### PR TITLE
Add example for Wombat Plan review

### PR DESCRIPTION
**Pull request by ivargrimstad**
Signed-off-by: Ivar Grimstad <ivar.grimstad@eclipse-foundation.org>

## Specification PR template
When creating a specification project plan review, create PRs with the content defined as follows.

Include the following in the PR:
- [ ] A directory in the form wombat/x.y where x.y is the release major.minor version.
- [ ] An index page wombat/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
- [ ] Title should be on the form "Jakarta Wombat X.Y (under development)"
- [ ] Includes a plan for the release. Usually, a couple of statements is enough. Otherwise, a link to a document describing the release.
- [ ] Includes a detailed description of any backward incompatibility (Mark with **N/A** and check if none)
- [ ] Declares optional features if there are any (Mark with **N/A** and check if none)
- [ ] Includes minimum Java SE version
- [ ] Describe any updates or required changes including splitting out the TCK (Mark with **N/A** and check if not planned)
- [ ] Link to updated release record

### CODE REVIEW

**Comment by kwsutter** [comment]
@Ivar, is the request for an updated release record sufficient?  Do we need to ask for a "release plan"?  This may be part of the release record, or it could be a separate document (like we did with Jakarta EE 9).  But, I think we need to document that requirement for a plan review.

**Comment by ivargrimstad** [comment]
@kwsutter It is just a suggestion. I wanted to start small to avoid adding overhead unless needed.
In my opinion, a release plan in the form of a couple of statements and a release record should be enough in most cases for the component specifications. No need to overdo it. For the platform or releases where there are significant changes planned, a document may make sense. But shouldn't be a general requirement.

**Comment by kwsutter** [comment]
> @kwsutter It is just a suggestion. I wanted to start small to avoid adding overhead unless needed.
> In my opinion, a release plan in the form of a couple of statements and a release record should be enough in most cases for the component specifications. No need to overdo it. For the platform or releases where there are significant changes planned, a document may make sense. But shouldn't be a general requirement.

Agree, @ivargrimstad.  But, we need to request a "plan" of some type.  The "plan" could be part of the release record.  Or, it can be a separate doc or web site.  But, we need to have them provide a "plan" of some sort.

**Comment by ivargrimstad** [comment]
> > @kwsutter It is just a suggestion. I wanted to start small to avoid adding overhead unless needed.
> > In my opinion, a release plan in the form of a couple of statements and a release record should be enough in most cases for the component specifications. No need to overdo it. For the platform or releases where there are significant changes planned, a document may make sense. But shouldn't be a general requirement.
> 
> Agree, @ivargrimstad. But, we need to request a "plan" of some type. The "plan" could be part of the release record. Or, it can be a separate doc or web site. But, we need to have them provide a "plan" of some sort.

I have added an item in the checklist (item 3) that should cover this. Should it be detailed even further?

**Comment by kwsutter** [comment]
@ivargrimstad, this PR is still in Draft mode.  Should we convert it, review it, approve it, and merge it?

**Comment by ivargrimstad** [comment]
I think we now have so many live examples, that this one has played out its role

**Pull request closed without merging**
