### PR TITLE
Jakarta Concurrency 3.1

### PR DESCRIPTION
**Pull request by KyleAure**
## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
- [x] Specification HTML in the form of jakarta-wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
- [x] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [x] Updated release record - https://jakarta.ee/specifications/concurrency/3.1/
   - [x] ~Generated IP Log~
   - [x] Email to PMC - Release review https://projects.eclipse.org/projects/ee4j.cu/reviews/3.1-release-review
   - [ ] Start release review by emailing EMO 
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      - https://jakarta.oss.sonatype.org/content/repositories/jakartaenterpriseconcurrent-1022
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      - Staged:     https://download.eclipse.org/ee4j/cu/jakartaee11/staged/eftl/
      - Promoted: https://download.eclipse.org/ee4j/cu/jakartaee11/promoted/eftl/
- [x] The URL of the compatibility certification request issue:
      - https://github.com/jakartaee/concurrency/issues/480
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Review by edbratt — CHANGES_REQUESTED** [review]
- [ ] Please revise the TCK and Specification licenses to v1.1 (sorry these changes may have been inadequately communicated to the project teams). This is required in the Specification documents as well as the API Docs and also the TCK (multiple locations)
- [x] Please address differences in TCK SHA sums between this PR and the CCR
- [x] Please confirm that the TCK results test and skip counts are correct for the CCR
- [x] Please review the page content (_index.md) to ensure that all the changes are final, appropriately summarize and definite.
- [ ] Please update the page content to reflect OpenLiberty is the initial CI

This is further detailed by e-mail to cu-dev@eclipse.org.

**Comment by mtdelgadoa** [comment]
Hello all, 
the EMO is trying to avoid duplication of release records, so we will be providing our feedback and comments related to this release directly here.

## EMO REVIEW CHECKLIST 

EDP Review status: ONGOING

### **EMO review checklist**
PMI record: [URL](https://projects.eclipse.org/projects/ee4j.cu/reviews/3.1-release-review)

_**EF Specification Process**_      
- [ ] Spec Committee Ballot completed

_**Intellectual Property Management**_      
- [ ] All project code has [copyright and license headers](https://www.eclipse.org/projects/handbook/#ip-copyright-headers) correctly applied. ** EMO will scan the code at their discretion **   
- [ ]  All distributed third-party content has been vetted by the IP Due Diligence process (i.e., IP Log has been approved)   

_**Open Source Rules of Engagement**_
- [ ] PMC approval [on the mailing list](https://github.com/eclipsefdn/emo-team/emo/-/blob/main/%7Blink%20to%20the%20message%7D)

General:
- [ ] Project is operating within the mission and scope defined in its top-level project’s charter   
- [ ]  Project is operating within the bounds of its own scope   
- [ ]  Project is operating in an open and transparent manner       
- [ ]  Overall the project is operating according to the Eclipse Development Process.   

Things to check:
- Communication channels advertised
- Advertised communication channels used
- Committers are responding to questions
- Committers are responding to issues
- Committers are responding to pull/merge/review requests

_**Branding and Trademarks**_
The following applies when the project has a custom website.
To the best of our knowledge:
- [ ]  Project content correctly uses Eclipse Foundation trademarks    
- [ ] Project content (code and documentation) does not violate trademarks owned by other organizations   

Things to check:
- [ ]  Project website uses the [project's formal name](https://www.eclipse.org/projects/handbook/#trademarks-website-name) in first and all prominent references
- [ ]   Project website includes a trademark attribution statement
- [ ] Project website footers contain all [necessary elements](https://www.eclipse.org/projects/handbook/#trademarks-website-footer)

_**Legal Documentation**_
Required files:   
- [ ] License files in all repository roots   
- [ ]  README       
- [ ]  CONTRIBUTING (or equivalent)   

Recommended files:
- [ ] NOTICES or equivalent (you can use the [Legal Documentation generator](https://www.eclipse.org/projects/tools/documentation.php) available under committer tools)   
- [ ]  CODE_OF_CONDUCT   
- [ ]  SECURITY   
 
See examples for [Security file](https://gitlab.eclipse.org/security/best-practices/-/blob/main/templates/SECURITY.md) and [Code of Conduct](https://github.com/eclipse/.github/blob/master/CODE_OF_CONDUCT.md).

Required elements:
- [ ]  ECA is referenced/described   

Recommended elements:
- [ ]  Build instructions provided   
- [ ] [Security policy](https://www.eclipse.org/security/policy.php) is described   
 
_**Metadata (PMI)**_
- [ ] The formal name, e.g. "Eclipse Foo™", is used in the project title   
- [ ] The formal name including appropriate marks (e.g, "™") is used in the first mention in the text of the project description, and scope   
- [ ] The project description starts with a single paragraph that can serve as an executive summary   
- [ ] Source code repository references are up-to-date   
- [ ] Download links and information are up-to-date (see [EF handbook for more information on how-to do this](https://www.eclipse.org/projects/handbook/#resources-downloads))   
- [ ] Communication channels listed in the PMI (i.e. public mailing list, forums, etc.)

**Comment by arjantijms** [comment]
Regarding  https://github.com/jakartaee/platform/pull/881 we need to make sure no TCK tests are in conflict with that.

Currently I think "AnnotationFullTests" in the Concurrency TCK is. 

cc @OndroMih @aubi @njr-11

**Comment by arjantijms** [comment]
> If you found a TCK test that is incorrect or inconsistent with requirements, let's open a challenge issue against the TCK for it with a more specific description identifying what is wrong in the test.

I didn't run the test personally, but several GlassFish committers did (specifically @aubi), and found that there was an *Definition annotation with qualifiers on a bean that was set not to be scanned by CDI.

As the TCK is not yet final (the ballot hasn't started), I think the challenge process is not needed, and we can just adjust the test?

cc @ivargrimstad 


@aubi Maybe you can do a PR to update the failing test? It's maybe as simple as giving the class a bean defining annotation, or using a beans.xml to set all beans to being scanned.

**Comment by njr-11** [comment]
> As the TCK is not yet final (the ballot hasn't started), I think the challenge process is not needed, and we can just adjust the test?

Kyle had staged a copy of the TCK/spec that was supposed to be final, but problems were found with the licenses and inconsistent checksums, so that needed to be rebuilt and restaged.  Regardless of whether it's a challenge or not, using a separate issue for the discussion and updates seems appropriate rather than having the discussion here in the specification pull.  Regarding adjusting the test, would adding `@ApplicationScoped` to the `AnnotationServlet` that defines the resources be sufficient?

**Comment by OndroMih** [comment]
I think so, @njr-11. @aubi , can you try if it helps you to pass the test with Payara?

**Comment by edburns** [comment]
Related: https://github.com/jakartaee/concurrency/pull/491 .

**Comment by njr-11** [comment]
@edbratt This pull and the CCR should now reflect all of the changes that you asked for.

**Comment by edbratt** [comment]
# Spec Review Checklist

1. Spec PR
  - [x] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [x] Directory of form {spec}/x.y
  - [x] PDF of form jakarta-{spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [x] HTML of form jakarta-{spec}-spec-x.y.html ("-spec" preferred but not required)
  - [x] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [x] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [x] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [x] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta.{spec}-api/x.y.z/
  - [x] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [x] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] (Optional) Second PR for just apidocs

2. _index.md
  - [x] Link to project release plan of the form https://projects.eclipse.org/projects/ee4j.{spec}/releases/x.y/plan
  - [x] Link to spec pdf
  - [x] Link to spec html
  - [x] Link to apidocs
  - [x] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip (The folder path is required, the file name pattern is preferred.)
  - [x] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [x] Name of and link to at least one Compatible Implementation
  - [x] Review summary statement to ensure it has been updated to reflect the work accomplished and does not contain proposal statements as might be found in Plan Review statement.

3. javadocs
  - [x] Footer contains Eclipse copyright and link to license
  - [x] ESFL license is included, usually as doc-files/speclicense.html
  - [x] no META-INF directory in PR
  - [x] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [x] Correct spec title
  - [x] Version number of the form x.y, not x.y.z
  - [x] Correct Eclipse copyright line
  - [x] No DRAFT or SNAPSHOT
  - [x] Correct Logo

5. Spec HTML
  - [x] Same as PDF

6. TCK zip file
  - [x] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [x] User's Guide (or equivalent documentation)
  - [x] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [x] Software requirements listed
  - [x] Installation and configuration described
  - [x] How to run tests
  - [x] Where to file challenges

8. Compatibility certification request
  - [x] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [x] SHA-256 fingerprint matches staged TCK zip file
  - [x] Request issue has `certification` label.

9. TCK results summary
  - [x] Page is hosted by Compatible Implementation project
  - [x] Includes all information from certification request
  - [x] Summary includes number of tests passed, failed, errors
  - [x] SHA-256 fingerprint matches staged TCK zip file on cert request

10. If a Release Review is required, the specification project team contacts the EMO to initiate the review by sending an email to emo@eclipse.org.
    (A Release Review is not required if the current release is a Service Release based on a previously successful Major or Minor
    release as indicated by a release record on the project's Releases page, e.g., the [Jakarta Servlet releases page](https://projects.eclipse.org/projects/ee4j.servlet/reviews).)
    - [x] The specification project team requests approval by sending an email to the EMO (with cc to the PMC) that contains a link to **this** PR and a request to the PMC for approval.
          
11. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Review by edbratt — COMMENTED** [review]
All issues in the PR are addressed. Checking if we can proceed with the TCK contents as they currently are....

**Review by edbratt — APPROVED** [review]
LGTM. Thank you!

**Comment by edbratt** [comment]
- [x] adds this final checklist to the main PR.
 - [x] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [x] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0). See [here](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/323/)
 - [x] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [x] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [x] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [x] creates an issue in the specification project that includes the following checklist for the specification project team:
   https://github.com/jakartaee/concurrency/issues/507

**Pull request merged**
