### PR TITLE
Jakarta Messaging 3.0 Final

### PR DESCRIPTION
**Pull request by dblevins**
Signed-off-by: David Blevins <david.blevins@gmail.com>

## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
- [x] Specification HTML in the form of jakarta-wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
- [ ] For a Release Review, a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/jms/jakarta.jms-api/3.0.0/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-messaging-tck-3.0.0.zip
      sha256: 2f5e099d9862227d9494e413ebd15033961c4271237453d1d48eb0b0005fd89c
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/jms-api/issues/283
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by dblevins** [comment]
Next steps to get out of Draft status:

 - Review TCK and promote
 - Get a certification request
 - Release/tag the source
 - Update API docs
 - Update specification PDF/HTML

**Comment by edbratt** [comment]
# Spec Review Checklist

1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form jakarta-{spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form jakarta-{spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta.{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] (Optional) Second PR for just apidocs

2. _index.md
  - [ ] Link to project release plan of the form https://projects.eclipse.org/projects/ee4j.{spec}/releases/x.y/plan
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip (The folder path is required, the file name pattern is preferred.)
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request
 
10. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Comment by kwsutter** [comment]
Found a couple of items, @dblevins...

- The javadoc is referencing the 2.0 version of the Specification (near the bottom of the first page of the javadoc).
   Package Specification
          [Jakarta Messaging 2.0 specification](https://jakarta.ee/specifications/messaging/2.0/) 
- I found that reference when I was looking for some indication of the version of the javadoc.  I can't find any reference to what version of the API the javadoc supports.  All of the other javadocs reference the version of the Spec/API that it represents.
- The javadoc footer doesn't have a link to the EFSL license. The copyright is there, but not a link to the EFSL.
- The copyright in the Specs only contains the year 2020?  Why wouldn't it contain the year we started the Jakarta EE effort?  2018, 2020  or 2019, 2020
- The Eclipse release record (https://projects.eclipse.org/projects/ee4j.jms/releases/3.0.0) needs updating.  It needs a more accurate date (Nov 06 or later).  And, it needs another sentence or two explaining what's in this major release of JMS.  (The EMO is requesting something more than just pointing at the Jakarta EE 9 release plan.)

FYI, @edbratt, I just took a look at the TCK and verified the last items on the checklist (instructions, requirements, challenge process, etc).

**Review by kwsutter — COMMENTED** [review]
Posted comments earlier that need to be addressed.

**Review by edbratt — CHANGES_REQUESTED** [review]
Checklist is much further along. Please review comments from @kwsutter

**Comment by dblevins** [comment]
Now updated:

 - [x] javadoc is referencing the 2.0 version
 - [x] javadoc has version in upper right
 - [x] javadoc footer has EFSL
 - [x] javadoc ESFL license is included as doc-files/speclicense.html
 - [x] javadoc has no META-INF directory
 - [x] specification copyright year includes 2019
 - [x] release record has Nov 6th date
 - [x] release record description expanded to cover package rename

This optional item is not done

 - [ ] javadocs-jar artifact matches apidocs (optional for this release)

**Comment by kwsutter** [comment]
@dblevins Thanks!  Not sure if I missed it on the first time or if it was just introduced, but the Copyright at the bottom of the javadoc says "Copyright © 2019 Eclipse Foundation. All rights reserved."  I think this should be updated to include 2020.  Hopefully this is relatively easy to change and we can still start the ballot today.  Otherwise, it looks like you addressed all of my other questions.  Thanks again!

I'm off this afternoon, so I'll leave the final approval to @edbratt.  Fix the Copyright and we're good to go from my perspective.

**Comment by arjantijms** [comment]
Should there be a need to re-stage artefacts or re-run the TCK, let me know. A TCK run is trivial to start. It takes very consistently 43 minutes.

**Comment by edbratt** [comment]
@kwsutter I made a similar comment in the jms-api PR. @arjantijms What changed in the TCK causing it to be restaged?

**Comment by dblevins** [comment]
@kwsutter @edbratt Copyright year in Javadoc has been updated

**Review by edbratt — APPROVED** [review]

**Comment by kwsutter** [comment]
> @kwsutter I made a similar comment in the jms-api PR. @arjantijms What changed in the TCK causing it to be restaged?

@edbratt I don't think anything changed with the TCK. It has the same SHA value as yesterday.  I think @arjantijms was just offering to quickly re-run the test suite IF there were changes that required a re-execution.

**Review by kwsutter — APPROVED** [review]
Thanks, @dblevins and @arjantijms.  Looks good!

**Comment by kwsutter** [comment]
Sorry, @edbratt!  The github UI was too slow and I accidentally reset your Approval review when I was only trying to do mine.  My apologies!

**Comment by edbratt** [comment]
Awaiting verification in Eclipse GlassFish for fix to https://github.com/eclipse-ee4j/glassfish/issues/23253 to begin ballot. @dblevins could you bump the link to the compatible implementation to [Open MQ 6.0.0 M3](https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/mq/mq-distribution/6.0.0-M2/mq-distribution-6.0.0-M2.zip). I do not think that GlassFish RC 1 should be referenced (and I've removed it from the CCR).

**Comment by edbratt** [comment]
> Sorry, @edbratt! The github UI was too slow and I accidentally reset your Approval review when I was only trying to do mine. My apologies!

No worries. We're rerunning the failed Jakarta EE TCK tests using MQ M3. Presuming those results are good and we can get a bump to the compatible implementation in this _index.md, we should be good to go with the ballot.

**Comment by kwsutter** [comment]
@edbratt and @dblevins Took care of the updates to _index.md.  Looks like I messed up with the "signed off" footer, but we're close enough for the ballot...  :-)

**Comment by dblevins** [comment]
@kwsutter  thanks, Kevin!

**Comment by edbratt** [comment]
[Tests are good](https://ci.eclipse.org/jakartaee-tck/job/build-glassfish/86/)

**Review by edbratt — APPROVED** [review]
All looks good!

**Comment by dblevins** [comment]
Who hoo!!  Go team :)

**Comment by arjantijms** [comment]
>  I think @arjantijms was just offering to quickly re-run the test suite IF there were changes that required a re-execution.

Indeed ;)

Now good to see all was finished in time :)

**Comment by kwsutter** [comment]
FYI, the "extra" commit after the ballot started was to just [sign off on the commit](https://github.com/jakartaee/specifications/pull/256#issuecomment-715651058) that was done prior to the vote...  So, it was only a commit message update, no change to files.

**Comment by arjantijms** [comment]
Ballot successful: https://eclipse.org/lists/jakarta.ee-spec/msg01298.html 🎊

**Comment by arjantijms** [comment]
CQ/IP log bug: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22774

**Comment by edbratt** [comment]
- [x] adds this final checklist to the main PR.
 - [ ] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [ ] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
 - [ ] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [ ] creates an issue in the specification project that includes the following checklist for the specification project team:
  https://github.com/eclipse-ee4j/jms-api/issues/286

**Pull request merged**
