### PR TITLE
Jakarta Enterprise Web Services 1.4 Specification

### PR DESCRIPTION
**Pull request by dblevins**
## Specification PR template
When creating a specification project release review, create two PRs with the content divided as follows.

Include the following in PR#1:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of wombat-spec-x.y.pdf
- [x] Specification HTML in the form of wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] For a Progress Review, that sufficient progress has been made on
      a Compatible Implementation and TCK, to ensure that the spec is
      implementable and testable.
- [x] For a Release Review, a summary that a Compatible Implementation
      is complete, passes the TCK, and that the TCK includes sufficient
      coverage of the specification. The TCK users guide MUST include
      the instructions to run the compatible implementations used to
      validate the release.  Instructions MAY be by reference.
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      N/A - There is no API jar for this specification
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      N/A - Covered by [Jakarta EE Platform TCK](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-jakartaeetck-8.0.0.zip)
- [x] The URL of the compatibility certification request issue:
      [Eclipse Glassfish Certification Request](https://github.com/eclipse-ee4j/jakartaee-platform/issues/99) 
https://github.com/eclipse-ee4j/jax-ws-api/issues/83

Include the following in PR#2:
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory.
      N/A - There is no API jar for this specification

### CODE REVIEW

**Comment by dblevins** [comment]
# Spec Review Checklist

## 1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://oss.sonatype.org/conte/repositories/staging/jakarta/{spec}/jakarta-{spec}-api/x.y.z/
https://oss.sonatype.org/content/repositories/staging/jakarta/jms/jakarta.jms-api/2.0.3/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] Second PR for just apidocs

## 2. _index.md
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

## 3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

## 4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

## 5. Spec HTML
  - [ ] Same as PDF

## 6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG) (refers to RI)

## 7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

## 8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
fd175e1742a1c9e23dbc0aa0b8b881965fcead0336c121c2dac27a00a8fa113d
  - [ ] Request issue has `certification` label.

## 9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

**Comment by dblevins** [comment]
@bshannon both should be correct now.  Updated pr coming on `jax-ws-api` repo

**Comment by edbratt** [comment]
I believe that the Certification Request issue should be filed against JAX-WS-API repository: https://github.com/eclipse-ee4j/jax-ws-api/issues. This is where the Scope Statement and Boiler Plate discussions were held.

**Comment by dblevins** [comment]
@edbratt @bshannon Certification request updated.

**Comment by bshannon** [comment]
* On ballot completion
 - [ ] The designated specification committee representative adds this final checklist to the main PR.
 - [ ] The specification committee representative merges the specification and apidocs PRs.
 - [ ] The designated specification committee representative calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job.
 - [ ] The specification project member who created the staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [ ] The EMO updates the specification page with the ballot results.
This list goes on the committed spec index page.
 - [ ] The specification project team should go through the merged spec website page to verify all the links are valid.
 - [ ] The specification project team should approve the compatibility request.
 - [ ] The compatible implementation project/vendor MUST send an email tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [ ] The specification project team should merge any final release branch as appropriate for the branch management for the project.

**Comment by bshannon** [comment]
@dblevins Please check off the project team items above that have been completed.

@waynebeaton The ballot results are not on the spec page.

**Comment by dblevins** [comment]
@bshannon there's been no action.  Can someone please attend to the certification request? https://github.com/eclipse-ee4j/jax-ws-api/issues/83#issuecomment-528617702

**Comment by bshannon** [comment]
@dblevins Certification request done, please complete the other items.

**Comment by dblevins** [comment]
Someone who is a committer will have to do this item:

"The specification project team should merge any final release branch as appropriate for the branch management for the project."

FYI back on air for JakartaOne Live in a few minutes.  Then 3 hours to prepare for another live session.

**Pull request merged**
