### PR TITLE
Jakarta Activation 2.0 spec

### PR DESCRIPTION
**Pull request by bshannon**
Signed-off-by: Bill Shannon <bill.shannon@oracle.com>

## Specification PR template
When creating a specification project release review, create two PRs with the content divided as follows.

Include the following in PR#1:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of wombat-spec-x.y.pdf
- [x] Specification HTML in the form of wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [ ] For a Progress Review, that sufficient progress has been made on
      a Compatible Implementation and TCK, to ensure that the spec is
      implementable and testable.
- [x] For a Release Review, a summary that a Compatible Implementation
      is complete, passes the TCK, and that the TCK includes sufficient
      coverage of the specification. The TCK users guide MUST include
      the instructions to run the compatible implementations used to
      validate the release.  Instructions MAY be by reference.
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/activation/jakarta.activation-api/2.0.0/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      http://download.eclipse.org/ee4j/jaf/tck/eftl/jakarta-activation-tck-2.0.0.zip
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/jaf/issues/40

Include the following in PR#2:
- [ ] Specification JavaDoc in the wombat/x.y/apidocs directory.

### CODE REVIEW

**Comment by bshannon** [comment]
> ... I noticed the Copyright for the Spec still only indicated 2019. That should be updated to 2020. You also need a Scope statement in the 2.0 index file... thanks again!

Fixed.

**Comment by kwsutter** [comment]
Hi @bshannon.  Can we convert this PR into a Milestone PR instead?  Or, close this one and create a new one?  Whatever is easier.  Thanks!  (Same thing for the Activation apidocs PR #143.)

We are also looking for Jakarta Mail Milestone PRs as well (just as a reminder).  Thanks!

**Comment by lukasj** [comment]
replaced by/copied to #172

**Comment by kwsutter** [comment]
Since @lukasj is superseding these PRs with alternate PRs per https://github.com/jakartaee/specifications/pull/142#issuecomment-637609523, I'm going to close this PR to avoid confusion.

**Pull request closed without merging**
