### PR TITLE
Add Hibernate ORM 5.5.0.Final as compatible JPA 2.2 implementation

### PR DESCRIPTION
**Pull request by beikov**

### CODE REVIEW

**Comment by ivargrimstad** [comment]
Certification request: https://github.com/eclipse-ee4j/jpa-api/issues/323

**Review by kwsutter — APPROVED** [review]

**Comment by ivargrimstad** [comment]
I'll merge this and follow up with a separate PR to add the "used for ratification" list item as decided by the spec committee.

**Comment by beikov** [comment]
Do we need to do something special to get https://jakarta.ee/specifications/persistence/2.2/ and https://jakarta.ee/specifications/persistence/3.0/ updated? @ivargrimstad

**Comment by ivargrimstad** [comment]
@beikov It is merged and the update jobs for the site goes every 24 hours. Usually around noon, so possibly available soon...

**Comment by ivargrimstad** [comment]
@beikov  It's live now!

**Pull request merged**
