### PR TITLE
Jakarta Authentication 1.1 apidocs

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

- [X ] Specification JavaDoc in the wombat/x.y/apidocs directory.

### CODE REVIEW

**Comment by starksm64** [comment]
The javadoc does not have the EFTL license and link.

**Comment by arjantijms** [comment]
@starksm64 are you sure, it should be there:

* https://github.com/jakartaee/specifications/pull/39/files#diff-3eada619cbe8568a227cb2d2645d9c7a
* https://github.com/jakartaee/specifications/pull/39/files#diff-5fbf8dfc22b309e0e275a2771ad5f1f5R231

**Comment by starksm64** [comment]
> @starksm64 are you sure, it should be there:
> 
> * https://github.com/jakartaee/specifications/pull/39/files#diff-3eada619cbe8568a227cb2d2645d9c7a
> * https://github.com/jakartaee/specifications/pull/39/files#diff-5fbf8dfc22b309e0e275a2771ad5f1f5R231

You are right, I'm seeing this now:

<p class="legalCopy"><small>Comments to: <a href="mailto:jaspic-dev@eclipse.org">jaspic-dev@eclipse.org</a>.<br> Copyright &#169; 2019 Eclipse Foundation. All rights reserved.<br> Use is subject to <a href="../../../../doc-files/speclicense.html" target="_top">license terms</a>.</small></p>

**Comment by dblevins** [comment]
@starksm64 don't forget to merge the apidocs

**Pull request merged**
