### PR TITLE
Jakarta EE 8 Platform apidocs

### PR DESCRIPTION
**Pull request by kwsutter**
## Specification PR template
When creating a specification project release review, create two PRs with the content divided as follows.

Include the following in PR#2:
- [x] Specification JavaDoc in the platform/8/apidocs directory.

### CODE REVIEW

**Comment by bshannon** [comment]
This generally looks good.  @kwsutter do you believe this is up to date?

I did make a tiny tweak to the copyright line in the footer; I updated the source
repo so if you need to regenerate these for any reason you should pick up the fix.

**Comment by kwsutter** [comment]
Thanks, @bshannon.  I was going to do another generation anyway, so I'll pick up your changes.  But, this content should be pretty much it...

**Comment by kwsutter** [comment]
> I did make a tiny tweak to the copyright line in the footer; I updated the source
> repo so if you need to regenerate these for any reason you should pick up the fix.

@bshannon Where was this tweak in the copyright?  Was there a PR that needed to be reviewed or merged?  I can't find it.  Thanks!

**Comment by bshannon** [comment]
It was too trivial to waste time with a PR so I just committed it.
It changed "(c) Copyright" to "Copyright (c)".

**Pull request merged**
