### PR TITLE
Jakarta Batch 1.0 Specification

### PR DESCRIPTION
**Pull request by scottkurz**
Signed-off-by: Scott Kurz <skurz@us.ibm.com>

## Specification PR template
When creating a specification project release review, create two PRs with the content divided as follows.

Include the following in PR#1:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of wombat_x.y.pdf
- [x] Specification HTML in the form of wombat_x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] For a Release Review, a summary that a Compatible Implementation
      is complete, passes the TCK, and that the TCK includes sufficient
      coverage of the specification. The TCK users guide MUST include
      the instructions to run the compatible implementations used to
      validate the release.  Instructions MAY be by reference.
- [x] The URL of the OSSRH staging repository for the api, javadoc:
    https://oss.sonatype.org/content/repositories/staging/jakarta/batch/jakarta.batch-api/1.0.2/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
http://download.eclipse.org/jakartabatch/tck/eftl/jakarta.batch.official.tck-1.0.2.zip.   (**NOTE:** Since the eclipse.org mirroring is slow, it is more convenient to use the OSSRH staging repo URL: https://oss.sonatype.org/content/repositories/staging/jakarta/batch/jakarta.batch.official.tck/1.0.2/jakarta.batch.official.tck-1.0.2.zip)
- [x]  The URL of the compatibility certification request issue: 
https://github.com/eclipse-ee4j/batch-api/issues/5

Include the following in PR#2:
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory.

### CODE REVIEW

**Comment by scottkurz** [comment]
Please add 'draft' label (and feel free to suggest a downloads.eclipse.org  URL).  Thank you.

**Comment by bshannon** [comment]
The staging repository link we want is this:
https://oss.sonatype.org/content/repositories/staging/jakarta/batch/jakarta.batch-api/1.0.2/

**Comment by scottkurz** [comment]
Updated the staging repo URL.

Fixed the spec rev number issue.

 Not sure what the next step(s) are for the TCK download URL.

**Comment by scottkurz** [comment]
> 
> 
> The Specification document needs to remove the "DRAFT" designation per the post on the Spec Leads list... https://www.eclipse.org/lists/jakartaee-spec-project-leads/msg00067.html

Done (rebased so I lost the original commit the comment was hooked to).

**Comment by scottkurz** [comment]
@bshannon  - I think this PR is now ready... thanks again for spelling out the detail we were looking for w.r.t pointing to the TCK zips/results.      

Note the "change requested" review from @kwsutter can be ignored...  I guess in force-pushing over them I can't now mark them as "resolved" (or haven't found how).

Thanks.

**Comment by scottkurz** [comment]
Actually I'm going to uncheck the staging repo for the API.  As mentioned here
https://github.com/eclipse-ee4j/batch-api/issues/1, I should respin based on the Jakarta dependency.

**Comment by dblevins** [comment]
Spec PDF looks good

**Comment by kwsutter** [comment]
Just a clarification on this approval...  I had made some previous review comments that were no longer "resolvable", so I just accepted the changes.  There are still some changes we're working through on this PR before it can be marked "done".

**Comment by dblevins** [comment]
This spec is due for review and promotion to vote August 16th.  Can you review this checklist and ensure all requirements are met:
https://github.com/jakartaee/specification-committee/blob/master/spec_review_checklist.md

**Comment by scottkurz** [comment]
> This spec is due for review and promotion to vote August 16th. Can you review this checklist and ensure all requirements are met:
> https://github.com/jakartaee/specification-committee/blob/master/spec_review_checklist.md

Thx @dblevins, I think this is completely ready, except for a couple places where we use the staged TCK and need to go back and do a final run (update SHA, etc.).

**Comment by kwsutter** [comment]
# Spec Review Checklist

1. Spec PR
  - [x] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [x] Directory of form {spec}/x.y
  - [x] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [x] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [x] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [x] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [x] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [x] Staging repository link of the form https://oss.sonatype.org/conte/repositories/staging/jakarta/{spec}/jakarta-{spec}-api/x.y.z/
  - [x] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [x] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [x] Second PR for just apidocs

2. _index.md
  - [x] Link to spec pdf
  - [x] Link to spec html
  - [x] Link to apidocs
  - [x] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [x] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [x] Name of and link to at least one Compatible Implementation

3. javadocs
  - [x] Footer contains Eclipse copyright and link to license
  - [x] ESFL license is included, usually as doc-files/speclicense.html
  - [x] no META-INF directory in PR
  - [x] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [x] Correct spec title
  - [x] Version number of the form x.y, not x.y.z
  - [x] Correct Eclipse copyright line
  - [x] No DRAFT or SNAPSHOT
  - [x] Correct Logo (no logo)

5. Spec HTML
  - [x] Same as PDF

6. TCK zip file
  - [] README file (optional for this release) (README.adoc)
  - [] EFTL license file, preferably named LICENSE.md (LICENSE)
  - [] User's Guide (or equivalent documentation)
  - [] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [] Software requirements listed
  - [] Installation and configuration described
  - [] How to run tests
  - [] Where to file challenges

8. Compatibility certification request
  - [] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [] SHA-256 fingerprint matches staged TCK zip file
75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808
  - [] Request issue has `certification` label.

9. TCK results summary
  - [] Page is hosted by Compatible Implementation project
  - [] Includes all information from certification request
  - [] Summary includes number of tests passed, failed, errors
  - [] SHA-256 fingerprint matches staged TCK zip file on cert request

**Comment by kwsutter** [comment]
* On ballot completion
 - [x] The designated specification committee representative adds this final checklist to the main PR.
 - [ ] The specification committee representative merges the specification PRs.
 - [ ] The designated specification committee representative calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job.
 - [ ] The specification project member who created the staging release promotes the specification api jars to maven central.
 - [ ] The EMO updates the specification page with the ballot results.
This list goes on the committed spec index page.
 - [ ] The specification project team should go through the merged spec website page to verify all the links are valid.
 - [ ] The specification project team should approve the compatibility request and send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [ ] The specification project team should merge any final release branch as approriate for the branch management for the project.

**Pull request merged**
