### PR TITLE
WebSocket 2.0.0 Javadoc part2

### PR DESCRIPTION
**Pull request by markt-asf**
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

### CODE REVIEW

**Comment by m0mus** [comment]
`META-INF` should be excluded.

**Comment by markt-asf** [comment]
> Remove META-INF folder

Please review the PR more carefully. This PR removes an existing META-INF folder.

**Comment by m0mus** [comment]
> > Remove META-INF folder
> Please review the PR more carefully. This PR removes an existing META-INF folder.

Sorry, my bad. I approved.

**Comment by keilw** [comment]
I see the API repository got the automatic-module-name resolution merged: https://github.com/eclipse-ee4j/websocket-api/commit/a990b230d6f9e375855c9c121d89a4160a62a287

**Comment by edbratt** [comment]
Sorry, one quick request: Could we fix the typo in the top index table?
https://deploy-preview-235--jakartaee-specifications.netlify.app/specifications/websocket/2.0/apidocs/
"This package contains all the Jakartq WebSocket APIs common to both the client and server side."
(Change Jakartq to Jakarta)? Sorry, I just noticed this. Once you see it, you can't un-see it!

**Comment by joakime** [comment]
> Sorry, one quick request: Could we fix the typo in the top index table?
> https://deploy-preview-235--jakartaee-specifications.netlify.app/specifications/websocket/2.0/apidocs/
> "This package contains all the Jakartq WebSocket APIs common to both the client and server side."
> (Change Jakartq to Jakarta)? Sorry, I just noticed this. Once you see it, you can't un-see it!

That looks like a change needed at the websocket repo side ...

* https://github.com/eclipse-ee4j/websocket-api/blob/master/api/client/src/main/java/jakarta/websocket/package-info.java#L19

**Review by kwsutter — APPROVED** [review]
LGTM.  Thanks!

**Comment by edbratt** [comment]
- [x] adds this final checklist to the main PR.
 - [x] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [ ] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
 - [ ] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [ ] creates an issue in the specification project that includes the following checklist for the specification project team:
 \<include url of Issue here>

**Pull request merged**
