### PR TITLE
Update Platform TCK 10.0.1 + Jakarta Servlet TCK 6.0.1 for TCK challenge https://github.com/jakartaee/servlet/issues/472 + https://github.com/jakartaee/servlet/issues/471

### PR DESCRIPTION
**Pull request by scottmarlow**
Signed-off-by: Scott Marlow <smarlow@redhat.com>

## Jakarta Servlet 6.0 TCK update 
- [x] The tracking issue representing this update:
  Tracking specifications issues https://github.com/jakartaee/servlet/issues/472 + https://github.com/jakartaee/servlet/issues/471
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-servlet-tck-6.0.1.zip

## Jakarta Platform 10 TCK update 
- [x] The tracking issue representing this update:
  Tracking specifications issues https://github.com/jakartaee/servlet/issues/472 + https://github.com/jakartaee/servlet/issues/471
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jakartaeetck-10.0.1.zip

### CODE REVIEW

**Review by brideck — APPROVED** [review]

**Review by edbratt — CHANGES_REQUESTED** [review]
Please update your PR to reflect that these are new, additional TCKs. The originals are still valid and should be listed as legacy releases.

**Comment by edbratt** [comment]
The artifacts are promoted. Please be sure to use the new SHA-SUM and Signature file links for the added TCKs
-- Servlet 6.0.1 ([promotion job](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/261))
  - TCK https://download.eclipse.org/jakartaee/servlet/6.0/jakarta-servlet-tck-6.0.1.zip
  - SHA https://download.eclipse.org/jakartaee/servlet/6.0/jakarta-servlet-tck-6.0.1.zip.sha256
  - SIG https://download.eclipse.org/jakartaee/servlet/6.0/jakarta-servlet-tck-6.0.1.zip.sig

Platform 10.0.1 ([promotion job](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/262/))
  - TCK - https://download.eclipse.org/jakartaee/platform/10/jakarta-jakartaeetck-10.0.1.zip
  - SHA - https://download.eclipse.org/jakartaee/platform/10/jakarta-jakartaeetck-10.0.1.zip.sha256
  - SIG - https://download.eclipse.org/jakartaee/platform/10/jakarta-jakartaeetck-10.0.1.zip.sig

**Comment by edbratt** [comment]
Are CCR(s) available to verify these new TCKs are passed by an implementation?

**Comment by scottmarlow** [comment]
> Are CCR(s) available to verify these new TCKs are passed by an implementation?

https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/155/ ran against the staged (10.0.1) Platform TCK with https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.0-M9.zip

https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-standalonetck-build-run-100/114/ ran against the staged (6.0.1) Servlet TCK with https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.0-M9.zip

**Comment by scottmarlow** [comment]
> The artifacts are promoted. Please be sure to use the new SHA-SUM and Signature file links for the added TCKs -- Servlet 6.0.1 ([promotion job](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/261))
> 
>     * TCK https://download.eclipse.org/jakartaee/servlet/6.0/jakarta-servlet-tck-6.0.1.zip
> 
>     * SHA https://download.eclipse.org/jakartaee/servlet/6.0/jakarta-servlet-tck-6.0.1.zip.sha256
> 
>     * SIG https://download.eclipse.org/jakartaee/servlet/6.0/jakarta-servlet-tck-6.0.1.zip.sig
> 
> 
> Platform 10.0.1 ([promotion job](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/262/))
> 
>     * TCK - https://download.eclipse.org/jakartaee/platform/10/jakarta-jakartaeetck-10.0.1.zip
> 
>     * SHA - https://download.eclipse.org/jakartaee/platform/10/jakarta-jakartaeetck-10.0.1.zip.sha256
> 
>     * SIG - https://download.eclipse.org/jakartaee/platform/10/jakarta-jakartaeetck-10.0.1.zip.sig

Done, just pending further review of the changes.

**Review by edbratt — APPROVED** [review]

**Pull request merged**
