### PR TITLE
Promote CDI TCK 4.0.12

### PR DESCRIPTION
**Pull request by manovotn**
A new version of CDI TCK was released today and addressed two accepted TCK challenges:

* https://github.com/jakartaee/cdi-tck/issues/487
* https://github.com/jakartaee/cdi-tck/issues/485

### CODE REVIEW

**Comment by scottmarlow** [comment]
@ivargrimstad @starksm64 could one of you please run the promotion script?  Thank you!

**Comment by starksm64** [comment]
It has been promoted.

https://www.eclipse.org/downloads/download.php?file=/jakartaee/cdi/4.0/cdi-tck-4.0.12-dist.zip
288403829e63d049a28e68b145d1f6caa955f8ac28614c4cbae8f45ea2e923dd

**Comment by jamezp** [comment]
Maybe it's still uploading, but the ZIP seems bad.

**Comment by jamezp** [comment]
Actually, it seems to be downloading an HTML file. I'm getting a 404 on the download. Maybe I just need patience :)

**Comment by scottmarlow** [comment]
@starksm64 the contents of the [promoted file](wget https://download.eclipse.org/jakartaee/cdi/4.0/cdi-tck-4.0.12-dist.zip) looks like output from the promotion script but I am not sure.  

Starts with:
```
 <!DOCTYPE html>         
<html lang="en">     
  <head>          
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- Google Tag Manager -->
      <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
         new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
         j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
         'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
         })(window,document,'script','dataLayer','GTM-5WLCZXC');
      </script>
      <!-- End Google Tag Manager -->     
      <meta name="author" content="Christopher Guindon"/> 
      <meta name="keywords" content="eclipse.org, Eclipse Foundation"/>
      <link rel="shortcut icon" href="//www.eclipse.org/eclipse.org-common/themes/solstice/public/images/favicon.ico"/>
      <title>Not Found | The Eclipse Foundation</title>
      <link rel="stylesheet" href="//www.eclipse.org/eclipse.org-common/themes/solstice/public/stylesheets/quicksilver.min.css?v1.3"/>
      <meta name="description" content="The Eclipse Foundation - home to a global community, the Eclipse IDE, Jakarta EE and over 360 open source projects, including runtimes, tools and frameworks."/>
      <meta property="og:description" content="The Eclipse Foundation - home to a global community, the Eclipse IDE, Jakarta EE and over 360 open source projects, including runtimes, tools and frameworks."/>
      <meta property="og:image" content="https://www.eclipse.org/eclipse.org-common/themes/solstice/public/images/logo/eclipse-foundation-200x200.png"/>
      <meta property="og:title" content="Not Found | The Eclipse Foundation"/>
      <meta property="og:image:width" content="200"/>
      <meta property="og:image:height" content="200"/>
      <meta itemprop="name" content="Not Found | The Eclipse Foundation"/>
      <meta itemprop="description" content="The Eclipse Foundation - home to a global community, the Eclipse IDE, Jakarta EE and over 360 open source projects, including runtimes, tools and frameworks."/>
      <meta itemprop="image" content="https://www.eclipse.org/eclipse.org-common/themes/solstice/public/images/logo/eclipse-foundation-400x400.png"/>
      <meta name="twitter:site" content="@EclipseFdn"/>
      <meta name="twitter:card" content="summary"/>
      <meta name="twitter:title" content="Not Found | The Eclipse Foundation"/>
      <meta name="twitter:url" content="https://www.eclipse.org"/>
      <meta name="twitter:description" content="The Eclipse Foundation - home to a global community, the Eclipse IDE, Jakarta EE and over 360 open source projects, including runtimes, tools and frameworks."/>
      <meta name="twitter:image" content="https://www.eclipse.org/eclipse.org-common/themes/solstice/public/images/logo/eclipse-foundation-400x400.png"/>
      <link href="//fonts.googleapis.com/css?family=Libre+Franklin:400,700,300,600,100" rel="stylesheet" type="text/css"/>
      <script> var eclipse_org_common = {"settings":{"cookies_class":{"name":"eclipse_settings","enabled":1}}}</script>
   </head>                       
```

**Comment by manovotn** [comment]
FTR here is the link to the console output of the build which also seems to upload the dist file - https://ci.eclipse.org/cdi/job/CDI-TCK-Release-JDK11/114/console
(@starksm64 should have access, others I am not sure)

**Comment by scottmarlow** [comment]
From comparing console for CDI TCK promotion https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/287 + earlier promotion of REST TCK promotion https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/286, the first sign that something is different is:

Rest TCK determines:
> for url in '$FILE_URLS'
++ basename https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-restful-ws-tck-3.1.4.zip
> + file=jakarta-restful-ws-tck-3.1.4.zip

^ seemed to use the staged REST TCK.

CDI TCK determines:
> for url in '$FILE_URLS'
++ basename https://download.eclipse.org/jakartaee/cdi/4.0/cdi-tck-4.0.12-dist.zip
> + file=cdi-tck-4.0.12-dist.zip

^ didn't seem to use the staged CDI TCK.

**Comment by scottmarlow** [comment]
https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/283/console seemed to work with similar parameters passing in:

> ++ basename https://download.eclipse.org/ee4j/cdi/4.0/cdi-tck-4.0.11-dist.zip
> + file=cdi-tck-4.0.11-dist.zip

**Comment by scottmarlow** [comment]
Hmm, perhaps we need to instead pass in https://download.eclipse.org/ee4j/cdi/4.0/cdi-tck-4.0.12-dist.zip

**Comment by scottmarlow** [comment]
Thanks Scott, the promoted TCK zip is correct now!

**Pull request merged**
