### PR TITLE
Jakarta Servlet 4.0 apidocs

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

Include the following in PR#2:
- [X] Specification JavaDoc in the wombat/x.y/apidocs directory.

### CODE REVIEW

**Comment by dblevins** [comment]
Not sure if it's a showstopper, but we still have some "Java EE" references:

```
servlet/4.0/apidocs/javax/servlet/AsyncContext.html:766: This method supports resource injection if the given <tt>clazz</tt> represents a Managed Bean. See the Java EE
servlet/4.0/apidocs/javax/servlet/ServletContext.html:1411: Managed Bean. See the Java EE platform and JSR 299 specifications for additional details about Managed Beans and
servlet/4.0/apidocs/javax/servlet/ServletContext.html:1496: if the given <tt>servletClass</tt> represents a Managed Bean. See the Java EE platform and JSR 299 specifications
servlet/4.0/apidocs/javax/servlet/ServletContext.html:1577: method supports resource injection if the given <tt>clazz</tt> represents a Managed Bean. See the Java EE
servlet/4.0/apidocs/javax/servlet/ServletContext.html:1678: See the Java EE platform and JSR 299 specifications for additional details about Managed Beans and resource
servlet/4.0/apidocs/javax/servlet/ServletContext.html:1800: This method supports resource injection if the given <tt>clazz</tt> represents a Managed Bean. See the Java EE
servlet/4.0/apidocs/javax/servlet/ServletContext.html:2032: See the Java EE platform and JSR 299 specifications for additional details about Managed Beans and resource
servlet/4.0/apidocs/javax/servlet/ServletContext.html:2138: Java EE platform and JSR 299 specifications for additional details about Managed Beans and resource injection.</div>
servlet/4.0/apidocs/javax/servlet/ServletContext.html:2182: This method supports resource injection if the given <tt>clazz</tt> represents a Managed Bean. See the Java EE

```

**Comment by bshannon** [comment]
> Not sure if it's a showstopper, but we still have some "Java EE" references:

And some JSR 299 references.

**Comment by arjantijms** [comment]
I did all those things in https://github.com/eclipse-ee4j/servlet-api/pull/247 and I assumed that when Greg wanted to redo that all, he indeed would redo it all.

**Comment by arjantijms** [comment]
At the moment new PRs are being done to fix various Servlet issues. When that's done I'll re-stage and update this PR.

**Comment by starksm64** [comment]
@arjantijms are there more changes expected for this PR?

**Comment by arjantijms** [comment]
> @arjantijms are there more changes expected for this PR?

I'm not 100% sure. I did the PRs for Servlet, but then as mentioned above Greg asked whether he could do them as project lead, which is a fair request, so my original PR was closed and Greg would continue redoing everything.

But after that Greg only did a small PR which wasn't complete, and thereafter things went pretty quiet.

**Comment by stuartwdouglas** [comment]
I have submitted:
https://github.com/eclipse-ee4j/servlet-api/pull/260
and
https://github.com/eclipse-ee4j/servlet-api/pull/259

This adds speclicense.html and removes the Java EE and JSR references.

**Comment by stuartwdouglas** [comment]
@starksm64 as my Servlet PR's only affect Javadoc's once these are merged do I need to re-stage the artifact and (and hence re-run the TCK etc), or is it sufficient to just update this PR with the new Javadocs?

The only real difference that this would make is that the -javadoc.jar artifacts that have been staged will be slightly different to the versions that are published here.

**Comment by arjantijms** [comment]
@stuartwdouglas 

>  as my Servlet PR's only affect Javadoc's once these are merged do I need to re-stage the artifact and (and hence re-run the TCK etc),

I also restage and rerun the TCK after Javadoc changes, as the API is what we're ultimately testing here.

**Comment by starksm64** [comment]
> @starksm64 as my Servlet PR's only affect Javadoc's once these are merged do I need to re-stage the artifact and (and hence re-run the TCK etc), or is it sufficient to just update this PR with the new Javadocs?
> 
> The only real difference that this would make is that the -javadoc.jar artifacts that have been staged will be slightly different to the versions that are published here.

The api jars do need to be restaged so that the javadoc artifact is in sync with the website content. Since this is updating the api jars as well, the TCK should be run just to verify nothing else has actually changed.

**Comment by arjantijms** [comment]
> The api jars do need to be restaged so that the javadoc artifact is in sync with the website content. 

I'll restaged them then.

**Comment by arjantijms** [comment]
Restaged: 

* https://jenkins.eclipse.org/servlet/job/1_servlet-build-and-stage/18/console
* https://oss.sonatype.org/content/repositories/staging/jakarta/servlet/jakarta.servlet-api/4.0.3/

**Comment by starksm64** [comment]
I have created a PR to fix the remaining issue with the javadoc footer

**Comment by stuartwdouglas** [comment]
The footer was updated in master: https://github.com/eclipse-ee4j/servlet-api/commit/55fbbf81f3a8e449cf30583a2adce875297a1ec7

It looks like this PR has not been synched with the Javadoc changes

**Comment by arjantijms** [comment]
> I have created a PR to fix the remaining issue with the javadoc footer
arjantijms#1

Thx, it's merged now.

**Comment by starksm64** [comment]
> > I have created a PR to fix the remaining issue with the javadoc footer
> > [arjantijms#1](https://github.com/arjantijms/specifications/pull/1)
> 
> Thx, it's merged now.

I'm not seeing another commit show up on this pull request though, and the footer has not been updated?

**Comment by arjantijms** [comment]
> I'm not seeing another commit show up on this pull request though, and the footer has not been updated?

I see, you did the PR to my master, not to my PR.

**Comment by starksm64** [comment]
> I see, you did the PR to my master, not to my PR.

Sorry about that. I keep missing that the compare across forks switches back to master. I have created another PR against the servlet_apidocs branch.

**Comment by arjantijms** [comment]
@starksm64 
> Sorry about that. I keep missing that the compare across forks switches back to master. I have created another PR against the servlet_apidocs branch.

No worries, it seems to have worked now. I did had to force push the merge commit away, but otherwise all seems fine.

**Comment by starksm64** [comment]
> No worries, it seems to have worked now. I did had to force push the merge commit away, but otherwise all seems fine.

It looked good for bit, but as soon as I looked at a link to the license on anything but the top docs, the link was broke. So I just pulled down the servlet-api, rebuilt the javadoc on the 4.0.3 branch after setting the copyright to just 2019, and this looks good everywhere. The https://github.com/arjantijms/specifications/pull/3 is from a clean fork so it should just merge.

**Comment by dblevins** [comment]
@starksm64 don't forget to merge the apidocs

**Pull request merged**
