### PR TITLE
Jakarta MVC 2.0

### PR DESCRIPTION
**Pull request by ivargrimstad**
## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
- [x] Specification HTML in the form of jakarta-wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
      N/A
- [x] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [x] Updated release record
   - [x] Generated IP Log
   - [x] Email to PMC
   - [x] Start release review by emailing EMO 
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/mvc/jakarta.mvc-api/2.0.0/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://download.eclipse.org/ee4j/mvc/staged/2.0/jakarta-mvc-tck-2.0.0.zip
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/mvc-api/issues/53
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by ivargrimstad** [comment]
# Spec Review Checklist

1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form jakarta-{spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form jakarta-{spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta.{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] (Optional) Second PR for just apidocs

2. _index.md
  - [ ] Link to project release plan of the form https://projects.eclipse.org/projects/ee4j.{spec}/releases/x.y/plan
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip (The folder path is required, the file name pattern is preferred.)
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

10. If a Release Review is required, the specification project team contacts the EMO to initiate the review by sending an email to emo@eclipse.org.
    (A Release Review is not required if the current release is a Service Release based on a previously successful Major or Minor
    release as indicated by a release record on the project's Releases page, e.g., the [Jakarta Servlet releases page](https://projects.eclipse.org/projects/ee4j.servlet/reviews).)
    - [ ] An issue will be created by the EMO to track the release review.
    - [ ] The specification project team requests approval for the release from the PMC by sending an email to ee4j-pmc@eclipse.org.
    - [ ] The specification project team then delivers an IP Log to the IP Team for their review as described in https://www.eclipse.org/projects/handbook/#pmi-commands-iplog.

11. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Review by starksm64 — APPROVED** [review]

**Comment by starksm64** [comment]
Voting thread:
https://www.eclipse.org/lists/jakarta.ee-spec/msg01401.html

**Comment by ivargrimstad** [comment]
Thanks @starksm64 !

**Comment by kwsutter** [comment]
@ivargrimstad I found a couple of items while doing the release review...
- In the Javadoc, the release specified at the top of the page is "Jakarta MVC 2.0.0-SNAPSHOT API".
- In the Javadoc, the link at the bottom of the page for the license gets a 404...
- Question... On the Krazo 2.0 page, there is this statement: "Eclipse Krazo requires at least the Jakarta EE 8 Web-Profile or the Eclipse MicroProfile."  I thought MVC 2.0 was updated for Jakarta EE 9 and the updated namespace.  Does Krazo 2.0 work with either Jakarta EE 8 (javax) or Jakarta EE 9 (jakarta)?  And, since you spelled a specific version of Jakarta EE, do you also need a specific version of MicroProfile?

Not sure if the first two items warrant a re-review?  You'd have to push a new version of the javadoc.  I downloaded the staged version of the javadoc jar file.  The release is correct at the top of this javadoc: "Jakarta MVC 2.0.0 API".  But, the license link still gives me a 404 error...

I'll hold off on my vote until we can have this discussion.  Thanks.

**Comment by ivargrimstad** [comment]
> * In the Javadoc, the release specified at the top of the page is "Jakarta MVC 2.0.0-SNAPSHOT API".

Yes, that is weird. AS you point out, the stated javadoc jar has the correct header. 

> * In the Javadoc, the link at the bottom of the page for the license gets a 404...

I see that now. Seems like the doc-files directory weren't copied to the target folder because of the default value of the <docfilessubdirs> configuration of the javadoc plugin.

> * Question... On the Krazo 2.0 page, there is this statement: "Eclipse Krazo requires at least the Jakarta EE 8 Web-Profile or the Eclipse MicroProfile."  I thought MVC 2.0 was updated for Jakarta EE 9 and the updated namespace.  Does Krazo 2.0 work with either Jakarta EE 8 (javax) or Jakarta EE 9 (jakarta)?  And, since you spelled a specific version of Jakarta EE, do you also need a specific version of MicroProfile?

That statement is a simple copy/paste error. I have updated the gh-pages now, so it states that Jakarta EE 9 is the minimum requirement.

> Not sure if the first two items warrant a re-review? You'd have to push a new version of the javadoc. I downloaded the staged version of the javadoc jar file. The release is correct at the top of this javadoc: "Jakarta MVC 2.0.0 API". But, the license link still gives me a 404 error...

I can either copy the correctly generated javadoc files into this PR and update the staged javadoc artifact OR do a 2.0.1 release of the API artifacts directly after the ballot. I find the first option better.

**Comment by kwsutter** [comment]
> > Not sure if the first two items warrant a re-review? You'd have to push a new version of the javadoc. I downloaded the staged version of the javadoc jar file. The release is correct at the top of this javadoc: "Jakarta MVC 2.0.0 API". But, the license link still gives me a 404 error...
> 
> I can either copy the correctly generated javadoc files into this PR and update the staged javadoc artifact OR do a 2.0.1 release of the API artifacts directly after the ballot. I find the first option better.

I'm okay with not restarting the ballot.  I'll put my comments in the ballot thread and see if there's any pushback.  Otherwise, I think we're okay to move forward.  Thanks!

**Comment by starksm64** [comment]
Representative | Representative for: | Vote
-- | -- | --
Kenji Kazumura | Fujitsu | +1
Dan Bandera, Kevin Sutter | IBM | +1
Ed Bratt, Dmitry Kornilov | Oracle | +1
Andrew Pielage, Matt Gill | Payara | +1
Scott Stark, Mark Little | Red Hat | +1
David Blevins, Jean-Louis Monteiro | Tomitribe | +1
Ivar Grimstad | EE4J PMC | +1
Marcelo Ancelmo, Martijn Verburg | Participant Members | +1
Werner Keil | Committer Members | +1
Scott (Congquan) Wang | Enterprise Members | +1
  | Total | 10

**Comment by starksm64** [comment]
* On ballot completion, the specification committee mentor:
 - [x] adds this final checklist to the main PR.
 - [x] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [ ] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
 - [ ] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [ ] creates an issue in the specification project that includes the following checklist for the specification project team:

**Pull request merged**
