### PR TITLE
Add service release of concurrency TCK to spec page

### PR DESCRIPTION
**Pull request by arjantijms**
https://download.eclipse.org/ee4j/cu/jakartaee10/staged/eftl/concurrency-tck-3.0.2.zip 

needs to be promoted to

https://download.eclipse.org/jakartaee/concurrency/3.0/concurrency-tck-3.0.2.zip

Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by arjantijms** [comment]
cc @ivargrimstad

**Comment by arjantijms** [comment]
sha256sum concurrency-tck-3.0.2.zip

22728d729f620d6a85ae903e7d1184e0a7508a4328491b785f1b4f3d7215ca93  concurrency-tck-3.0.2.zip

**Review by starksm64 — APPROVED** [review]
The preview looks good.

**Comment by arjantijms** [comment]
Note that https://download.eclipse.org/jakartaee/concurrency/3.0/concurrency-tck-3.0.2.zip doesn't resolve yet.

@ivargrimstad was https://download.eclipse.org/ee4j/cu/jakartaee10/staged/eftl/concurrency-tck-3.0.2.zip already promoted to https://download.eclipse.org/jakartaee/concurrency/3.0/concurrency-tck-3.0.2.zip ?

**Comment by starksm64** [comment]
It has been promoted

**Pull request merged**
