### PR TITLE
Jakarta XML WS 3.0

### PR DESCRIPTION
**Pull request by lukasj**
## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of wombat-spec-x.y.pdf
- [x] Specification HTML in the form of wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [ ] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
- [x] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [x] Updated release record
   - [x] Generated IP Log
   - [x] Email to PMC
   - [x] Start release review by emailing EMO
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/xml/ws/jakarta.xml.ws-api/3.0.0/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-xml-ws-tck-3.0.0.zip
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/jax-ws-api/issues/149, https://github.com/eclipse-ee4j/jax-ws-api/issues/150
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

### CODE REVIEW

**Comment by kwsutter** [comment]
# Spec Review Checklist

1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta.{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] (Optional) Second PR for just apidocs

2. _index.md
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request
 
10. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Comment by kwsutter** [comment]
@cesarhernandezgt First the easy question...  The TCK Results will be accessible from the Certification Request.  So, once @lukasj is able to provide that link, then you should have access to the TCK results.

Re: naming questions...  According to our [specification naming guidelines](https://github.com/jakartaee/specification-committee/blob/master/names.adoc), the official short name for this component is xml-ws.  So, the name of the pdf and html should be using xml-ws (these all look good and consistent).  The maven coordinates were defined separately based on the existing javax coordinates, so they may not be exactly consistent with the defined short names, but they are normally very close.  https://wiki.eclipse.org/JakartaEE_Maven_Versioning_Rules

Technically, the directory name for the specifications probably should use this short name, but that's not a requirement.  And, changing it now could have a ripple effect across any external references.  So, let's leave the "xml-web-services" directory as-is.

Hope this helps.  Thanks for the thorough review!

**Comment by lukasj** [comment]
@dblevins almost nothing has been done on the spec part - I was hoping **unchecked** checkbox in the pr description makes that clear. From other issues - wrong acronyms there, wrong xml namespaces, probably missing few paragraphs...

**Comment by dblevins** [comment]
@lukasj Thanks for the clarification.  Didn't intend to offend.  I've been sending PRs to all the spec projects that still need help.

**Comment by lukasj** [comment]
@dblevins no problem at all, I'm leaving this one to be the last to work on myself as it has dependencies which should have been made ready first (activation, soap, jws and xml binding) - none of them entered ballot yet. At this point my plan is to get to this in ~2w, so whatever will be done by then is going to be much appreciated (and save me some time) ;-)

**Comment by lukasj** [comment]
final version of the spec document has been added, javadoc has been update too

**Review by cesarhernandezgt — COMMENTED** [review]
After the latest commits I marked as complete:
1. Spec PR
[x] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
[x] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)

4. Spec PDF
[x]  No DRAFT or SNAPSHOT

I found some references to jax-ws in the TCK documentation `JAXWS3.0-ReleaseNotes.html` and source code like `JAXWSDeliverable.java` `JAXWSPropertyManager.java` `TS_HOME/src/com/sun/ts/tests/jaxws/common/xml/catalog/META-INF/jax-ws-catalog.xml`

**Comment by lukasj** [comment]
> I found some references to jax-ws in the TCK documentation JAXWS3.0-ReleaseNotes.html and source code like JAXWSDeliverable.java JAXWSPropertyManager.java TS_HOME/src/com/sun/ts/tests/jaxws/common/xml/catalog/META-INF/jax-ws-catalog.xml

`jax-ws-catalog.xml` is the name defined by the spec. `JAXWS*.java` are source files to which the acronym "ban" should not apply. Or are you saying we must rename all not only API classes to avoid having the acronym in its name? That would be really huge amount of work...

**Comment by dblevins** [comment]
@lukasj Correct.  We're stuck with any "JAX-WS" acronym uses in API classes themselves.  Jakarta Messaging is full of `JMS` references in the API classes.  In non-source files like xml schemas have all been updated to not reference the `javax` packages, but that has stopped short of forcing renames of specific elements.  For example, the EJB schema still has `<ejb-ref>` and similar refs which will not be renamed.

That said, I think `JAXWS3.0-ReleaseNotes.html` is a file that could be renamed to align with the new brand a bit better.  The old release notes are fine, but 3.0 and onward should probably use the new brand.  Perhaps, `xml-web-services-3.0-releasenotes.html` or some similar name.

**Comment by lukasj** [comment]
@dblevins My question was whether we should rename `JAXWSDeliverable.java` to something like `XMLWSDeliverable.java` or `JAXWSPropertyManager.java` to `XMLWSPropertyManager.java`; thus also files like `jakarta.xml.bind.JAXBContext.java` to `jakarta.xml.bind.XMLBContext.java`? The rest is pretty much clear (and done already)

**Comment by dblevins** [comment]
@lukasj We're stuck with any "JAX-WS" acronym uses in API classes themselves.  We can repackage classes from javax-to-jakarta, but any other changes that affect bytecode cannot be made (i.e. we cannot rename the classes, methods, fields, enums, annotations, etc).

**Comment by keilw** [comment]
I don't think this is much different for other specs especially JMS, @dblevins might know, because he's leading that one. Starting with the package "jms" and at least half a dozen classes or interfaces like `JMSConnectionFactory`. Don't think this can be changed so soon, why would it here?

**Comment by lukasj** [comment]
I believe this is ready now. Java class names remain untouched as I believe that is not needed.

**Comment by dblevins** [comment]
@lukasj This looks great.  Marking as final and will put it up for ballot!  Thank you so much for the great work on this!

I didn't check off item 10 in the checklist, "Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file."  If you've done that, can you supply a link to the PR?  Tomorrow is fine -- not a blocker for the ballot IMO and it's very very late for you.

**Comment by lukasj** [comment]
@dblevins see https://github.com/eclipse-ee4j/jakartaee-api/pull/84

**Review by dblevins — APPROVED** [review]

**Comment by kwsutter** [comment]
@dblevins Thanks for merging the PR, but the "Ballot Completion" checklist is missing.  We need to ensure that all of these steps have been done in support of XML Web Services Specification.  I've verified the first few.  Could you please verify the rest?  Thanks!

* On ballot completion, the specification committee mentor:
 - [x] adds this final checklist to the main PR.
 - [x] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [x] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
 - [x] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [ ] creates an issue in the specification project that includes the following checklist for the specification project team:
 \<include url of Issue here>


 ----
 - [ ] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [ ] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [ ] approve the compatibility request.
 - [ ] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [ ] merge any final release branch as appropriate for the branch management for the project.

**Pull request merged**
