### PR TITLE
Jakarta Authorization 2.1 Plan Review

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

## Plan Review PR template
When creating a specification project plan review, create PRs with the content defined as follows.

Include the following in the PR:

- [X]   A directory in the form wombat/x.y where x.y is the release major.minor version.
- [X]   An index page wombat/x.y/_index.md following template
- [X]   Title should be on the form "Jakarta Wombat X.Y (under development)"
- [X]   Includes a plan for the release. Usually, a couple of statements is enough. Otherwise, a link to a document describing the release.
- [X]   N/A - Includes a detailed description of any backward incompatibility (Mark with N/A and check if none)
- [X]   N/A - Declares optional features if there are any (Mark with N/A and check if none)
- [X]   Includes minimum Java SE version
- [X]   N/A - Describe any updates or required changes including splitting out the TCK (Mark with N/A and check if not planned)
- [X]   Link to updated release record
https://projects.eclipse.org/projects/ee4j.jacc/releases/2.1

### CODE REVIEW

**Comment by kwsutter** [comment]
@arjantijms One basic question...  Why is this a major version update (ie. Authorization 3.0) vs a minor version update (ie. Authorization 2.1)?  I read through your index.md file and the release record and I'm missing the reasoning for a major version update.

**Comment by arjantijms** [comment]
@kwsutter I didn't give this too much thought. The plan is to update the API with generics, adding say `<String>` at the appropriate places. Is that enough for a major version update, or could a minor update do?

**Comment by edbratt** [comment]
If API's are removed (even if they'd been previously deprecated), we'd want to declare a major version update. If the changes only add APIs, a minor update is probably fine. Generally, I'd suggest, qualitatively, if the changes contemplated are going to cause compatibility issues with legacy applications, it should be a major update just to alert users.

**Comment by kwsutter** [comment]
> If API's are removed (even if they'd been previously deprecated), we'd want to declare a major version update. If the changes only add APIs, a minor update is probably fine. Generally, I'd suggest, qualitatively, if the changes contemplated are going to cause compatibility issues with legacy applications, it should be a major update just to alert users.

Agree.  This is why I am challenging all of the major spec version updates...  I just want to make sure that we're giving these major version updates proper thought.  If adding generics is the main item for this plan review, then I would think a 2.x update would be sufficient.

**Comment by kwsutter** [comment]
@arjantijms Have you decided what direction you plan to take with the new version of Authorization?  Based on the input thus far, I would recommend a 2.1 update instead of a 3.0 update.  If we can decide on this, then I think we're ready for ballot.  Thanks!

**Review by kwsutter — COMMENTED** [review]
Just looking for a response about which direction you plan to pursue regarding a 2.1 vs 3.0 release.  Thanks!

**Review by kwsutter — CHANGES_REQUESTED** [review]
Changing this review to "Request Changes" just to show that it's being actively reviewed...

**Comment by arjantijms** [comment]
@kwsutter I'm fine with moving it to 2.1. At this point we may not have super breaking changes in mind.

**Comment by kwsutter** [comment]
> @kwsutter I'm fine with moving it to 2.1. At this point we may not have super breaking changes in mind.

@arjantijms If you wish to move this to a 2.1 Plan Review, then this PR needs updating before we can take it to ballot.  Thanks!

**Comment by arjantijms** [comment]
@kwsutter Good point ;) I think I've updated everything to say 2.1 now ;)

**Comment by kwsutter** [comment]
@arjantijms Looking good.  I did notice that the 2.1 Release Record (https://projects.eclipse.org/projects/ee4j.jacc/releases/2.1) still has a reference to a "3.0 release review".  Can you clean that up?  I'll start the ballot later today.  Thanks!

**Comment by arjantijms** [comment]
> @arjantijms Looking good. I did notice that the 2.1 Release Record (https://projects.eclipse.org/projects/ee4j.jacc/releases/2.1) still has a reference to a "3.0 release review". Can you clean that up? I'll start the ballot later today. Thanks!

Ah, thanks for spotting that. I changed it right away. It says 2.1 now.

**Review by kwsutter — APPROVED** [review]
Looks good now.  Thanks, @arjantijms!

**Comment by kwsutter** [comment]
> > @arjantijms Looking good. I did notice that the 2.1 Release Record (https://projects.eclipse.org/projects/ee4j.jacc/releases/2.1) still has a reference to a "3.0 release review". Can you clean that up? I'll start the ballot later today. Thanks!
> 
> Ah, thanks for spotting that. I changed it right away. It says 2.1 now.

I also just noticed that the first comment (Description) in this PR still referenced the 3.0 release record.  I updated that for you so that we didn't have to put off the ballot for another day...  :-)  Hope that was okay.  Thanks!

**Comment by arjantijms** [comment]
Perfect, thanks!

**Pull request merged**
