### PR TITLE
Jakarta Authentication 2.0

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [X] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [X] Specification PDF in the form of wombat-spec-x.y.pdf
- [X] Specification HTML in the form of wombat-spec-x.y.html
- [X] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [ ] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
- [X] For a Release Review, a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
- [X] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/authentication/jakarta.authentication-api/2.0.0/
- [X] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-authentication-tck-2.0.0.zip
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/authentication/issues/105
- [X] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

### CODE REVIEW

**Comment by kwsutter** [comment]
@dblevins and @cesarhernandezgt  are the assigned Spec Committee mentors for this PR.  Please work directly with David and Cesar to complete the pre-review for this PR in preparation for the ballot.  Thanks!  Any questions, you can contact me as well.

**Comment by arjantijms** [comment]
@kwsutter @cesarhernandezgt We should be very close to the final status of this, but I haven't received any feedback yet.

**Comment by kwsutter** [comment]
I will start by posting the Checklist so that @cesarhernandezgt and @jeanouii have something to work with...  (These two are your mentors for this PR.). And, also as a reference for you, @arjantijms.  Thanks.

# Spec Review Checklist

1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form jakarta-{spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form jakarta-{spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta.{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] (Optional) Second PR for just apidocs

2. _index.md
  - [ ] Link to project release plan of the form https://projects.eclipse.org/projects/ee4j.{spec}/releases/x.y/plan
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip (The folder path is required, the file name pattern is preferred.)
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request
 
10. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Review by jeanouii — CHANGES_REQUESTED** [review]
@arjantijms As discussed in the Jakarta Security PR, the file names have to be updated so they have jakarta- prefix. 

I went to create a PR https://github.com/eclipse-ee4j/authentication/pull/107
You just need to review and if you are happy, you can run `mvn clean install -Dstatus=Final -Dspec.version=2.0 -Pstaging` and then update the files here.

**Review by jeanouii — CHANGES_REQUESTED** [review]
Sorry duplicate message

**Review by jeanouii — CHANGES_REQUESTED** [review]
Index page {spec}/x.y/_index.md following template
- Does not follow the template (release review table).

API doc 
- still snapshot

PDF/HTML
- version number is not x.y in the first page
- still DRAFT
- copyright year should be updated (currently 2019)

Certification requestion checksum does seem to match
shasum -a 256 ~/Downloads/jakarta-authentication-tck-2.0.0.zip
26dfef951f1c92fccdf78a03bf30cbdec3aacb372f8e93ec158cfc4d98b3d6d8  /Users/jlmonteiro/Downloads/jakarta-authentication-tck-2.0.0.zip

**Comment by arjantijms** [comment]
@jeanouii 

> PDF/HTML
> version number is not x.y in the first page
> still DRAFT
> copyright year should be updated (currently 2019)

If I look at the deploy preview, and double check the repo, none of that seems to be the case:

https://deploy-preview-239--jakartaee-specifications.netlify.app/specifications/authentication/2.0/

Screenshot 2020-09-27 at 16 00 01
Screenshot 2020-09-27 at 15 59 38

**Comment by arjantijms** [comment]
@jeanouii

> API doc
> still snapshot

I'm not sure where you saw the snapshot. When I open the javadocs I see this:

Screenshot 2020-09-27 at 16 03 16

**Comment by arjantijms** [comment]
@jeanouii 
> Index page {spec}/x.y/_index.md following template
> Does not follow the template (release review table).

Release review table updated in https://github.com/jakartaee/specifications/pull/239/commits/4fdc861501ae5cc63e7065504516cc592a7922e8

**Comment by arjantijms** [comment]
@jeanouii 
> Certification requestion checksum does seem to match

They always change a couple of times, but updated now again:

* https://github.com/eclipse-ee4j/glassfish/pull/23213
* https://github.com/eclipse-ee4j/authentication/issues/105

**Comment by jeanouii** [comment]
Hey @arjantijms 
Thanks. I'll check it out again and keep going with the checks.

Sorry if some feedback was not accurate anymore. I was probably not up to date.

**Comment by arjantijms** [comment]
@jeanouii no worries, thanks for taking a look again! :)

**Comment by kwsutter** [comment]
@arjantijms Will the TCK be moved to the "promoted" directory in preparation for the ballot?

**Comment by arjantijms** [comment]
> Will the TCK be moved to the "promoted" directory in preparation for the ballot?

Yes, when @jeanouii has no further feedback and okays the materials, I'll ask for it to be moved (or look at moving it myself if possible).

**Comment by kwsutter** [comment]
> > Will the TCK be moved to the "promoted" directory in preparation for the ballot?
> 
> Yes, when @jeanouii has no further feedback and okays the materials, I'll ask for it to be moved (or look at moving it myself if possible).

Sure, makes sense.  But, I think @jeanouii needs the SHA values to kind of match up...  Right now, it looks like we have three different SHA values depending on which TCK is looked at and which document is referenced...  thanks!

**Comment by arjantijms** [comment]
> Sure, makes sense. But, I think @jeanouii needs the SHA values to kind of match up... Right now, it looks like we have three different SHA values depending on which TCK is looked at and which document is referenced... thanks!

Yes, maybe we could do with some simplifications here in the process at one point, as the updating of SHA values at multiple places is a recurring problem. I don't know how to address it though.

So for now as soon @jeanouii approves the content of the TCK (which mostly comes down to checking the user guides etc I guess), I'll do this move. Then @jeanouii has to do one more check for the SHA values, and then we can hopefully start the ballot ;)

**Comment by jeanouii** [comment]
Yeah, was checking the TCK. Here is some points to discuss. Dunno how much it's important

- javax mentions here and there (JASPICSpecAssertions.html - authorized javax but also javax.jmx.Message which seems to be a typo. Should be jakarta.jms.Message isn't it?)

- release notes has
API tests for all of the public APIs under the javax.JASPIC package --> jakarta.xxxx?
https://jakarta-ee/specifications/authentication/2.0/ --> broken link

The map files in bin/ are still referencing javax packages such as servlet. There is also a JavaEE branding to fix.
Finally, small detail, /jaspic-tck/bin/sig-test.map needs to be /authentication-tck/....

I am happy to help also fixing typos in there if you need and remaining branding issues

**Comment by jeanouii** [comment]
@arjantijms I created a wider PR to hopefully help.
If it does not, I can send a smaller PR so it's easier to review for you and just approve

**Comment by jeanouii** [comment]
Created a small PR so it's easier to review and hopefully merge
https://github.com/eclipse-ee4j/jakartaee-tck/pull/540

**Comment by arjantijms** [comment]
@jeanouii 
> eclipse-ee4j/jakartaee-tck#540

Looks good to me, as mentioned in the issue, just needs the copyright to be updated.

**Comment by arjantijms** [comment]
@jeanouii 
The copyright was updated and I merged the PR. Now we need, just to be sure, restage  the TCK and then update SHAs. See https://github.com/eclipse-ee4j/jakartaee-tck/issues/541

**Comment by jeanouii** [comment]
That'd be awesome. If you can do that last thing for me, I'll start the ballot tomorrow

**Comment by arjantijms** [comment]
@jeanouii I re-staged and re-executed the TCK:

```
BUILD SUCCESSFUL
Total time: 5 minutes 54 seconds
SHA256_GF=f69a582e2ee15f49afb48adb2393d42351256ea070a60513e1ae17afe973e9c3
SHA256_API=396bd2869dd7d5a79ce495bb9412cc4e4d0422ea8e8d7422419d8ef38b891f8a
SHA256_TCK=4fff0e3984cec6937db1e5b2e1894534f695fe72ad3aeb076a8423fa5845ad07
Product_download=https://download.eclipse.org/ee4j/glassfish/weekly/glassfish-6.0.0-SNAPSHOT-2020-10-04.zip
API_download=https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/authentication/jakarta.authentication-api/2.0.0/jakarta.authentication-api-2.0.0.jar
TCK_download=https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-authentication-tck-2.0.0.zip
OS4=3.12.0 NAME="Alpine Linux" ID=alpine VERSION_ID=3.12.0 PRETTY_NAME="Alpine Linux v3.12" HOME_URL="https://alpinelinux.org/" BUG_REPORT_URL="https://bugs.alpinelinux.org/"
JDK_VERSION=java version "1.8.0_202" Java(TM) SE Runtime Environment (build 1.8.0_202-b08) Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```

Let me know if the TCK is now fine so I can (ask to) promote it to the promoted folder.

**Comment by arjantijms** [comment]
SHA update PR for GF website: https://github.com/eclipse-ee4j/glassfish/pull/23227

Compatibility request issue updated: https://github.com/eclipse-ee4j/authentication/issues/105

**Comment by arjantijms** [comment]
TCK promotion tracked here: https://github.com/eclipse-ee4j/jakartaee-tck/issues/541

**Comment by jeanouii** [comment]
I'll do that right now

**Review by jeanouii — APPROVED** [review]
Look all good to me.
Thanks so much Arjan.

Can you promote the TCK so I can start the ballot

**Comment by arjantijms** [comment]
Thank you too! I'll look at the promotion now.

**Comment by arjantijms** [comment]
@jeanouii The TCK is now promoted, see: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-authentication-tck-2.0.0.zip

**Review by kwsutter — COMMENTED** [review]
The Authentication 2.0 Release Record needs updating.  It still says a release date of May 06:  https://projects.eclipse.org/projects/ee4j.jaspic/releases/2.0.0 Also, you should get a review of this release record started with the PMC and EMO.  Thanks.

Since we're changing the maven coordinates midstream, is there a way to point the old coordinates (https://search.maven.org/artifact/jakarta.security.auth.message/jakarta.security.auth.message-api) to the new ones (https://search.maven.org/artifact/jakarta.authentication/jakarta.authentication-api/2.0.0/jar)?  If developers were using the previous 2.0.0-RC1 API, they may have trouble finding the final 2.0 API.

Finally, the Compatible Implementation links are not consistent.  In this PR, you are referencing a dated snapshot of Glassfish.  But, the CR and TCK Results are referencing an M2 release (tag) of Glassfish.  Not sure what the right answer is for this case, but the inconsistency jumped out at me.

None of these are stop-shop issues.  I'll still vote on the ballot.  Thanks.

**Comment by arjantijms** [comment]
IP log / CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22727

**Comment by arjantijms** [comment]
Updated release record, set to 22 October: https://projects.eclipse.org/projects/ee4j.authentication/releases/2.0.0

Mail sent to emo regarding release review:

```
MIME-Version: 1.0
Date: Wed, 14 Oct 2020 22:44:35 +0200
Subject: Please schedule 2.0.0 Release Review
To: Wayne Beaton <emo@eclipse.org>

Link:
https://projects.eclipse.org/projects/ee4j.jaspic/reviews/2.0.0-release-review
```

**Comment by arjantijms** [comment]
PR and CR updated. PR to update TCK results: https://github.com/eclipse-ee4j/glassfish/pull/23244

**Comment by arjantijms** [comment]
Release bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=567946

**Comment by arjantijms** [comment]
Release review successful: https://bugs.eclipse.org/bugs/show_bug.cgi?id=567946

**Comment by kwsutter** [comment]
@jeanouii Can you please ensure that the items in this final checklist are fully addressed for this PR?  Thanks!

* On ballot completion, the specification committee mentor:
 - [ ] adds this final checklist to the main PR.
 - [ ] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [ ] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
 - [ ] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [ ] creates an issue in the specification project that includes the following checklist for the specification project team:
 \<include url of Issue here>


 ----
 - [ ] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [ ] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [ ] approve the compatibility request.
 - [ ] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [ ] merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
Since there's no issue, responding to the checklist here:

Promoted to maven central: https://repo1.maven.org/maven2/jakarta/authentication/jakarta.authentication-api/2.0.0/
Links on https://jakarta.ee/specifications/authorization/2.0/ correct
CCR approved: https://github.com/eclipse-ee4j/authentication/issues/105
Mail send
Release branch merged: https://github.com/eclipse-ee4j/authentication/pull/113

**Comment by jeanouii** [comment]
> Links on https://jakarta.ee/specifications/authorization/2.0/ correct

@arjantijms this looks like the wrong link. It should point to Authentication and not Authorization. I double checked all the links and TCK signature and it looks good.

**Comment by arjantijms** [comment]
@jeanouii You're absolute right, thanks for spotting that!

**Pull request merged**
