### PR TITLE
adding CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by chrisguindon**
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

### CODE REVIEW

**Comment by chrisguindon** [comment]
I believe that our code of conduct should be included in all git repository to signal that project is welcoming and inclusive and that we have procedure for handling abuse.

I don't believe it's a requirements at the moment but I think it's the right thing to do.

**Comment by bshannon** [comment]
Having a code of conduct for all our projects is a good thing.

Having **the same** code of conduct for all our projects is a very good thing.

Storing a copy of the code of conduct in each repository, and keeping it up to date
in each repository if/when the code of conduct changes does not seem like the best approach.

It seems like GitHub has some special support for CODE_OF_CONDUCT.md files,
but I can't completely understand what all it does with those files.

There is a way to [create a default version of such files at the GitHub organization
level](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file-for-your-organization), and that should probably be done for the eclipse-ee4j and jakartaee GitHub
organizations, containing the content proposed here, rather than storing a copy of the
CODE_OF_CONDUCT.md file in the specifications repository.

And of course this assume that the EE4J PMC has approved this specific code of conduct.

**Comment by chrisguindon** [comment]
> It seems like GitHub has some special support for CODE_OF_CONDUCT.md files,
> but I can't completely understand what all it does with those files.
> 
> There is a way to create a default version of such files at the GitHub organization
> level, and that should probably be done for the eclipse-ee4j and jakartaee GitHub
> organizations, containing the content proposed here, rather than storing a copy of the
> CODE_OF_CONDUCT.md file in the specifications repository.

We have:
https://github.com/jakartaee/.github

Which is a fork of:
https://github.com/eclipse/.github

The [code of conduct](https://github.com/eclipse/.github/blob/master/CODE_OF_CONDUCT.md) in https://github.com/eclipse/.github was approved by the Eclipse Foundation Board of Directors at ECE 2019.

I assume we could do the same for eclipse-ee4j.

Files in the .github repository should be included thought developers workflows such as opening an issue but I prefer to include them in the repository since these files won’t appear in the file browser or Git history. 

I created a PR for this repository because I went through the exercise of standardizing our code of conduct for repos under the https://github.com/jakartaee organization and thought it would be a good idea to the same for this one.

- https://github.com/jakartaee/jakartablogs.ee/commit/567997c515cb2556f7be0f6fdf8ebcc5c05f950e

- https://github.com/jakartaee/jakarta.ee/commit/ec6b3cb81f54d11f3af7b23e3ce94f5b09d00b89

- https://github.com/jakartaee/jekyll-theme-jakarta-ee/commit/f4d47763bbf425b69b47eb98aed29329041ae3c8

- https://github.com/jakartaee/jakartaone.org/commit/04c745a2db2e0cbe96ab94de16777468daa987f5

**Comment by bshannon** [comment]
> The [code of conduct](https://github.com/eclipse/.github/blob/master/CODE_OF_CONDUCT.md) in https://github.com/eclipse/.github was approved by the Eclipse Foundation Board of Directors at ECE 2019.

Did the BoD require the code of conduct to be exactly the same for all Eclipse projects?

Or did they approve this as merely one acceptable code of conduct?

> Files in the .github repository should be included thought developers workflows such as opening an issue but I prefer to include them in the repository since these files won’t appear in the file browser or Git history.

I understand, but I don't think we want each project to have its own different code of conduct.
I think at least all projects under the same PMC should use the same code of conduct, so it
seems wrong to duplicate the file into every repo.

> I created a PR for this repository because I went through the exercise of standardizing our code of conduct for repos under the https://github.com/jakartaee organization and thought it would be a good idea to the same for this one.

And you've tripped over the larger issue of whether each repo should be allowed to have
a different code of conduct.  I'd love to get some feedback from others here...

**Comment by chrisguindon** [comment]
> Did the BoD require the code of conduct to be exactly the same for all Eclipse projects?
> Or did they approve this as merely one acceptable code of conduct?

The previous code of conduct was written in 2015. We recommended an update to our Code of Conduct via [Bug 537202](https://bugs.eclipse.org/bugs/show_bug.cgi?id=537202) - Update Eclipse Foundation Community Code of Conduct and create a markdown template https://bugs.eclipse.org/bugs/show_bug.cgi?id=537202

In this bug, I also recommended that we require the code of conduct for all our project but as far as I know, this was not approved or discussed: https://bugs.eclipse.org/bugs/show_bug.cgi?id=537202#c1

> I understand, but I don't think we want each project to have its own different code of conduct.
> I think at least all projects under the same PMC should use the same code of conduct, so it
> seems wrong to duplicate the file into every repo.

In my opinion, a newcomer that lands on one of our git repository might not be aware of our  Community Code of Conduct and because of that, I think it should be included in all of our repository.

> And you've tripped over the larger issue of whether each repo should be allowed to have
> a different code of conduct. I'd love to get some feedback from others here...

This Code of Conduct applies within all project spaces, and it also applies when an individual is representing the project or its community in public spaces.”

**Comment by kwsutter** [comment]
Thanks for the nudge, @bshannon.  I can understand the desire to have a Code of Conduct immediately available and viewable by anyone visiting any one of our repos.  But, the maintenance of such files *could* become a nightmare.  Granted, these don't seem to get modified too often.  But, we would want them to stay consistent among the various Jakarta EE and EE4J projects.  And, we certainly wouldn't want one project to go rogue on their Code of Conduct that would be inconsistent with the rest of the Jakarta EE or EE4J projects.

I think housing the official Code of Conduct at the top level project is sufficient.  We could have each individual project point to this common Code of Conduct either in their README or maybe a separate CODE_OF_CONDUCT that only references the master copy.  But, let's not repeat the same full text for the Code of Conduct in every project.  Thanks.

**Comment by bshannon** [comment]
> I think housing the official Code of Conduct at the top level project is sufficient. We could have each individual project point to this common Code of Conduct either in their README or maybe a separate CODE_OF_CONDUCT that only references the master copy. But, let's not repeat the same full text for the Code of Conduct in every project. Thanks.

There's two ways to implement that:

1. Put the CODE_OF_CONDUCT.md file in the .github directory of the GitHub *organization* repository (i.e., "jakartaee" and "eclipse-ee4j").  GitHub then displays that code of conduct for all projects within the same organization (unless overridden in the project's repository).
2. Put the CODE_OF_CONDUCT.md file in the .github directory of the (e.g.) eclipse-ee4j/ee4j repository (which represents the Eclipse top level project "ee4j").

In either case, per-project README.md files would link to the common CODE_OF_CONDUCT.md file.  (Alternatively every project would have a "stub" CODE_OF_CONDUCT.md file whose content was simply a link to the common CODE_OF_CONDUCT.md file in the top level project repository.)

@kwsutter which of #1 and #2 above did you prefer?  Or something else?

**Comment by chrisguindon** [comment]
As a follow-up, we are currently have a .github repository under the jakartaee organization:
https://github.com/jakartaee/.github

I created an issue for @eclipsewebmaster on Eclipse Bugzilla to make sure we create a .github repository for all our organizations on github:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=553285

**Comment by kwsutter** [comment]
@chrisguindon, I'm not familiar with the .github repository mechanism.  So, by you creating the CoC.md at that top-level repo, does that file automatically get created in newly created repositories?  Or, does it just provide a nice holding spot so that each repository can easily reference it?

@bshannon, since Chris is already initiating option #1, I guess I like that one best.  :-)  That was going to be my choice anyway.

Providing a "stub" CoC.md file in each repo seems like the easiest approach.  This also seems like it could more easily be automated.  Updating each README may require some knowledge of the current format of the README --ie. more work.

**Comment by bshannon** [comment]
> @chrisguindon, I'm not familiar with the .github repository mechanism. So, by you creating the CoC.md at that top-level repo, does that file automatically get created in newly created repositories? Or, does it just provide a nice holding spot so that each repository can easily reference it?

Neither, as I understand it.

Whenever GitHub would display a code of conduct (and I don't know what causes it to do that), it effectively does a path search, first looking in the local repo and then in the organization repo.

> @bshannon, since Chris is already initiating option #1, I guess I like that one best. :-) That was going to be my choice anyway.

Me too.  :-)

> Providing a "stub" CoC.md file in each repo seems like the easiest approach. This also seems like it could more easily be automated. Updating each README may require some knowledge of the current format of the README --ie. more work.

I don't believe there needs to be a "stub" CoC.md file anywhere.  Just put the default/master one in the organization repo, and then in the rare case where you need to override it because some project just *has* to be different, put the updated version in the repo.

Maybe there's some key sequence or button or something that I've missed that causes it to display the code of code for the current organization?

**Comment by ivargrimstad** [comment]
Close this one?

**Comment by ivargrimstad** [comment]
Has been added to the organisation, so I'm closing this one

**Pull request closed without merging**
