### PR TITLE
Jakarta RESTful Web Services 4.0 Plan Review

### PR DESCRIPTION
**Pull request by spericas**
Signed-off-by: Santiago Pericas-Geertsen santiago.pericasgeertsen@oracle.com

## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

- [x] A directory in the form wombat/x.y where x.y is the release major.minor version.
- [x] An index page wombat/x.y/_index.md following template
- [x] Title should be on the form "Jakarta Wombat X.Y (under development)"
- [x] Includes a plan for the release. Usually, a couple of statements is enough. Otherwise, a link to a document describing the release.
- [x] N/A - Includes a detailed description of any backward incompatibility (Mark with N/A and check if none)
- [x] N/A - Declares optional features if there are any (Mark with N/A and check if none)
- [x] Includes minimum Java SE version
- [x] N/A - Describe any updates or required changes including splitting out the TCK (Mark with N/A and check if not planned)
- [x] Link to updated release record 
https://projects.eclipse.org/projects/ee4j.jaxrs/releases/4.0.0

### CODE REVIEW

**Comment by ivargrimstad** [comment]
@spericas Are you planning a 3.1 before 4.0? If that is the case, you should file a separate plan review for 3.1. 
If the intention is to merge the planned 3.1 into 4.0, then just ignore my comment.

**Comment by spericas** [comment]
> @spericas Are you planning a 3.1 before 4.0? If that is the case, you should file a separate plan review for 3.1.
> If the intention is to merge the planned 3.1 into 4.0, then just ignore my comment.

Yes, we plan to do 3.1 before 4.0 as a standalone release. There will be a separate plan review for it.

**Comment by ivargrimstad** [comment]
> > @spericas Are you planning a 3.1 before 4.0? If that is the case, you should file a separate plan review for 3.1.
> > If the intention is to merge the planned 3.1 into 4.0, then just ignore my comment.
> 
> Yes, we plan to do 3.1 before 4.0 as a standalone release. There will be a separate plan review for it.

Excellent! When do you think you could prepare a PR for that? I think it would make more sense to run that plan review by the spec committee first, then this one. We could stagger the reviews, so it won't need to be a week between them even.

**Comment by spericas** [comment]
> > > @spericas Are you planning a 3.1 before 4.0? If that is the case, you should file a separate plan review for 3.1.
> > > If the intention is to merge the planned 3.1 into 4.0, then just ignore my comment.
> > 
> > 
> > Yes, we plan to do 3.1 before 4.0 as a standalone release. There will be a separate plan review for it.
> 
> Excellent! When do you think you could prepare a PR for that? I think it would make more sense to run that plan review by the spec committee first, then this one. We could stagger the reviews, so it won't need to be a week between them even.

Sure, we pushed the 4.0 review last week as that was required for EE 10.

**Comment by ivargrimstad** [comment]
> > > > @spericas Are you planning a 3.1 before 4.0? If that is the case, you should file a separate plan review for 3.1.
> > > > If the intention is to merge the planned 3.1 into 4.0, then just ignore my comment.
> > > 
> > > 
> > > Yes, we plan to do 3.1 before 4.0 as a standalone release. There will be a separate plan review for it.
> > 
> > 
> > Excellent! When do you think you could prepare a PR for that? I think it would make more sense to run that plan review by the spec committee first, then this one. We could stagger the reviews, so it won't need to be a week between them even.
> 
> Sure, we pushed the 4.0 review last week as that was required for EE 10.

That is greatly appreciated!
But it feels weird to run a plan review for 4.0 which is based on a 3.1 that hasn't been planned yet (from the spec committee point of view).

**Comment by keilw** [comment]
@spericas Any plans in 4.0 to coordinate with Jakarta Security (https://github.com/jakartaee/specifications/pull/362) and @arjantijms especially on areas like the redundant `SecurityContext` in both specs?

**Comment by spericas** [comment]
> > > > > @spericas Are you planning a 3.1 before 4.0? If that is the case, you should file a separate plan review for 3.1.
> > > > > If the intention is to merge the planned 3.1 into 4.0, then just ignore my comment.
> > > > 
> > > > 
> > > > Yes, we plan to do 3.1 before 4.0 as a standalone release. There will be a separate plan review for it.
> > > 
> > > 
> > > Excellent! When do you think you could prepare a PR for that? I think it would make more sense to run that plan review by the spec committee first, then this one. We could stagger the reviews, so it won't need to be a week between them even.
> > 
> > 
> > Sure, we pushed the 4.0 review last week as that was required for EE 10.
> 
> That is greatly appreciated!
> But it feels weird to run a plan review for 4.0 which is based on a 3.1 that hasn't been planned yet (from the spec committee point of view).

 Understood. The original plan was to get 3.1 into EE 9.1, but that would have required the acceptance of new features. I'll try to get the 3.1 plan this week.

**Comment by spericas** [comment]
> @spericas Any plans in 4.0 to coordinate with Jakarta Security (#362) and @arjantijms especially on areas like the redundant `SecurityContext` in both specs?

 Good question. Seems like something that we should include in the plan. Any thoughts @arjantijms?

**Review by ivargrimstad — APPROVED** [review]

**Comment by starksm64** [comment]
I have created an issue in jaxrs-api for alignment with a core profile effort:
https://github.com/eclipse-ee4j/jaxrs-api/issues/969

This could certainly entail another 'lite' version of JAXRS, but this is something we would want to see addressed with the first post EE9 backwards incompatible version of a JAXRS spec.

**Comment by jeanouii** [comment]
> stion. Seems like something that we sh

A

**Pull request merged**
