### PR TITLE
XML Binding 3.0.1 (SR)

### PR DESCRIPTION
**Pull request by lukasj**
## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
  N/A
- [ ] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
- [ ] Specification HTML in the form of jakarta-wombat-spec-x.y.html
- [ ] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
  N/A
- [ ] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
  N/A
- [ ] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [ ] Updated release record
   - [ ] Generated IP Log
   - [ ] Email to PMC
   - [ ] Start release review by emailing EMO 
  N/A
- [x] For a [Service Release Review](https://jakarta.ee/committees/specification/operations/#creating_a_final_service_release_specification)
   - [x] Updated release record
   https://projects.eclipse.org/projects/ee4j.jaxb/releases/3.0.1
   - [x] Add Change Log
   - [x] Start release review by emailing Specification Committee
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/xml/bind/jakarta.xml.bind-api/3.0.1/
- [ ] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
  N/A
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/jaxb-api/issues/180
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by lukasj** [comment]
@kwsutter here I'm updating also the spec document (to fix broken links there). What is the right version/status to use? I used version `3.0`, status `rev1` for now. What changed in the spec is there in the changelog section, I think Apendix I.

**Comment by kwsutter** [comment]
> @kwsutter here I'm updating also the spec document (to fix broken links there). What is the right version/status to use? I used version 3.0, status rev1 for now. What changed in the spec is there in the changelog section, I think in Appendix I.

@lukasj Per the discussion on the template PR #345, let's hold off on the update to the Specification document itself at this point.  Let's just focus on the API (Javadoc) and TCK for this 3.0.1 service release PR.  Once we figure out the proper process for updating the Spec document, then we can just come back and update the information.  I'd like to make progress on the rest of the Service Release instead of holding up everything until we get a direction from the Spec Committee.  Sound okay?

**Comment by lukasj** [comment]
@kwsutter no problem, I moved spec doc related changes to its own PR (see #346)

**Review by kazumura — APPROVED** [review]
LGTM. Thanks @lukasj

**Pull request merged**
