### PR TITLE
EL 4.0.0 part 2

### PR DESCRIPTION
**Pull request by markt-asf**
Signed-off-by: Mark Thomas <markt@apache.org>

- [x] Specification JavaDoc in the wombat/x.y/apidocs directory.

### CODE REVIEW

**Comment by markt-asf** [comment]
This is draft pending the availability of the proposed EL 4.0.0 TCK.
I am not aware of any remaining issues blocking the release of the EL 4.0.0 TCK. At the time of writing this comment, Tomcat 10.0.0-M7 passes the EL 4.0.0 TCK built from the repo with both Java 8 and Java 11.

**Comment by kwsutter** [comment]
Thanks, @markt-asf! FYI, we're supposed to be assigning Spec Committee mentors to each of these PRs as an aid to get through the process. Unfortunately, we've had a little blip with our own process and the mentors for EL are not official Committers yet for this repo... ;-) So, I will take the initial look and provide comments.

**Comment by kwsutter** [comment]
The footer on the javadoc should contain a reference to the EFSL (spec license), which should be in your doc-files directory.  Something must have changed since the 3.0 release since this reference was part of the 3.0 EL javadoc.

Also, the title on the javadoc page says this, "Provides the API for Jakarta Expression Language 3.0".  It should be version 4.0.

**Comment by markt-asf** [comment]
Footer and version references should be fixed now.

**Comment by kwsutter** [comment]
This looks good from my perspective.  @MattGill98, if you agree, please mark your approval.  Thanks.

**Review by Pandrex247 — APPROVED** [review]

**Comment by hendrikebbers** [comment]
Mostly all classes in the JavaDoc provide the @since information. An example can be found here: https://deploy-preview-226--jakartaee-specifications.netlify.app/specifications/expression-language/4.0/apidocs/jakarta/el/mapelresolver

The „MapELResolver“ class defines that it is part of the API since „Jakarta Server Pages 2.1“. If I get it right there was never a 2.1 version of Jakarta Server Pages. The first Jakarta Server Pages release was 2.3 but the „MapELResolver“ class was already part of JSP before it has been moved to Jakarta. From my point of view it should be defined as „JSP 2.1 / Jakarta Expression Language 4.0“ since the class was introduced in JSP 2.1 but moved to a new package with Jakarta Expression Language 4.0.

**Comment by hendrikebbers** [comment]
@arjantijms @dblevins can you give me some feedback on my concerns about the `since` metadata? See my previous comment.

**Comment by arjantijms** [comment]
@hendrikebbers I think is something more common throughout the various APIs. I think we'd best change this for the next release and/or a maintenance release of Expression Language.

**Comment by MattGill98** [comment]
On ballot completion, the specification committee mentor:
 - [ ] adds this final checklist to the main PR.
 - [ ] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [ ] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
 - [ ] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [ ] creates an issue in the specification project that includes the following checklist for the specification project team:
 \<include url of Issue here>


 ----
 - [ ] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [ ] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [ ] approve the compatibility request.
 - [ ] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [ ] merge any final release branch as appropriate for the branch management for the project.

**Pull request merged**
