### PR TITLE
Enshrine ballot results for XML Web Services 4.0

### PR DESCRIPTION
**Pull request by edbratt**
Ballot results for successful ballot

### CODE REVIEW

**Comment by edbratt** [comment]
Final check looks good to me. I'll leave this for tomorrow in case anyone else wants to take a look and finds something.
https://deploy-preview-478--jakartaee-specifications.netlify.app/specifications/xml-web-services/4.0/

**Review by lukasj — APPROVED** [review]
LGTM

**Comment by lukasj** [comment]
looks like I've somehow managed to change the final count of votes in the plan summary from 9 to 10 - would you mind to fix it as part of this PR?

**Comment by lukasj** [comment]
thank you, Ed

**Pull request merged**
