### PR TITLE
Jakarta Faces 4.0 Plan Review

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

## Plan Review PR template
When creating a specification project plan review, create PRs with the content defined as follows.

Include the following in the PR:

- [X]   A directory in the form wombat/x.y where x.y is the release major.minor version.
- [X]   An index page wombat/x.y/_index.md following template
- [X]   Title should be on the form "Jakarta Wombat X.Y (under development)"
- [X]   Includes a plan for the release. Usually, a couple of statements is enough. Otherwise, a link to a document describing the release.
- [X]   N/A - Includes a detailed description of any backward incompatibility (Mark with N/A and check if none)
- [X]   N/A - Declares optional features if there are any (Mark with N/A and check if none)
- [X]   Includes minimum Java SE version
- [X]   N/A - Describe any updates or required changes including splitting out the TCK (Mark with N/A and check if not planned)
- [X]   Link to updated release record
https://projects.eclipse.org/projects/ee4j.faces/releases/4.0

### CODE REVIEW

**Review by kazumura — APPROVED** [review]
LGTM. Thanks.

**Comment by kwsutter** [comment]
@arjantijms Looking at the release record, it looks like you are proposing some removal of deprecated APIs.  This is consistent with requiring a major version update.  Thanks for providing that detail.

**Comment by kwsutter** [comment]
One more request...  What about separating the API from the Impl?  Could that be added to the list of requirements for 4.0?

**Comment by arjantijms** [comment]
> One more request... What about separating the API from the Impl? Could that be added to the list of requirements for 4.0?

I'd love to do that, but I'm not sure if we have resources for that. It's already a big list, though personally I'd really like to work on it. Too bad perhaps that there's no direct funding of Faces work like in the days that Oracle had paid employees working on it.

**Pull request merged**
