### PR TITLE
Jakarta Batch 2.1 Release Review

### PR DESCRIPTION
**Pull request by scottkurz**
Signed-off-by: Scott Kurz <skurz@us.ibm.com>

## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
- [x] Specification HTML in the form of jakarta-wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] (N/A) - For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
- [x] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [x] Updated release record
   - [X] Generated IP Log - https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23955
   - [x] Email to PMC
   - [x] Start release review by emailing EMO 
- [X] The URL of the OSSRH staging repository for the api, javadoc:
  https://jakarta.oss.sonatype.org/content/repositories/jakartabatch-1026
- [X] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
  https://download.eclipse.org/jakartabatch/tck/eftl/jakarta.batch.official.tck-2.1.0.zip
- [X] The URL of the compatibility certification request issue:
  https://github.com/eclipse-ee4j/batch-api/issues/197
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by starksm64** [comment]
# Spec Review Checklist

1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form jakarta-{spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form jakarta-{spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta.{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] (Optional) Second PR for just apidocs

2. _index.md
  - [ ] Link to project release plan of the form https://projects.eclipse.org/projects/ee4j.{spec}/releases/x.y/plan
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip (The folder path is required, the file name pattern is preferred.)
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

10. If a Release Review is required, the specification project team contacts the EMO to initiate the review by sending an email to emo@eclipse.org.
    (A Release Review is not required if the current release is a Service Release based on a previously successful Major or Minor
    release as indicated by a release record on the project's Releases page, e.g., the [Jakarta Servlet releases page](https://projects.eclipse.org/projects/ee4j.servlet/reviews).)
    - [ ] An issue will be created by the EMO to track the release review.
    - [ ] The specification project team requests approval for the release from the PMC by sending an email to ee4j-pmc@eclipse.org.
    - [ ] The specification project team then delivers an IP Log to the IP Team for their review as described in https://www.eclipse.org/projects/handbook/#pmi-commands-iplog.

11. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Comment by edbratt** [comment]
The Plan review results table is not formatted correctly. Please revise that part of this PR (it is broken in the merged copy as well)

**Comment by scottkurz** [comment]
> @scottkurz It seems there is some inconsistency between releases on this. API artifacts are versioned down to the service release level, while specs only have a major/minor value. Just stick with what the release plan was for. Some specs are doing x.y.0 releases while others are just doing x.y.

Thanks for the clarification.  @starksm64 do you think I should proceed with the PMC/EMO emails right now?  Or should I wait for the final candidate CDI API (or anything else)?

**Comment by starksm64** [comment]
Just wait for the final CDI API candidate which should be out tomorrow. Then we can go to ballot.

**Comment by starksm64** [comment]
@scottkurz The copyright on the spec files has the date "2018, 2020". It really should "2018, 2022"

**Comment by starksm64** [comment]
@scottkurz The plan review ballot should look like the following so that it both formats correctly, and follows the ballot template we have used:

| Representative                     | Representative for: |  Vote  |
|------------------------------------|---------------------|--------|
| Kenji Kazumura                     | Fujitsu             |  +1  |
| Dan Bandera, Kevin Sutter          | IBM                 |  +1  |
| Ed Bratt, Dmitry Kornilov          | Oracle              |  +1  |
| Andrew Pielage, Matt Gill          | Payara              |  +1  |
| Scott Stark, Mark Little           | Red Hat             |  +1  |
| David Blevins, Jean-Louis Monteiro | Tomitribe           |  +1  |
| Ivar Grimstad                      | EE4J PMC            |  +1  |
| Marcelo Ancelmo, Martijn Verburg   | Participant Members |  +1  |
| Werner Keil                        | Committer Members   |  +1  |
| Scott (Congquan) Wang              | Enterprise Members  |  +1  |
|                                    | **Total**           |  10 |

**Comment by starksm64** [comment]
@ivargrimstad The copyright date and plan review ballot format on {spec}/x.y/_index.md  are the only minor issues left to go to ballot.

**Comment by scottkurz** [comment]
> @ivargrimstad The copyright date and plan review ballot format on {spec}/x.y/_index.md are the only minor issues left to go to ballot.

@starksm64,  I respun to address both issues.

For the copyright, it must have been the one in the spec doc, section 1.1.  I updated that.

For the plan review (now I understand Ed's comment on the same point earlier),  I pushed a commit hopefully fixing it.

I wasn't sure how literally to present the voting member history, so I went back and looked at the mailing list and narrowed it down to the voting individual for each company/org represented.   I can easily revert to the full set of names if that's better.  One note too:  Dr. Jun Qian listed a vote representing 'Primeton', but I assume it's OK to list it under "Enterprise Members"?

**Comment by scottkurz** [comment]
@starksm64 - one thing I was unsure about... for this step:
> If a Release Review is required, the specification project team contacts the EMO to initiate the review by sending an email to [emo@eclipse.org](mailto:emo@eclipse.org).

Is that something you did already ?  I am aware of this issue:
https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/240
but I didn't email EMO myself .  Thanks.

**Comment by starksm64** [comment]
@scottkurz No, I did not do that so I'm not sure how the issue was created. I assumed it was you.

**Comment by scottkurz** [comment]
@starksm64 
> @scottkurz No, I did not do that so I'm not sure how the issue was created. I assumed it was you.

From the https://www.eclipse.org/projects/handbook/#release-review process...
<html><body>


  | The EMO will likely notice that you’ve created the release record,  connected with your PMC, and submitted an IP Log for review by the IP  team and will take steps to initiate the actual review. However, since  there is a great deal of variability in this process, send an email to EMO stating your intent to release.
-- | --

so this seems to be where the issue comes from.

Please let me know if you think I should be sending the email or someone else?  Thanks.

**Comment by starksm64** [comment]
@scottkurz go ahead and send the email using the "Send Email to the PMC..." link in the Committer Tools section of the https://projects.eclipse.org/projects/ee4j.batch page.

**Comment by scottkurz** [comment]
> @scottkurz go ahead and send the email using the "Send Email to the PMC..." link in the Committer Tools section of the https://projects.eclipse.org/projects/ee4j.batch page.

Looks like we're covered: https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/240#note_588476

**Comment by starksm64** [comment]
@scottkurz I don't see that the copyright line on the specifications have been updated. I checked both the preview of the website and the pdf file in the current set of changes files. The plan review ballot has been updated and looks good.

**Comment by scottkurz** [comment]
> @scottkurz I don't see that the copyright lines on the specifications have been updated. I checked both the preview of the website and the pdf file in the current set of changes files. 

@starksm64 could you please tell me how you're going about looking?

If I look at the HTML/PDF within staged specification zip:  https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/batch/specification/2.1.0/specification-2.1.0.zip

I see:
image

**Comment by starksm64** [comment]
I'm looking at the pdf attached to this PR. That is what will be promoted to the jakarta.ee specifications section. It won't be extracted from the current staging repo.

**Comment by scottkurz** [comment]
> I'm looking at the pdf attached to this PR. That is what will be promoted to the jakarta.ee specifications section. It won't be extracted from the current staging repo.

Ah...that slipped my mind.   Updated now.  Thanks

**Comment by ivargrimstad** [comment]
Great!
I'll get the ballot started shortly

**Comment by scottkurz** [comment]
Let me note an issue just popping up on the platform mailing list:
https://www.eclipse.org/lists/jakartaee-platform-dev/msg03312.html

@starksm64 - unless there's any specific requirement or expectation that we do provide a 2.1 schema I'd just as soon leave it alone, stick to our 2.0 versions and accept that these are separately versioned than the Java / spec artifacts.   True there are pros/cons either way but no one (active in Batch) has identified a need until now.    Appreciate your thoughts...thanks.

**Comment by starksm64** [comment]
There is no need for schemas to be in lock step with the specs. If there are no changes there is no reason to update the schema file.

**Comment by ivargrimstad** [comment]
* On ballot completion, the specification committee mentor:
 - [ ] adds this final checklist to the main PR.
 - [ ] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [ ] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
 - [ ] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [ ] creates an issue in the specification project that includes the following checklist for the specification project team:
 \<include url of Issue here>

**Pull request merged**
