### PR TITLE
Jakarta Management API 1.1 Specification

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

## Specification PR template
When creating a specification project release review, create two PRs with the content divided as follows.

Include the following in PR#1:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of wombat_x.y.pdf
- [x] Specification HTML in the form of wombat_x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] For a Release Review, a summary that a Compatible Implementation
      is complete, passes the TCK, and that the TCK includes sufficient
      coverage of the specification. The TCK users guide MUST include
      the instructions to run the compatible implementations used to
      validate the release.  Instructions MAY be by reference.
     N/A - Covered by Glassfish Compatible Implementation
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://oss.sonatype.org/content/repositories/staging/jakarta/management/j2ee/jakarta.management.j2ee-api/1.1.4/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      N/A - Covered by [Jakarta EE Platform TCK](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-jakartaeetck-8.0.0.zip)
- [x] The URL of the compatibility certification request issue:
      [Eclipse Glassfish Certification Request](https://github.com/eclipse-ee4j/jakartaee-platform/issues/99)
      [Management Certification Request](https://github.com/eclipse-ee4j/management-api/issues/46)
These are basically the same since Glassfish is the Compatible Implementation for both.  Except, the latter one references the Management 1.1 Spec and is more consistent with the expected process.

### CODE REVIEW

**Comment by scottkurz** [comment]
1. missing **management/_index.md**
2. Even though there's a run at the platform level _("Glassfish Certification Request")_ shouldn't  maybe the PR comment as well as the **management/1.1/_index.md** still link to the certification request issue?
3. The spec document (PDF/HTML) has the project as **Jakarta Management 1.1** and the version as **1.1.4**.   I think these should be:  **Jakarta Management** and **1.1** instead right?   I don't know if the 1.1.4 version shows up in the spec at all.

**Comment by scottkurz** [comment]
For 3., I included a PR [here](https://github.com/eclipse-ee4j/management-api/pull/43/files)

**Comment by scottkurz** [comment]
One more issue in the spec PDF.  If you click on the link under text displayed:  `https://projects.eclipse.org/projects/ee4j.jakartaee-stable` in the beginning the underlying URL is 
`https://projects.eclipse.org/projects/ee4j.jakartaee-stable1.1.4`

**Comment by kwsutter** [comment]
> For 3., I included a PR [here](https://github.com/eclipse-ee4j/management-api/pull/43/files)

Thanks, @scottkurz.  I just left a comment on the PR asking to be rebased on master...

**Comment by kwsutter** [comment]
>     1. missing **management/_index.md**
Thanks, got it!

>     2. Even though there's a run at the platform level _("Glassfish Certification Request")_ shouldn't  maybe the PR comment as well as the **management/1.1/_index.md** still link to the certification request issue?
Possibly.  Per your similar comment on the Managed Beans spec, I'm not clear on this since the Platform Certification Request hasn't been created yet...

>     3. The spec document (PDF/HTML) has the project as **Jakarta Management 1.1** and the version as **1.1.4**.   I think these should be:  **Jakarta Management** and **1.1** instead right?   I don't know if the 1.1.4 version shows up in the spec at all.
Yes, good catch.  Jim and I were talking about similar changes earlier today.  Thanks for the PR, I'll take a look.

**Comment by dblevins** [comment]
# Spec Review Checklist

## 1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://oss.sonatype.org/conte/repositories/staging/jakarta/{spec}/jakarta-{spec}-api/x.y.z/
https://oss.sonatype.org/content/repositories/staging/jakarta/jms/jakarta.jms-api/2.0.3/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] Second PR for just apidocs

## 2. _index.md
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

## 3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

## 4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

## 5. Spec HTML
  - [ ] Same as PDF

## 6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG) (refers to RI)

## 7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

## 8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
fd175e1742a1c9e23dbc0aa0b8b881965fcead0336c121c2dac27a00a8fa113d
  - [ ] Request issue has `certification` label.

## 9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

**Comment by dblevins** [comment]
@kwsutter I didn't check "Name of and link to at least one Compatible Implementation" as ideally the link is to a webpage vs the actual download.  People should really know where they got it from so they know where to get help and that jakarta.ee is not the actual producer of the binary.  (i.e. they need to see they left the jakarta.ee website and then get the binary)

**Comment by kwsutter** [comment]
> @kwsutter I didn't check "Name of and link to at least one Compatible Implementation" as ideally the link is to a webpage vs the actual download. People should really know where they got it from so they know where to get help and that jakarta.ee is not the actual producer of the binary. (i.e. they need to see they left the jakarta.ee website and then get the binary)

@dblevins I think most people have been doing a direct link.  If I just did the download page (ie. https://projects.eclipse.org/projects/ee4j.glassfish/downloads), then eventually the user will have to know which version to select for download.  A direct link prevents that question mark.  We can discuss when we review this.  Thanks.

**Comment by bshannon** [comment]
@kwsutter This PR should refer to a certification request in the management-api project.

**Comment by kwsutter** [comment]
> @kwsutter This PR should refer to a certification request in the management-api project.

I didn't know we closed on this.  The last reply I did on this topic showed very little difference between a standalone CR and the platform CR (I used managed beans as an example).  I didn't see any additional followups, so I assumed either way was fine for now.

**Comment by kwsutter** [comment]
> > @kwsutter This PR should refer to a certification request in the management-api project.
> 
> I didn't know we closed on this. The last reply I did on this topic showed very little difference between a standalone CR and the platform CR (I used managed beans as an example). I didn't see any additional followups, so I assumed either way was fine for now.

I have added [CR #46](https://github.com/eclipse-ee4j/management-api/issues/46) to the Description above -- just to be complete.

**Comment by kwsutter** [comment]
@dblevins - I know you have the todo for Management API, but I just found out that we accidentally promoted the Management API jars at the same time we were doing the JAXR jars...  So, I put this checklist here and marked that one item off.  Thanks.

* On ballot completion
 - [ ] The designated specification committee representative adds this final checklist to the main PR.
 - [ ] The specification committee representative merges the specification PRs.
 - [ ] The designated specification committee representative calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job.
 - [x] The specification project member who created the staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [ ] The EMO updates the specification page with the ballot results.
This list goes on the committed spec index page.
 - [ ] The specification project team should go through the merged spec website page to verify all the links are valid.
 - [ ] The specification project team should approve the compatibility request.
 - [ ] The compatible implementation project/vendor MUST send an email tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [ ] The specification project team should merge any final release branch as appropriate for the branch management for the project.

**Pull request merged**
