### PR TITLE
Promote Faces TCK 4.0.3

### PR DESCRIPTION
**Pull request by arjantijms**
Please also promote the binary from 

https://www.eclipse.org/downloads/download.php?file=/faces/jakartaee10/staged/eftl/jakarta-faces-tck-4.0.3.zip

to

https://download.eclipse.org/jakartaee/faces/4.0/jakarta-faces-tck-4.0.3.zip

### CODE REVIEW

**Comment by ivargrimstad** [comment]
The promotion script expects the file to be in a location like this: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/

The URL pointing to the download.php service does not work.

**Comment by arjantijms** [comment]
> The URL pointing to the download.php service does not work.

That's annoying indeed. The GlassFish scripts have the same issue. At some point Eclipse resorted to this other format.

See: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2817

**Comment by arjantijms** [comment]
@ivargrimstad after inspecting the redirect headers etc after clicking on the download link manually, I found this URL:

https://download.eclipse.org/faces/jakartaee10/staged/eftl/jakarta-faces-tck-4.0.3.zip

Can you try that one?

**Comment by ivargrimstad** [comment]
Yes, that one worked!

**Review by ivargrimstad — APPROVED** [review]

**Pull request merged**
