### PR TITLE
Experimenting...  Modify entry for CCRs

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

This PR will be used to experiment with altering the entry on the Platform (and eventually Web Profile) Specifications page when identifying the Compatible Implementations for a particular version.

### CODE REVIEW

**Comment by kwsutter** [comment]
This first iteration simplifies the list of CIs to a single query for a defined Milestone (EE 9.1 CCRs).  This allows us to remove the "for ratification" item that caused some concern in the past.  Instead, I added a `ratified` label that would be added to the specific CCR that was used to ratify the Specification.  We still need this identification for the Spec version, but it's not as blatant as the previous mechanism.

**Review by ivargrimstad — APPROVED** [review]
I like it

**Comment by kazumura** [comment]
I would suggest to use "Compatible Implementations" instead "Compatbile Certification Requests"
because EFSP defines 'Specification' as the set of API, TCK and CI.
CCRs do not make sense in the speicification page.
I think it is good idea to use the link of CCR list for "Compatible Implementations".
But CCR list should include only the ones labeld "accepted".

**Comment by kwsutter** [comment]
> I would suggest to use "Compatible Implementations" instead "Compatible Certification Requests"
> because EFSP defines 'Specification' as the set of API, TCK and CI.
> CCRs do not make sense in the specification page.
> I think it is good idea to use the link of CCR list for "Compatible Implementations".

I'd be okay with that.  I was trying to match up the title with the URL content...  But, if "Compatible Implementations" is still okay with everyone but still reference the list of CCRs, I'm fine with making that change.

> But CCR list should include only the ones labeled "accepted".

Hmmm...  This is easier said than done.  The nice thing about using a Milestone is that all CCRs can be shown regardless of State or Labels.  I'm not aware of a means to filter a Milestone report based on a Label.  If we want to filter on the `Accepted` Label, then we would also have to use additional label filters such as `EE10` (or the like).  And, also ensure that we show both Open and Closed issues.  This could be done, but does the extra work and query provide any additional benefit?

**Comment by ivargrimstad** [comment]
Closing this PR following the discussion in the spec committee.

**Pull request closed without merging**
