### PR TITLE
Jakarta Concurrency 3.0.4 service release

### PR DESCRIPTION
**Pull request by KyleAure**
Fixes https://github.com/jakartaee/concurrency/issues/374

- [x] Need to promote TCK-Dist here: https://download.eclipse.org/ee4j/cu/jakartaee10/promoted/eftl/

### CODE REVIEW

**Review by scottmarlow — APPROVED** [review]

**Review by jamezp — APPROVED** [review]

**Comment by scottmarlow** [comment]
@ivargrimstad did you also run the Specification Committee CI job to promote https://www.eclipse.org/downloads/download.php?file=/ee4j/cu/jakartaee10/promoted/eftl/concurrency-tck-3.0.4.zip?  I don't yet see concurrency-tck-3.0.4.zip under https://download.eclipse.org/jakartaee/concurrency/3.0/

**Comment by ivargrimstad** [comment]
Yes, and I see it there. It's probably a caching issue. Try refreshing or with a different browser

https://download.eclipse.org/jakartaee/concurrency/3.0/concurrency-tck-3.0.3.zip

**Comment by ivargrimstad** [comment]
> Yes, and I see it there. It's probably a caching issue. Try refreshing or with a different browser
> 
> https://download.eclipse.org/jakartaee/concurrency/3.0/concurrency-tck-3.0.3.zip

Ah., sorry my mistake. This is 3.0.3. The job crashed and the ci is being restarted...

**Comment by ivargrimstad** [comment]
Done!

**Comment by scottmarlow** [comment]
Thanks @ivargrimstad!  

I do see the published Concurrency 3.0.4 zip download now but guess the website might need some time for the update (I did refresh my browser).  Just mentioning that in case something on CI needs to restart for the website update.

**Comment by ivargrimstad** [comment]
Yes, the website update runs on an (unknown) shecdule. I'll trigger it with an update so the updates should be live in about 15 minutes.

**Pull request merged**
