### PR TITLE
Jakarta Transactions 1.3

### PR DESCRIPTION
**Pull request by tomjenkinson**
Signed-off-by: Tom Jenkinson <tom.jenkinson@redhat.com>
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of wombat_x.y.pdf
- [x] Specification HTML in the form of wombat_x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] For a Release Review, a summary that a Compatible Implementation
      is complete, passes the TCK, and that the TCK includes sufficient
      coverage of the specification. The TCK users guide MUST include
      the instructions to run the compatible implementations used to
      validate the release.  Instructions MAY be by reference.
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://oss.sonatype.org/content/repositories/staging/jakarta/transaction/jakarta.transaction-api/1.3.3/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-transactions-tck-1.3.0.zip
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/jta-api/issues/50

Include the following in PR#2:
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory.
https://github.com/jakartaee/specifications/pull/26

### CODE REVIEW

**Comment by dblevins** [comment]
Spec PDF looks good.

**Comment by dblevins** [comment]
I filled out the checkboxes so all PRs have the same number.  If some of them are not applicable, check them and use "N/A" as the requested URL.

Note I unchecked the OSSRH staging repo box as there needs to be a URL like this one:

 - https://oss.sonatype.org/content/repositories/jakartaejb-1013/jakarta/ejb/jakarta.ejb-api/3.2.6/

**Comment by bshannon** [comment]
> Note I unchecked the OSSRH staging repo box as there needs to be a URL like this one:
> 
>     * https://oss.sonatype.org/content/repositories/jakartaejb-1013/jakarta/ejb/jakarta.ejb-api/3.2.6/

No, it's not supposed to be in a "local" staging repository, it's supposed to be in the "global" staging repository, e.g., https://oss.sonatype.org/content/repositories/staging/jakarta/ejb/jakarta.ejb-api/3.2.6/.

**Comment by dblevins** [comment]
This spec is due for review and promotion to vote August 16th.  Can you review this checklist and ensure all requirements are met:
https://github.com/jakartaee/specification-committee/blob/master/spec_review_checklist.md

**Comment by kwsutter** [comment]
# Spec Review Checklist

1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://oss.sonatype.org/conte/repositories/staging/jakarta/{spec}/jakarta-{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] Second PR for just apidocs

2. _index.md
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

**Comment by NottyCode** [comment]
# Spec Review Checklist

1. Spec PR
  - [x] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [x] Directory of form {spec}/x.y
  - [x] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [x] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [x] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [x] Staging repository link of the form https://oss.sonatype.org/conte/repositories/staging/jakarta/{spec}/jakarta-{spec}-api/x.y.z/
  - [x] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [x] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [x] Second PR for just apidocs

2. _index.md
  - [x] Link to spec pdf
  - [x] Link to spec html
  - [x] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [x] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [x] Footer contains Eclipse copyright and link to license
  - [x] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [x] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [x] Correct spec title
  - [x] Version number of the form x.y, not x.y.z
  - [x] Correct Eclipse copyright line
  - [x] No DRAFT or SNAPSHOT
  - [x] Correct Logo

5. Spec HTML
  - [x] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [x] EFTL license file, preferably named LICENSE.md
  - [x] User's Guide (or equivalent documentation)
  - [x] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [x] Software requirements listed
  - [x] Installation and configuration described
  - [x] How to run tests
  - [x] Where to file challenges

8. Compatibility certification request
  - [x] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [x] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [x] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [x] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

**Comment by NottyCode** [comment]
The following issues need to be resolved:

1. There is no {spec}/_index.md file
1. The `jakarta_ee_logo_schooner_color_stacked_default.png` needs to be removed from the PR.
1. The TCK link in the PR description doesn't match the template form. I'm not sure if this is an issue or not, I will check the PR's being voted on. In the meantime I'm adding this so it doesn't get lost.
1. The _index.md doesn't link to the CI project.
1. The javadoc PR has a META-INF folder
1. The compatibility certification request doesn't contain the `certification` label
1. The TCK results summary doesn't include all information in the certification request
1. The TCK results summary does not include the SHA-256 fingerprint.

**Comment by NottyCode** [comment]
I've gone through and verified and completed the checklist. This looks go to me.

**Comment by kwsutter** [comment]
> @dblevins just a ping to say that it is ready for review now in response to your comment [here](https://github.com/jakartaee/specifications/pull/25#issuecomment-519995601). Do I need to do some other notification too? Thanks!

You're good, @tomjenkinson!  It's on our list to pre-review for today and hopefully go to ballot shortly after.  Thanks!

**Comment by dblevins** [comment]
@tomjenkinson The staged API binaries will be expired and deleted automatically by Nexus OSSRH on Sunday, Sept 1 st, therefore the Steering Committee has approved publishing this API jar early.  Can you publish this api jar to Maven Central at your earliest convenience?

In the event the binaries are deleted before you can get to it, here is a backup of your staged repository.  
[jakartatransaction-1022.tar.gz](https://github.com/jakartaee/specifications/files/3557762/jakartatransaction-1022.tar.gz)

**Comment by kwsutter** [comment]
* On ballot completion
 - [x] The designated specification committee representative adds this final checklist to the main PR.
 - [ ] The specification committee representative merges the specification PRs.
 - [ ] The designated specification committee representative calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job.
 - [ ] The specification project member who created the staging release promotes the specification api jars to maven central.
 - [ ] The EMO updates the specification page with the ballot results.
This list goes on the committed spec index page.
 - [ ] The specification project team should go through the merged spec website page to verify all the links are valid.
 - [ ] The specification project team should approve the compatibility request and send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [ ] The specification project team should merge any final release branch as approriate for the branch management for the project.

**Comment by kwsutter** [comment]
> @kwsutter I can't edit your comment so just to mention that https://search.maven.org/artifact/jakarta.transaction/jakarta.transaction-api/1.3.3/jar exists (re: "The specification project member who created the staging release promotes the specification api jars to maven central.")

Thank you!

**Comment by smillidge** [comment]
I assume the email request to tck@... Is one for the whole platform so it can use the Jakarta Compatible logo? Rather than one for each api?

Steve

**Comment by waynebeaton** [comment]
> Also looking at https://github.com/jakartaee/specifications/blame/master/transactions/1.3/_index.md it seems that "The EMO updates the specification page with the ballot results." has been done, whether we need @waynebeaton to formally confirm on here that it is final before you check the box I am not sure?

My apologies. I missed checking the box on a couple of these.

**Comment by bshannon** [comment]
> I assume the email request to tck@... Is one for the whole platform so it can use the Jakarta Compatible logo? Rather than one for each api?

The wording in the [checklist](https://github.com/jakartaee/specification-committee/blob/master/spec_finalization_checklist.md) is a bit misleading.

Section 4.b of the [EFTL](https://www.eclipse.org/legal/tck.php) requires any implementation of **any** spec to send a message to
tck@eclipse.org before making any claim of compatibility.  Doing so is also necessary
before requesting use of the trademark for those specs that allow it (currently only the
full platform and the web profile).

**Comment by bshannon** [comment]
> @kwsutter I noted a difference between the wording in your checkbox "The specification project team should approve the compatibility request and send an email to [tck@eclipse.org](mailto:tck@eclipse.org) for approval of the compatible implementation for trademark usage." and the one from @bshannon to the jakartaee-spec-project-leads mailing list which says "The compatible implementation project/vendor MUST send an email tck@xxxxxxxxxxx for approval of the compatible implementation for trademark usage." which I think means this would instead be an action for the Glassfish team /cc @smillidge

See my previous response.  I don't know where Kevin's text came from, but mine came from
the [checklist](https://github.com/jakartaee/specification-committee/blob/master/spec_finalization_checklist.md), which we should probably update to be more clear.

**Comment by bshannon** [comment]
@tomjenkinson Please confirm that email was sent to tck@eclipse.org.

**Comment by bshannon** [comment]
@tomjenkinson I don't think @smillidge is planning to send a message to tck@eclipse.org for each spec for which GlassFish is a compatible implementation, but I'm happy for you and him to communicate and decide which of you should send the message.  Just please make sure that it's done.  Thanks.

**Comment by bshannon** [comment]
@smillidge Please confirm that you've sent email to tck@eclipse.org for this spec.

**Comment by bshannon** [comment]
@smillidge Once again, please confirm that you've sent email to tck@eclipse.org for this spec.

**Comment by arjantijms** [comment]
@bshannon I can sent the email if needed. Since I had prepared emails for all the specs Payara was/is involved with, this one is even still in my draft folder.

**Comment by bshannon** [comment]
I'm not sure why @smillidge can't do it.  Or maybe he's already done it and just hasn't told us.  It seemed most appropriate for a Project Lead from the GlassFish project to do it.

**Comment by arjantijms** [comment]
Dunno, for me it's as trivial as pushing a button on an already composed mail in my drafts folder, but let's wait a little for Steve then. It's 23:00 currently in the UK ;)

**Comment by smillidge** [comment]
I haven't sent the email. Not sure why I have to and who or what is wanting to use the Jakarta Compatible trademark? The GlassFish project has already requested the Jakarta Compatible trademark for GlassFish based on it passing the platform specification.

**Comment by smillidge** [comment]
Also btw I never got a response from sending an email on behalf of the GlassFish project to tck@eclipse.org.

**Comment by bshannon** [comment]
@smillidge 
> I haven't sent the email. Not sure why I have to and who or what is wanting to use the Jakarta Compatible trademark? The GlassFish project has already requested the Jakarta Compatible trademark for GlassFish based on it passing the platform specification.

This has nothing to do with the trademark.

As described in the Eclipse Foundation TCK License, mail needs to be sent to claim compatibility
with a specification.  The Jakarta Transactions specification approval lists GlassFish as a compatible
implementation.  We would like to be able to claim that GlassFish is a compatible implementation
of the Jakarta Transactions specification, so the message needs to be sent.

> Also btw I never got a response from sending an email on behalf of the GlassFish project to [tck@eclipse.org](mailto:tck@eclipse.org).

No response is expected.  You just need to send the message asserting that GlassFish is a
compatible implementation of the spec.

Please let us know when you've sent the message.  If you prefer that someone else sends the
message on behalf of the GlassFish project, let us know.

Thanks.

**Comment by smillidge** [comment]
Someone else can do it then. I'm not going to work through all specs, find the URL and send the email.

**Comment by arjantijms** [comment]
@smillidge no worries, as said I had the mail still in drafts and just sent it.

**Comment by smillidge** [comment]
I assume a mail is required for all individual specs? I only sent mails for Full Profile and Web Profile on behalf of the GlassFish project.

**Comment by smillidge** [comment]
@arjantijms thanks for sending the email but it should have the URL of the test results in the mail

**Comment by bshannon** [comment]
The email should have a link to the Compatibility Certification Request issue.

I believe Jakarta Transactions is the only one outstanding for GlassFish.  In the other cases
the spec project lead was also a Committer on GlassFish so they sent it themselves.

**Comment by arjantijms** [comment]
@smillidge I put a link to the PR in the mail (https://github.com/jakartaee/specifications/pull/25), which contains a link to the CR issue in its description along side all other info.

This is the same/similar mail I send for all other projects (Security, Faces, Servlet, Interceptors, Authentication, Authorization, Expression Language, ...)

**Comment by smillidge** [comment]
Why isn't any of this documented in the EFSP and the JESP specialisation https://jakarta.ee/about/jesp/ ?
The TCK license agreement has

`make TCK test results showing full and complete satisfaction of all requirements of the TCK publicly available on the testing party’s website and send a link to such test results to Eclipse at tck@eclipse.org` not a reference to a PR (sigh)

I think an overhaul of the documentation of this process is needed, IMHO it's currently incomprehensible to anybody who's not sat in the spec committee.

**Comment by bshannon** [comment]
We tried to clarify this in the [TCK process document](https://github.com/jakartaee/specification-committee/blob/master/process.adoc#accepted-certification-requests), but there continues to be confusion over
logo/trademark requirements vs. general TCK requirements.  I've updated the above to try to
make it more clear.

**Comment by smillidge** [comment]
Probably best to take to the spec committee but these process documents aren't linked to the main process pages on the Jakarta.ee website.

**Comment by bshannon** [comment]
> Probably best to take to the spec committee but these process documents aren't linked to the main process pages on the Jakarta.ee website.

We filed an [issue](https://github.com/jakartaee/specification-committee/issues/13) long ago, but it hasn't been implemented yet.

**Pull request merged**
