### PR TITLE
Jakarta Annotations 1.3.3

### PR DESCRIPTION
**Pull request by rotty3000**
Signed-off-by: Raymond Augé <raymond.auge@liferay.com>

## Specification PR template
Include the following:
- [x] A directory in the form wombat/x.y containing the following.
- [x] Specification PDF in the form of wombat_x.y.pdf
- [x] Specification HTML in the form of wombat_x.y.html
- [x] Specification JavaDoc in the apidocs directory.
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [ ] For a Release Review, a summary that a Compatible Implementation
      is complete, passes the TCK, and that the TCK includes sufficient
      coverage of the specification. The TCK users guide MUST include
      the instructions to run the compatible implementations used to
      validate the release.  Instructions MAY be by reference.
- [ ] The URL of the OSSRH staging repository for the api, javadoc:
      <add URL here>
- [ ] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      <add URL here>
- [ ] The URL of the compatibility certification request issue:
      <add URL here>

### CODE REVIEW

**Comment by rotty3000** [comment]
I'm fairly certain that this has the wrong version. I suspect it should be 1.3.4 or maybe even 1.3.5?

**Comment by dblevins** [comment]
Not sure if this is a showstopper, but there are some "Java EE" references we might want to convert:

```
annotations/1.3.3/apidocs/javax/annotation/ManagedBean.html:154: Java EE module. For each named Managed Bean, Java EE containers must make
annotations/1.3.3/apidocs/javax/annotation/PreDestroy.html:107: the <code>PostConstruct</code> annotation except the Java EE application 
annotations/1.3.3/apidocs/javax/annotation/sql/DataSourceDefinition.html:110: Java EE namespace, which will determine the accessibility of

```

**Comment by dblevins** [comment]
Spec status is Draft, but should be Final or Final Release. 
“Version: 1.3.3-SNAPSHOT” should be a final number.

**Comment by m0mus** [comment]
Please close this PR. It's replaced with the following PRs:
https://github.com/jakartaee/specifications/pull/69
https://github.com/jakartaee/specifications/pull/70

**Pull request closed without merging**
