### PR TITLE
Update the NoSQL to a 1.0.0-b4

### PR DESCRIPTION
**Pull request by otaviojava**
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of wombat-spec-x.y.pdf
- [x] Specification HTML in the form of wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md

### CODE REVIEW

**Comment by ivargrimstad** [comment]
Is this PR to be handled as a request for a progress review?

**Comment by otaviojava** [comment]
@ivargrimstad  progress review

**Comment by ivargrimstad** [comment]
> @ivargrimstad progress review

Ok, I'll label it as such and bring it to the spec committee's attention.

**Comment by ivargrimstad** [comment]
@otaviojava The Specification Committee will define a checklist to use for the review and come back to you when the review starts if additional information is needed.

**Comment by kazumura** [comment]
1. Spec PR for Plan / Proposal
  - [x] There is no new material that wasn't previously provided that would impact the existing Specification "work in progress" page layout.

2. _index.md
  - [x] If there are milestones previously approved and/or documented on the Specification page, but now out of date, or not feasible (missed checkpoints or other milestones), there must be a proposed PR to refresh the previously approved plan material.
  - [x] The progress review should demonstrate the agreed plan is still correct and accurate. If it is not, the Progress Review is an opportunity to revise the plan as needed.
  - [x] Mentor to confirm (via consultation with committer team) the scope is correct. If it has been revised, those changes should be summarized. Regardless, the committer team is responsible for providing any statements or documentation describing progress for the progress review materials.
    - [x] The mentor may wish to review the Plan Review Ballot checklist to confirm all items are captured. 
    - [x] If checkpoint or scope material is derived from issues or epic issues, the mentor may wish to request the committer team provide a summary statement of the specific progress against the issue or issues. 
    - [x] The committer team should provide an overall assessment that confirms they are "on track" or produces a plan revision that reflects the evolution since the last ballot. 
  - [x] The mentor should focus material for this review on progress of this specification revision and not the progress or changes associated with higher level projects (i.e. it is probably insufficient to say "schedule changed in Platform Release Plan so we're changing too"). Scope changes that have been imposed on this specification may certainly be noted and may be a source for plan revisions.
  - [x] Any changes or additional requirements, resource needs (e.g. CI/CD resources), feature changes, etc. should be reflected in the specification plan revision. If there are no changes the committer team should be able to demonstrate that they are progressing within the original plan that is already approved.

3. Proposed Spec PDF (Optional)
  - [x] Correct spec title, clearly marked preliminary
  - [x] Correct Eclipse copyright line
  - [x] Must indicate DRAFT or SNAPSHOT
  - [ ] Correct Logo

4. Proposed Spec HTML (Optional)
  - [x] Same as PDF

5. TCK
  - [x] Some statement or evidence of TCK development progress and accomplishment from previous review

6. EMO Requirements 

    N/A

**Comment by kazumura** [comment]
@otaviojava 
Ballot are approved.
But there are some comments. Please address them.

- The page should be converted into the new template
- The plan should be updated to reflect reality. Particularly the statement "Next quarter, we’ll work on JPA and NoSQL integration and move the API forward to use Java 11 as a minimum requirement, and upgrade the API to the Jakarta EE 10 as soon it gets a release."
- Minimum Java SE version should be stated for the spec according to the new template and not as a reference to a Jakarta EE release

We don't have a problem with the spec exploring this direction, but we currently have no interest in incorporating this in any profile or the platform because we don't see this as required.

We don't have a problem with the spec exploring this direction, but we currently have no interest in incorporating this in any profile or the platform.  We'd also want to see interest and active work in a second implementation before this spec would be proposed final.

If there really isn't interest in a second implementation, perhaps this would be better as a library vs a spec.

**Pull request merged**
