### PR TITLE
Jakarta Mail 2.0.1 (SR)

### PR DESCRIPTION
**Pull request by lukasj**
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>

## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [ ] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
       N/A
- [ ] Specification HTML in the form of jakarta-wombat-spec-x.y.html
       N/A
- [ ] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
       N/A
- [ ] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
       N/A
- [ ] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [ ] Updated release record
   - [ ] Generated IP Log
   - [ ] Email to PMC
   - [ ] Start release review by emailing EMO 
       N/A
- [x] For a [Service Release Review](https://jakarta.ee/committees/specification/operations/#creating_a_final_service_release_specification)
   - [x] Updated release record
    https://projects.eclipse.org/projects/ee4j.mail/releases/2.0.1
   - [x] Add Change Log
   - [x] Start release review by emailing Specification Committee
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/mail/jakarta.mail-api/2.0.1/
- [ ] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
       N/A
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/mail/issues/538
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by lukasj** [comment]
Javadoc changes:
* Cp year change
* added API version there
* added pointer to project's mailing list in the footer
* built by/on/for JDK 11

**Comment by ivargrimstad** [comment]
+1 LGTM

**Review by ivargrimstad — APPROVED** [review]

**Comment by kwsutter** [comment]
@ivargrimstad and @lukasj, I posted this in #336 as well, but where would be a good spot to document the extent of a service release.  Lukas added a comment in this Issue, or should it be in the index.md file, or maybe in the Eclipse release record?  We should decide on a common location and document it in the template and instructions.  Thanks!

Otherwise, this SR Issue looks good!  Thanks!

**Review by kwsutter — COMMENTED** [review]
Just the one comment about where to document the service release content...

**Comment by lukasj** [comment]
change log has been added

**Comment by kwsutter** [comment]
I'm good with this one as well.  @ivargrimstad?  Still good?

**Comment by ivargrimstad** [comment]
> I'm good with this one as well. @ivargrimstad? Still good?

Yes!
I'll go ahead and merge it.

**Pull request merged**
