### PR TITLE
Jakarta Management API 1.1 apidocs

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

## Specification PR template
When creating a specification project release review, create two PRs with the content divided as follows.

Include the following in PR#2:
- [x] Specification JavaDoc in the management/1.1/apidocs directory.

### CODE REVIEW

**Comment by dblevins** [comment]
- Fix: Yank META-INF dir
  https://github.com/jakartaee/specifications/pull/74/files#diff-149353dd6ef1c14279e65656659cce71R1

- Good: License file is present https://github.com/jakartaee/specifications/pull/74/files#diff-39d217329438c0fb022e947a321d21e5R1

- Good: Copyright is correct https://github.com/jakartaee/specifications/pull/74/files#diff-6d2553890d44ee7e4263650d337b55b4R229

**Comment by kwsutter** [comment]
>     * Fix: Yank META-INF dir
>       https://github.com/jakartaee/specifications/pull/74/files#diff-149353dd6ef1c14279e65656659cce71R1

Got it.  Thanks!

**Comment by dblevins** [comment]
@kwsutter mark this PR 'ready for review' when you get a chance.

**Comment by kwsutter** [comment]
> @kwsutter mark this PR 'ready for review' when you get a chance.

@dblevins I just did, but I thought all of us had the ability to promote a draft PR to a normal PR?  Didn't that work for you?  I've been having to do this on several of the PRs...

**Comment by dblevins** [comment]
@kwsutter I didn't even think to try to be honest.  I'll try on some others and delete my comment if it works.

**Pull request merged**
