### PR TITLE
Jakarta WebSocket 1.1

### PR DESCRIPTION
**Pull request by joakime**
Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of wombat_x.y.pdf
- [x] Specification HTML in the form of wombat_x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] For a Progress Review, that sufficient progress has been made on
      a Compatible Implementation and TCK, to ensure that the spec is
      implementable and testable.
- [x] For a Release Review, a summary that a Compatible Implementation
      is complete, passes the TCK, and that the TCK includes sufficient
      coverage of the specification. The TCK users guide MUST include
      the instructions to run the compatible implementations used to
      validate the release.  Instructions MAY be by reference.
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://oss.sonatype.org/content/repositories/staging/jakarta/websocket/
  https://oss.sonatype.org/content/repositories/staging/jakarta/websocket/jakarta.websocket-all/1.1.2/
  https://oss.sonatype.org/content/repositories/staging/jakarta/websocket/jakarta.websocket-api/1.1.2/
  https://oss.sonatype.org/content/repositories/staging/jakarta/websocket/jakarta.websocket-client-api/1.1.2/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-websocket-tck-1.1.0.zip
- [x] The URL of the compatibility certification request issue:
      eclipse-ee4j/websocket-api#308 (incomplete)

### CODE REVIEW

**Comment by starksm64** [comment]
For wave 1, this spec should be due by 8/7, so please review this ASAP. Note there is a good checklist for https://github.com/jakartaee/specification-committee/blob/master/spec_review_checklist.md

**Comment by joakime** [comment]
The TCK and compatible certification TCK parts for websocket-api are stuck.
Something that has been mentioned multiple times in eclipse-ee4j/websocket-api#295

The existing websocket TCK cannot be certified based on https://github.com/jakartaee/specification-committee/blob/master/process.adoc#materials-for-a-tck-release
For now, in order to make a certification request, I need a TCK that can be certified, and then a set of runs against it (for summary and SHA-256 requirements)
Then I need to point to the 2 TCK archives (public with its license and download.eclipse.org version with different license, as referenced in the above process/materials for a tck release doc).
The response to attempts to get information on how to get past this has been to wait till post Jakarta EE 8.

**Comment by starksm64** [comment]
# Spec Review Checklist

1. Spec PR
  - [x] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://oss.sonatype.org/conte/repositories/staging/jakarta/{spec}/jakarta-{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] Second PR for just apidocs

2. _index.md
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors

**Comment by starksm64** [comment]
> The TCK and compatible certification TCK parts for websocket-api are stuck.

For this PR all that is needed is a candidate final TCK that has the EFTL license. Once the jakartaeetck project has that, a run against that is what is needed. The jakarta spec committee signed version cannot exist at this point in the process. I'll clarify this in today's call.

**Comment by joakime** [comment]
> - [x] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}

Updated in initial issue summary of this issue

> - [ ]  Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip

Progress Stuck, process for this undefined.

> 4. Spec PDF
> - [x]  Version number of the form x.y, not x.y.z (has 1.1.2)

PDF Updated

> 8. Compatibility certification request
> - [x] Request follows template
> - [x] SHA-256 fingerprint matches staged TCK zip file
> - [x] Request issue has certification label.

Updated https://github.com/eclipse-ee4j/websocket-api/issues/308

> 9. TCK results summary
> - [ ] Page is hosted by Compatible Implementation project

Jakarta WebSocket API is a API only project.
Jakarta WebSocket API does not contain a compatible Implementation.  
The implementation tested was Tyrus.
The WebSocket TCK was tested against Glassfish, as that's the server container for Tyrus.
The Server API of Jakarta WebSocket was tested against Glassfish + Tyrus.
The Client API of Jakarta WebSocket was tested against Tyrus (without Glassfish).
These 2 categories of tests were performed in a single TCK execution.
https://eclipse-ee4j.github.io/websocket-api/TCK-Results.html

> - [x] Includes all information from certification request
> - [x] Summary includes number of tests passed, failed, errors

Completed.

**Comment by bshannon** [comment]
Ideally the TCK results would be hosted by the Tyrus project, since that's the Compatible Implementation, and Tyrus should be listed as the "product" in the certification request.

For this:
>  Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip

The intent is to supply the predicted URL that the TCK will be available at after it is finalized.
In this case, that would be https://download.eclipse.org/jakartaee/websocket/1.1/eclipse-websocket-tck-1.1.0.zip

**Comment by starksm64** [comment]
So in addition to setting the websocket/1.1/_index.md TCK link to what @bshannon has provided above, another run against the correct release of the TCK is needed and SHA256 values updated. A direct link to the build job artifact is https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run/lastSuccessfulBuild/artifact/standalone-bundles/eclipse-websocket-tck-1.1.0.zip

I have verified that this does not redirect to some CDN cache and that the size and SHA256 are:

```
Scotts-iMacPro:tmp starksm$ ls -la eclipse-websocket-tck-1.1.0.zip 
-rw-r--r--@ 1 starksm  wheel  11907247 Aug  7 01:52 eclipse-websocket-tck-1.1.0.zip
Scotts-iMacPro:tmp starksm$ shasum -a 256 eclipse-websocket-tck-1.1.0.zip 
30c501584c5fcce6b50bef34b96051df996dac3e79b8741871cb8e1b458db425  eclipse-websocket-tck-1.1.0.zip
```

**Comment by joakime** [comment]
> > Link to final TCK download zip file of the form [https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip](https://download.eclipse.org/jakartaee/%7Bspec%7D/x.y/*%7Bspec%7D-tck-x.y.z.zip)
> 
> The intent is to supply the predicted URL that the TCK will be available at after it is finalized.
> In this case, that would be https://download.eclipse.org/jakartaee/websocket/1.1/eclipse-websocket-tck-1.1.0.zip

Ah, this is a link to a future URL resource. Something that doesn't exist yet. 
Who is responsible for making that link on download.eclipse.org valid? (be it an upload, or a PR, or sftp, or a gerrit, or some other process that is complete mystery to me)

**Comment by bshannon** [comment]
> Who is responsible for making that link on download.eclipse.org valid? (be it an upload, or a PR, or sftp, or a gerrit, or some other process that is complete mystery to me)

Someone in the Spec Committee will run a Jenkins job that will create it, based on the "staged" TCK URL provided in the PR, after the spec is approved.

**Comment by joakime** [comment]
> another run against the correct release of the TCK is needed and SHA256 values updated. A direct link to the build job artifact is https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run/lastSuccessfulBuild/artifact/standalone-bundles/eclipse-websocket-tck-1.1.0.zip

TCK run is in process using new TCK zip link ... https://jenkins.eclipse.org/websocket/job/TCK_run/9/

**Comment by joakime** [comment]
> Ideally the TCK results would be hosted by the Tyrus project, since that's the Compatible Implementation, and Tyrus should be listed as the "product" in the certification request.

Requested that Tyrus enable their GitHub pages - https://github.com/eclipse-ee4j/tyrus/issues/681

**Comment by starksm64** [comment]
So the last issue is the TCK link on websocket/1.1/_index.md, but that we have not been letting hold up PRs going final.

**Comment by joakime** [comment]
The TCK Results PR at Tyrus is awaiting a review / merge - eclipse-ee4j/tyrus#682

**Comment by kwsutter** [comment]
@joakime Found one more item that needs to be updated.  The gray box at the top of the EFSL page needs to indicate the "Final" or "Final Release" status.  It can not be blank.

Screen Shot 2019-08-16 at 11 27 57 AM

**Comment by joakime** [comment]
> The gray box at the top of the EFSL page needs to indicate the "Final" or "Final Release" status. It can not be blank.

Updated in commit c5f6fe2c7030da691855b80157662ad4d7ef422d

**Comment by starksm64** [comment]
With that last change, this looks good. It was the only thing preventing this from going green, so removing draft label.

**Comment by joakime** [comment]
@starksm64 your commit b103c1f08ddcc77978f5097caef56ab881cad0e7 lacks the Eclipse Legal mandated `Signed-off-by` git footer.  (that's why this PR now fails on `eclipsefdn/eca` check.)

**Comment by dblevins** [comment]
@joakime The staged API binaries will be expired and deleted automatically by Nexus OSSRH on Wednesday, Sept 4th, giving you a very narrow window to publish after vote close Monday, Sept 2nd.  Explicit heads up so you're aware and can put 'publish api jars' at the top of your to-do list when you get back from US holiday on Tuesday.

Enjoy the long weekend and thank you for the amazing work shipping Jakarta EE 8!

**Comment by joakime** [comment]
@dblevins so jakarta websocket has not been voted on and approved yet, am I right in making that interpretation?
Just a bit confused while watching the other projects being encouraged to promote the staged release now.

**Comment by dblevins** [comment]
* On ballot completion
 - [x] The designated specification committee representative adds this final checklist to the main PR.
 - [ ] The specification committee representative merges the specification PRs.
 - [ ] The designated specification committee representative calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job.
 - [ ] The specification project member who created the staging release promotes the specification api jars to maven central.
 - [ ] The EMO updates the specification page with the ballot results.
This list goes on the committed spec index page.
 - [ ] The specification project team should go through the merged spec website page to verify all the links are valid.
 - [ ] The specification project team should approve the compatibility request and send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [ ] The specification project team should merge any final release branch as approriate for the branch management for the project.

**Comment by dblevins** [comment]
@joakime Keeping this terse to avoid confusion and questions.  Publish your staged binaries to maven central *now*.  They should have been expired and deleted yesterday, which means we have hours at best before they are deleted.

My note last week was an attempt to give you a heads-up so you could publish the moment your vote was approved on Monday and avoid scrambling.

If your binaries are deleted by the time you read this, I've attached a backup of your staging repo.
[jakartawebsocket-1008.tar.gz](https://github.com/jakartaee/specifications/files/3581295/jakartawebsocket-1008.tar.gz)

**Comment by dblevins** [comment]
h1. Published

 - jakarta-websocket-tck-1.1.0.zip
 - `30c501584c5fcce6b50bef34b96051df996dac3e79b8741871cb8e1b458db425`

```
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iQIcBAABAgAGBQJdcXt/AAoJEKvgVyXnfCtEB1cP/Rhb4ZISP3aG0AuM9CsvymF0
KLdI4hua+5GC1V90Pc7Y6D9juer9eSvAUKPIHMtICKvI3DOMrBaj0HHCGquj/dcC
HcZCF0/vFsrz/l7u7/gidfOF6hRnksi9c3mvJf/XAh8jaFIsDadDi57r+wSEktZb
X92mz3LIPUXAUIFH12xocuotFOjhV7RW30vB5kia/qVmmkofP8GQEwWlmF7/yP66
Zwj5VaIMJpN3R5bwcKbXSGe/hXGC4tMdun4M4ghyssdL5BcBbaXN3Zf9cOUgnvy4
K1wq8yPuHB9ONP20pDmDIQvpTA//9eBTdo6DPH3+KPMNF+k+U6sy2fZyGQt6SV+X
mzsIDsjT6cTdZCek1PxzN0KDmiSc2plhIh16GZhBUbi3mmEdxrtnq6ahXYF+VUyx
vq1p8yDm1916pKTIhhB0LfiLdCoaJ/yamwxPrezyWTyOHv3rpAECOh16trOJzWIl
Gqcc/hR4OfY5jXu6tdOtYvc1Oq8tWTN21eG0PZ480jMj1eFr+BgsMvLhO4/AMMYZ
tZHsSu6MHtRNNGwSBW5IrS++q5Qm7Y4DEVfa8CqA51POW9LwUglTZSL7GORQokiB
drZ7S2UUkNXi5qRNfkInpsXGJVOrb2ZdrW+OYbxulg2MoY3FR7idPpII9vhI16Fn
hsVCu12gZhpqXd0AXTJr
=6v/p
-----END PGP SIGNATURE-----
```

**Comment by bshannon** [comment]
The staged jar files still appear to be available. Please push them to Maven Central ASAP.

**Comment by joakime** [comment]
The Jakarta WebSocket 1.1.2 Jars are on Central - http://central.maven.org/maven2/jakarta/websocket/jakarta.websocket-api/1.1.2/

**Comment by dblevins** [comment]
Yay!  Thank you!  Checked that one off for you as we've realized you don't have edit ability to my comment with the checklist.  When you get these two done, let me know and I'll mark them:

[ ]  The specification project team should approve the compatibility request.
[ ] The specification project team should merge any final release branch as approriate for the branch management for the project.

**Comment by bshannon** [comment]
@joakime Please confirm that the remaining items on the [checklist](https://github.com/jakartaee/specifications/pull/79#issuecomment-528585080) have been completed.

**Comment by bshannon** [comment]
@joakime  Once again, please confirm that the remaining items on the checklist have been completed.

**Comment by joakime** [comment]
@bshannon it has not been done.   reaching out to the specification team now.

**Comment by bshannon** [comment]
I finally confirmed that all items on the release checklist have been completed.
@joakime Thanks.
@dblevins You're welcome.

**Pull request merged**
