### PR TITLE
Please promote Servlet TCK https://download.eclipse.org/jakartaee/servlet/6.0/jakarta-servlet-tck-6.0.2.zip

### PR DESCRIPTION
**Pull request by scottmarlow**
Please promote the Servlet 6.0.2 TCK for https://github.com/jakartaee/platform-tck/issues/1313 which addresses Platform TCK Challenge to update from optional web-app_2_3.dtd to (required) web-app_5_0.xsd

### CODE REVIEW

**Comment by scottmarlow** [comment]
@markt-asf are you okay with releasing a new Servlet 6.0.2 TCK zip that has been changed to use a web-app_5_0.xsd for one test?  The related discussion is on https://github.com/jakartaee/platform-tck/issues/1313 and doesn't involve Servlet specific TCK tests (as far as I know).

FYI, there will still be one test with  `web-app_2_3.dtd` (this test is excluded from the EE 10 Platform TCK which cannot include web-app_2_3.dtd or web-app_2_2.dtd tests).

**Comment by scottmarlow** [comment]
https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-servlet-tck-6.0.2.zip is the TCK to be staged when this pr is marked ready for review.

**Comment by markt-asf** [comment]
Not essential but I think the web.xml changes should also have been reverted for `servlet_compat_LeadingSlash_With_web.xml`. It shouldn't change the outcome of the test (which is excluded anyway) but I think the intention of the test is that this should use the 2.2 DTD.

The purpose of the other tests also looks to be testing compatibility of 2.2 DTDs in various scenarios. I don't think changing the deployment descriptor was correct there either.

These TCK tests are testing optional functionality. The changes made means the tests aren't performing the tests as intended. I think that is incorrect. If there is optional functionality there needs to be optional TCK tests OR these tests should be completely removed. I think leaving these tests in their current state is just going to cause confusion later as the current code comments are now not consistent with the test behaviour.

I'm not going to object to the release of a 6.0.2 Servlet TCK since:
- the change from a 2.2 DTD to a 5.0 schema for `servlet_compat_LeadingSlash_With_web.xml` won't break the test
- the other changes don't impact the Servlet TCK

but I do want to register my view that I think these changes are incorrect.

**Comment by scottmarlow** [comment]
Thanks @markt-asf!  sounds like this draft pr should be closed and that a new Platform issue should be opened for the next Jakarta EE 10 Platform TCK update to re-examine why these tests aren't optional.

**Pull request closed without merging**
