### PR TITLE
Jakarta WS Metadata 3.0

### PR DESCRIPTION
**Pull request by lukasj**
## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of wombat-spec-x.y.pdf
- [x] Specification HTML in the form of wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
N/A
- [x] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [x] Updated release record
   - [x] Generated IP Log
   - [x] Email to PMC
   - [x] Start release review by emailing EMO
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/jws/jakarta.jws-api/3.0.0/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-xml-ws-tck-3.0.0.zip
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/jws-api/issues/75, https://github.com/eclipse-ee4j/jws-api/issues/74
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

### CODE REVIEW

**Comment by ivargrimstad** [comment]
Here's the overall Checklist that we will use to help ensure that the specification is ready for ballot... The mentors should be ensuring that all of these items are in place. But, the project team is welcome to review this checklist as well to ensure that everything is in order. Thanks.

# Spec Review Checklist

1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta-{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] (Optional) Second PR for just apidocs

2. _index.md
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request
 
10. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Comment by ivargrimstad** [comment]
The TCK User's Guide included in the TCK zip is for Jakarta XML Web Services 2.3. Shouldn't it be 3.0?

**Comment by lukasj** [comment]
That's likely spread all over TCK's, can you file a bug at jakartaeetck project so they can fix it everywhere at once? Thx!

**Comment by ivargrimstad** [comment]
> That's likely spread all over TCK's, can you file a bug at jakartaeetck project so they can fix it everywhere at once? Thx!

Issue created for the TCK project: https://github.com/eclipse-ee4j/jakartaee-tck/issues/364

**Comment by edbratt** [comment]
I believe the preference is that the specification committer team submit PRs to update the TCK documentation in [jakartaee-tck](https://github.com/eclipse-ee4j/jakartaee-tck). For Jakarta RESTful Web Services, this will include:

- ReleaseNotes (I'd clone [this file](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jaxrs/docs/JAXRSTCK2.1-ReleaseNotes.html) and create a new file with the right version in the name and updated content), 
- [index.html](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jaxrs/docs/index.html), and
- the user-guide (source is [here](https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/user_guides/jaxrs/src/main/jbake/content), (You will need to update the copyright dates in the [footer](https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/user_guides/jaxrs/src/main/jbake/templates)))

Otherwise API teams may collaborate with someone in the Jakarta TCK committer team, but the API committer team is responsible for all documentation included in the specification, including the TCK documentation.

**Comment by m0mus** [comment]
@edbratt The links you posted are for JAXRS spec. Correct links are the same, but in `jaxws` directory.

**Comment by edbratt** [comment]
Apologies, they are corrected (I hope!).

**Comment by lukasj** [comment]
I believe this is ready now

**Comment by ivargrimstad** [comment]
Looks good. Can't see a PR to the Platform API though. It is currently included as 3.0.0-RC2 there.

**Review by ivargrimstad — APPROVED** [review]

**Comment by kwsutter** [comment]
Before I can vote on this Specification, I have a couple of questions...  @lukasj @ivargrimstad 

- On the CR and TCK Results, the compatible implementation link doesn't point at anything tangible.  There is no specific binary that is referenced that was used to test this Spec with the related TCK.  As we discussed on last week's Spec Committee call, even if it's a Snapshot driver, it needs to at least be in a location that will not go away in the future.  The text for the link seems to indicate there's an M5 driver somewhere, but I can't find one on the link provided (https://eclipse-ee4j.github.io/metro-jax-ws/index.html).

- The TCK link in the _index.md doesn't look to be correct.  Shouldn't the directory for the WS Metadata be "xml-web-services" instead of "xml-ws"?  Technically, I thought we were using the same name for the directory as in the actual file name, but I'm okay with abbreviating to "xml-ws" for that.  At the end of the day, we can promote it to whatever directory is necessary.  But, right now, there are different locations specified for the _index.md file as compared to the CR and TCK Results.

Thanks,
Kevin

**Comment by lukasj** [comment]
@kwsutter 

> * On the CR and TCK Results, the compatible implementation link doesn't point at anything tangible.  There is no specific binary that is referenced that was used to test this Spec with the related TCK.

~~https://jakarta.oss.sonatype.org/ returns 502 right now. How can we fix that?~~ Try again, download works for me know

At this point it is not possible to release the M5 implementation binary to public (in central) as it would be broken - bunch of dependencies are not available in central yet and it is still a big question when they will get there - this can vary somewhere between 2days (JAF, mail,..) and ~4 weeks (jaxb,..). Unless we can live with correct links and "temporarily broken" binaries.

>  As we discussed on last week's Spec Committee call, even if it's a Snapshot driver, it needs to at least be in a location that will not go away in the future.

This cannot be guaranteed for resources which are not under out direct control and AFAIK jakarta.oss.sonatype.org is not under our direct control.

In any case this version has been [tagged already](https://github.com/eclipse-ee4j/metro-jax-ws/releases/tag/3.0.0-M5), so if sth really bad would happen, there's a way to fix it.

>  The text for the link seems to indicate there's an M5 driver somewhere, but I can't find one on the link provided (https://eclipse-ee4j.github.io/metro-jax-ws/index.html).

- scroll down to the "Download Jakarta XML Web Services Milestone Release" section
- click on the "download" word in the "The latest milestone release of Jakarta XML Web Services is available for download as well as for consumption through maven." sentence (you'll get either HTTP 502 or the binary)
- see the Maven example section below this sentence, which mentions 3.0.0-M5 version


> * The TCK link in the _index.md doesn't look to be correct.  Shouldn't the directory for the WS Metadata be "xml-web-services" instead of "xml-ws"?

The directory in the _index should be [xml-web-services](https://download.eclipse.org/jakartaee/xml-web-services/) - do you want me to fix it immediately?

**Comment by kwsutter** [comment]
@lukasj Sorry to be a pain, but I think your link for the M5 driver needs to be more explicit. Your instructions in this PR were great and helped me.  But, we shouldn't have need extra instructions to find the download.  Even if you bookmarked the section for the Milestone driver and provided a link directly to that section, that would help.  I know it may be obvious to you, but it certainly wasn't obvious for the casual observer (me) to know where to find this M5 driver.  Thanks!

**Comment by lukasj** [comment]
@kwsutter I'd like to keep necessary overhead at the bare minimum as there has been already a lot of it and focus on finalizing other specs and implementations. The idea is that milestone builds will go away from that page (milestones will be linked from some other page, either directly from TCK results page or from some previous releases page) and the main "Download" link will be updated to lead to 3.0.0 once it's ready. But if you insist on this to be done now, I can do it for sure (here as well as in other ~2 projects)

**Comment by kwsutter** [comment]
> @kwsutter I'd like to keep necessary overhead at the bare minimum as there has been already a lot of it and focus on finalizing other specs and implementations. The idea is that milestone builds will go away from that page (milestones will be linked from some other page, either directly from TCK results page or from some previous releases page) and the main "Download" link will be updated to lead to 3.0.0 once it's ready. But if you insist on this to be done now, I can do it for sure (here as well as in other ~2 projects)

Hi @lukasj.  You've answered my other questions, so I'm going to go ahead with a +1.  But, I will also include a comment about CI link (similar to what has been documented in other PRs).  Thanks!

The other idea that was floated at today's Spec Committee was the idea to go back to all of these CRs and TCK Results that point at Snapshot or Milestone builds and update them with the final versions, especially for the Glassfish drivers since the full TCK bucket will be executed against GF before we can release.

**Comment by ivargrimstad** [comment]
* On ballot completion, the specification committee mentor:
 - [ ] adds this final checklist to the main PR.
 - [ ] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [ ] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
 - [ ] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [ ] creates an issue in the specification project that includes the following checklist for the specification project team:
 \<include url of Issue here>

**Pull request merged**
