### PR TITLE
Jakarta EE Web Profile 8 Specification

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

## Specification PR template
When creating a specification project release review, create two PRs with the content divided as follows.

Include the following in PR#1:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.  (use only a single digit for web profile)
- [x] Specification PDF in the form of wombat_x.y.pdf  (use only a single digit for web profile)
- [x] Specification HTML in the form of wombat_x.y.html  (use only a single digit for web profile)
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] For a Release Review, a summary that a Compatible Implementation
      is complete, passes the TCK, and that the TCK includes sufficient
      coverage of the specification. The TCK users guide MUST include
      the instructions to run the compatible implementations used to
      validate the release.  Instructions MAY be by reference.
- [x] The URL of the OSSRH staging repository for the api, javadoc:
https://oss.sonatype.org/content/repositories/staging/jakarta/platform/jakarta.jakartaee-web-api/8.0.0/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-jakartaeetck-8.0.0.zip
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/jakartaee-platform/issues/100

Include the following in PR#2:
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory.  (use only a single digit for web profile)

### CODE REVIEW

**Comment by bshannon** [comment]
Same comments as for #20 apply here.

**Comment by kwsutter** [comment]
Applied known changes per comments received on PR #20.  Still need to determine if we go with 8.0 or just 8 as the version number.

**Comment by dblevins** [comment]
Are we ok with these "Java EE" references or do we want them "Jakarta EE" and "Jakarta Security" respectively?

```
webprofile/8.0/WebProfile-spec-8.0.html:1063:<p>Java EE 8 Web Profile requires Java SE 8.</p>
webprofile/8.0/WebProfile-spec-8.0.html:1066:<p>Updated to reflect versions of Java EE 8
webprofile/8.0/WebProfile-spec-8.0.html:1141:<p>Added Java EE Security API 1.0 and JASPIC 1.1

```

**Comment by bshannon** [comment]
They should be fixed.  Please feel free to submit a PR.

**Comment by kwsutter** [comment]
> Are we ok with these "Java EE" references or do we want them "Jakarta EE" and "Jakarta Security" respectively?
> 
> ```
> webprofile/8.0/WebProfile-spec-8.0.html:1063:<p>Java EE 8 Web Profile requires Java SE 8.</p>
> webprofile/8.0/WebProfile-spec-8.0.html:1066:<p>Updated to reflect versions of Java EE 8
> webprofile/8.0/WebProfile-spec-8.0.html:1141:<p>Added Java EE Security API 1.0 and JASPIC 1.1
> ```

@dblevins, These references were in the Revision History for the Early Draft and Public Review Draft.  Since those drafts pre-dated Jakarta, I thought it was best to leave them as-is.  It's kind of a unique situation.  What do you think, @bshannon?

**Comment by bshannon** [comment]
@kwsutter I think I've commented on this before.  I think the revision history should be cleared and replaced by a history that describes what was done between the final Java EE 8 release and this final Jakarta EE 8 release.  That's the purpose of the revision history chapter.

**Comment by kwsutter** [comment]
# Spec Review Checklist

1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://oss.sonatype.org/conte/repositories/staging/jakarta/{spec}/jakarta-{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] Second PR for just apidocs

2. _index.md
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

**Comment by bshannon** [comment]
@kwsutter This PR should refer to the certification request in [issue #100](https://github.com/eclipse-ee4j/jakartaee-platform/issues/100).

**Comment by kwsutter** [comment]
> @kwsutter This PR should refer to the certification request in [issue #100](https://github.com/eclipse-ee4j/jakartaee-platform/issues/100).

Done!  Thanks.

**Comment by kwsutter** [comment]
* On ballot completion
 - [x] The designated specification committee representative adds this final checklist to the main PR.
 - [ ] The specification committee representative merges the specification and apidocs PRs.
 - [ ] The designated specification committee representative calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job.
 - [ ] The specification project member who created the staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [ ] The EMO updates the specification page with the ballot results.
This list goes on the committed spec index page.
 - [ ] The specification project team should go through the merged spec website page to verify all the links are valid.
 - [ ] The specification project team should approve the compatibility request.
 - [ ] The compatible implementation project/vendor MUST send an email tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [ ] The specification project team should merge any final release branch as appropriate for the branch management for the project.

**Pull request merged**
