### PR TITLE
ManagedBeans 2.0 release

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
- [x] Specification HTML in the form of jakarta-wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] N/A - For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
- [x] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [x] Updated release record
   - [x] Generated IP Log
   - [x] Email to PMC
   - [x] Start release review by emailing EMO
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      N/A - covered by [Annotation 2.0.0](https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/annotation/jakarta.annotation-api/2.0.0/)
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      N/A - covered by [Platform TCK](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.0.0.zip)
- [x] The URL of the compatibility certification request issue:
      [Glassfish Certification Request](https://github.com/eclipse-ee4j/jakartaee-platform/issues/258)
      [Managed Beans Certification Request](https://github.com/eclipse-ee4j/jakartaee-platform/issues/267)
- [x] N/A - Specification JavaDoc in the wombat/x.y/apidocs directory.
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by kwsutter** [comment]
Not quite ready for review yet, but I wanted to get the placeholder started.  Also, Scott Wang (Primeton) is listed as the mentor for this Spec, but he's not yet available in the system to assign the review to him...  Might need some assistance...  I'll put the initial Checklist into place and work from there...

**Comment by kwsutter** [comment]
# Spec Review Checklist

1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta.{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] (Optional) Second PR for just apidocs

2. _index.md
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request
 
10. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Comment by jeanouii** [comment]
Out of curiosity, why is this wombat managedbeans?
I was expecting managed-beans.

**Comment by kwsutter** [comment]
> Out of curiosity, why is this wombat managedbeans?
> I was expecting managed-beans.

Sorry, where are you finding "wombat managedbeans"?

**Comment by jeanouii** [comment]
> > Out of curiosity, why is this wombat managedbeans?
> > I was expecting managed-beans.
> 
> Sorry, where are you finding "wombat managedbeans"?

Sorry, I wasn't clear ...

In the template, we can see wombat for the spec name basically.
For most of the other specification like bean-validation, enterprise-beans, we use have an hyphen where as here we have managedbeans. I was expecting managed-beans.

Sorry again

**Comment by starksm64** [comment]
I added myself as the mentor in the assignments list.

**Comment by kwsutter** [comment]
> In the template, we can see wombat for the spec name basically.
> For most of the other specification like bean-validation, enterprise-beans, we use have an hyphen where as here we have managedbeans. I was expecting managed-beans.

Now I see what you mean.  I was just following the convention that we put in place for Managed Beans in Jakarta EE 8.  But, the file name for the spec could easily be updated to managed-beans.  I'll do that.  Thanks!

**Comment by kwsutter** [comment]
@starksm64 This one is closer to being ready for review.  It is still dependent on Glassfish for the CR, and it needs the Platform TCK, but the rest of it should be ready.  It's also dependent on Annotations 2.0, but we're getting close to starting a ballot on that one as well.  Thanks!

**Comment by starksm64** [comment]
The deployed site preview links to spec docs are resulting in 404 errors.  I can view the files from the PR, but the preview is not working for those links.

The issue is that the links on the pages use a name like jakarta-managedbeans-spec-2.0.html, but the file is named jakarta-managed-beans-spec-2.0.html

side by side comparison:
jakarta-managedbeans-spec-2.0.html
jakarta-managed-beans-spec-2.0.html

Note the dash between managed and beans in the file name.

**Comment by kwsutter** [comment]
> The deployed site preview links to spec docs are resulting in 404 errors. I can view the files from the PR, but the preview is not working for those links.
> 

:-) Doh!  I should have caught that.  I made the updates based on the comments from @jeanouii and I forget to modify the links themselves. Sorry about that...

**Comment by kwsutter** [comment]
@starksm64 Per our Spec Committee call this week, we decided that Specs dependent on the final Platform TCK and Glassfish could go forward with their ballots early.  This would help alleviate the big push at the end (6 Specs in the last two weeks).  And, it's relatively safe since we can't release Jakarta EE 9 until the Platform specs, TCK, and CI are complete and approved.  We will need to go back and update the CR reference after the ballot is done, but otherwise, this Spec PR should be ready to go.

I am referencing a "historical" version of the TCK to do the TCK file checks.

If you are comfortable with this approach, then please do a final review, approval, and start the ballot.  Thanks!

**Comment by scottmarlow** [comment]
FYI, the RC1 Platform TCK link is https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.0.0-RC1.zip which has the same SHA `75b2493a117e7f8fe775cc7e2e8a605a203611895091f4bb9aaabed57f813392` as was used [to pass 100% of the Full Platform TCK yesterday](https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1165) (we are running again due to a system networking failure that occurred after the test run while collecting test results).  The [Jakarta EE 9 TCK results wiki page](https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Jakarta-EE-9-TCK-results) will be updated after the run completes, not that you need to wait since I said, we already passed 100%.

[We also passed the Web Profile tests as well!](https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-certification-web/19/junit-reports-with-handlebars/testSuitesOverview.html).

This testing was done with https://download.eclipse.org/ee4j/glassfish/glassfish-6.0.0-RC2.zip.

**Comment by kwsutter** [comment]
@starksm64 I believe this one is ready for ballot.  I have referenced the CR for the Platform, which references Glassfish 6.0 RC2 along with the Platform TCK 9.0 RC1.

**Comment by kwsutter** [comment]
On the Spec Committee call today, @edbratt volunteered to help the Scotts out and take a look at this PR to see if it's ready for ballot.  Thanks!

**Comment by m0mus** [comment]
The spec pdf has some unfilled variables:
```
All existing copyright notices, or if one does not exist, a notice (hypertext is preferred, but a textualrepresentation  is  permitted)
 of  the  form:  "Copyright  (c)  [$date-of-document]  Eclipse  Foundation,Inc. <<url to this license>>"
```

**Review by edbratt — APPROVED** [review]
The pre-ballot checklist appears to be complete. Please review the comment left by @m0mus and decide if the Spec. doc. needs to be updated for this. I realize there has been some confusion about what to do with those URL/URIs. Otherwise, to me, it looks good to go. If @starksm64 isn't around, I think we can proceed to ballot after you decide that.

**Comment by kwsutter** [comment]
> The spec pdf has some unfilled variables like
> 
> ```
> All existing copyright notices, or if one does not exist, a notice (hypertext is preferred, but a textualrepresentation  is  permitted)
>  of  the  form:  "Copyright  (c)  [$date-of-document]  Eclipse  Foundation,Inc. <<url to this license>>"
> ```
> 
> and
> 
> ```
> "Copyright  (c)  [$date-of-document]  Eclipse  Foundation.  This  software  or  document  includes  
> materialcopied from or derived from [title and URI of the Eclipse Foundation specification document]."
> ```

As @edbratt pointed out, there was confusion as to whether these variables needed to be replaced or not.  In the end, we were instructed not to change anything associated with the EFSL.  All of the variables should be left as variables.

**Comment by kwsutter** [comment]
> The pre-ballot checklist appears to be complete. Please review the comment left by @m0mus and decide if the Spec. doc. needs to be updated for this. I realize there has been some confusion about what to do with those URL/URIs. Otherwise, to me, it looks good to go. If @starksm64 isn't around, I think we can proceed to ballot after you decide that.

I replied to @m0mus's comment.  I think we're good and the vote can be started by either yourself or @starksm64.  Thanks!

**Comment by edbratt** [comment]
I coordinated with @starksm64 and I'll initiate the ballot in a few minutes.

> 
> 
> > The pre-ballot checklist appears to be complete. Please review the comment left by @m0mus and decide if the Spec. doc. needs to be updated for this. I realize there has been some confusion about what to do with those URL/URIs. Otherwise, to me, it looks good to go. If @starksm64 isn't around, I think we can proceed to ballot after you decide that.
> 
> I replied to @m0mus's comment. I think we're good and the vote can be started by either yourself or @starksm64. Thanks!

I coordinated with @starksm64 and I'll initiate the ballot in a few minutes.

**Comment by edbratt** [comment]
Ballot thread: https://www.eclipse.org/lists/jakarta.ee-spec/msg01267.html

**Comment by kwsutter** [comment]
Per the Spec Committee meeting on 11/11, I updated the reference to the TCK to be without the "-RC1".  Since the same SHA values exist for both versions, this was deemed an acceptable and expected update.

**Comment by starksm64** [comment]
* On ballot completion, the specification committee mentor:
 - [x] adds this final checklist to the main PR.
 - [ ] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [ ] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
 - [ ] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [ ] creates an issue in the specification project that includes the following checklist for the specification project team:
 \<include url of Issue here>

**Comment by starksm64** [comment]
Representative | Representative for: | Vote
-- | -- | --
Kenji Kazumura | Fujitsu | +1
Dan Bandera, Kevin Sutter | IBM | +1
Ed Bratt, Dmitry Kornilov | Oracle | +1
Andrew Pielage, Matt Gill | Payara | +1
Scott Stark, Mark Little | Red Hat | +1
David Blevins, Jean-Louis Monteiro | Tomitribe | +1
Ivar Grimstad | EE4J PMC | +1
Marcelo Ancelmo, Martijn Verburg | Participant Members | +1
Werner Keil | Committer Members | +1
Scott (Congquan) Wang | Enterprise Members | +1
  | Total | 10

**Pull request merged**
