### PR TITLE
Jakarta Server Faces 2.3

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

## Specification PR template
When creating a specification project release review, create two PRs with the content divided as follows.

Include the following in PR#1:
- [X] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [X] Specification PDF in the form of wombat_x.y.pdf
- [X] Specification HTML in the form of wombat_x.y.html
- [X] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [X] For a Progress Review, that sufficient progress has been made on
      a Compatible Implementation and TCK, to ensure that the spec is
      implementable and testable.
- [X] For a Release Review, a summary that a Compatible Implementation
      is complete, passes the TCK, and that the TCK includes sufficient
      coverage of the specification. The TCK users guide MUST include
      the instructions to run the compatible implementations used to
      validate the release.  Instructions MAY be by reference.
- [X] The URL of the OSSRH staging repository for the api, javadoc:
      https://oss.sonatype.org/content/repositories/staging/jakarta/faces/jakarta.faces-api/2.3.2/
- [X] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-faces-tck-2.3.0.zip
- [X] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/faces-api/issues/1475

### CODE REVIEW

**Comment by smillidge** [comment]
api jar doesn't include NOTICE and LICENSE files in the Manifest.

**Comment by arjantijms** [comment]
@smillidge 
> api jar doesn't include NOTICE and LICENSE files in the Manifest.

Good catch Steve, thx! Updated it right away. 

* Commit: https://github.com/eclipse-ee4j/faces-api/commit/a3898269fcf57c348dcfa08ad3d312972e4fd7b6
* Restaged: https://ci.eclipse.org/faces/job/1_faces-build-and-stage/5/consoleText

**Comment by NottyCode** [comment]
# Spec Review Checklist

1. Spec PR
  - [x] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [x] Directory of form {spec}/x.y
  - [x] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [x] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [x] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [x] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [x] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [x] Staging repository link of the form https://oss.sonatype.org/conte/repositories/staging/jakarta/{spec}/jakarta-{spec}-api/x.y.z/
  - [x] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [x] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [x] Second PR for just apidocs

2. _index.md
  - [x] Link to spec pdf
  - [x] Link to spec html
  - [x] Link to apidocs
  - [x] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [x] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [x] Name of and link to at least one Compatible Implementation

3. javadocs
  - [x] Footer contains Eclipse copyright and link to license
  - [x] ESFL license is included, usually as doc-files/speclicense.html
  - [x] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [x] Correct spec title
  - [x] Version number of the form x.y, not x.y.z
  - [x] Correct Eclipse copyright line
  - [x] No DRAFT or SNAPSHOT
  - [x] Correct Logo

5. Spec HTML
  - [x] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [x] EFTL license file, preferably named LICENSE.md
  - [x] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [x] Software requirements listed
  - [x] Installation and configuration described
  - [x] How to run tests
  - [x] Where to file challenges

8. Compatibility certification request
  - [x] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [x] Request issue has `certification` label.

9. TCK results summary
  - [x] Page is hosted by Compatible Implementation project
  - [x] Includes all information from certification request
  - [x] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

**Comment by NottyCode** [comment]
I found a small number of issues:

1. I couldn't find the instructions for running it against the CI linked in here. I can find instructions for running against a CI of my choice, or another vendor CI, but I'd been interpreting this step of the checklist relative to the CI listed in this PR.
1. The TCK certification link lists this SHA has `db9a385010cd8544bc1f2468a1fbcaca16f14014fa341e5343c487616f8670dc` but when I run `shasum -a 256` on the downloaded tck zip I get this `77375ad39f8b736034dbfd554152bbd3e3931a9c9ef1760049c60c5fa87a06d9`

**Comment by arjantijms** [comment]
@NottyCode 

Thanks for the feedback! You are right about running it, it's not fully trivial. The Faces and Mojarra projects are aware that this is an issue.

I'm not 100% were I should exactly put the instructions and what the format is. @bshannon ?

The short of it is as follows:

1. Build and stage Mojarra using https://jenkins.eclipse.org/mojarra/job/1_mojarra-build-and-stage
2. Run the TCK against the staged build using https://jenkins.eclipse.org/mojarra/job/2_mojarra-run-tck-against-staged-build/
3. Extract and stage the API from the Mojarra build that was staged and passed the TCK using https://ci.eclipse.org/faces/job/1_faces-build-and-stage

We're fully aware that "Extract the API from the Mojarra build" is non-intuitive, and it will be a priority going forward to separate out the API properly into the API project.

I'm going to re-run the TCK and will post the SHA that was actually used during the test to address your second point. Thanks again!

**Comment by arjantijms** [comment]
@NottyCode 

TCK now running with artefacts:

* **SHA256_GF**=_SHA256(/home/jenkins/workspace/2_mojarra-run-tck-against-staged-build/download/glassfish.zip)=_ 26f3fa6463d24c5ed3956e4cab24a97e834ca37d7a23d341aadaa78d9e0093ce
* **SHA256_API**=_SHA256(/home/jenkins/workspace/2_mojarra-run-tck-against-staged-build/download/jakarta.faces.jar)=_ 4b8a7b1e91154dcbbbdc952fa599a9071370aad5ce6a377b3c2eacef7972a319
* **SHA256_TCK**_=SHA256(/home/jenkins/workspace/2_mojarra-run-tck-against-staged-build/download/facestck.zip)=_ 77375ad39f8b736034dbfd554152bbd3e3931a9c9ef1760049c60c5fa87a06d9

**Comment by arjantijms** [comment]
TCK passed using the above SHAs: https://jenkins.eclipse.org/mojarra/view/Release/job/2_mojarra-run-tck-against-staged-build/4/consoleText

I'll update the SHA.

**Comment by bshannon** [comment]
> @NottyCode
> 
> Thanks for the feedback! You are right about running it, it's not fully trivial. The Faces and Mojarra projects are aware that this is an issue.
> 
> I'm not 100% were I should exactly put the instructions and what the format is. @bshannon ?

The instructions are supposed to be in the TCK Users Guide [here](https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/user_guides/jsf/src/main/jbake/content), in the config chapter.
Looks like the implementation-specific instructions were lost in the conversion to AsciiDoc.
Let me see if I can add them back manually...

**Comment by starksm64** [comment]
The https://eclipse-ee4j.github.io/mojarra/certifications/jakarta-faces/2.3/TCK-Results still has the old SHA rather than 77375ad39f8b736034dbfd554152bbd3e3931a9c9ef1760049c60c5fa87a06d9

**Comment by kwsutter** [comment]
@arjantijms Could you also file a PR for updating jakartaee-api pom.xml with the proper Jakarta Faces API version (2.3.2?).  Thanks!

**Comment by kwsutter** [comment]
> @arjantijms Could you also file a PR for updating jakartaee-api pom.xml with the proper Jakarta Faces API version (2.3.2?). Thanks!
> 
> https://github.com/eclipse-ee4j/jakartaee-api/pulls

Never mind.  If you are good with the 2.3.2 version, I have updated the pom in jakartaee-api for you via [PR #34](https://github.com/eclipse-ee4j/jakartaee-api/pull/34).  If you decide on an alternate version, then please submit another PR.  Thank you.

**Comment by arjantijms** [comment]
> Never mind. If you are good with the 2.3.2 version, I have updated the pom in jakartaee-api for you via PR #34. 

Thanks Kevin! 2.3.2 should be perfect. I'm still working on the Authorization updates, and when that is done move back to Faces to address the remaining issues here.

Note to self and others:

As an exception this project also needs additional artefacts published, such as the VDL docs.

**Comment by arjantijms** [comment]
@starksm64 
> The https://eclipse-ee4j.github.io/mojarra/certifications/jakarta-faces/2.3/TCK-Results still has the old SHA rather than 77375ad39f8b736034dbfd554152bbd3e3931a9c9ef1760049c60c5fa87a06d9

Fixed! Thanks.

**Comment by arjantijms** [comment]
@NottyCode 
> 2. The TCK certification link lists this SHA has `db9a385010cd8544bc1f2468a1fbcaca16f14014fa341e5343c487616f8670dc` but when I run `shasum -a 256` on the downloaded tck zip I get this `77375ad39f8b736034dbfd554152bbd3e3931a9c9ef1760049c60c5fa87a06d9`

Should now be fixed, can you check again and if correct set the checkboxes? Thx!

**Comment by bshannon** [comment]
* On ballot completion
 - [ ] The designated specification committee representative adds this final checklist to the main PR.
 - [ ] The specification committee representative merges the specification and apidocs PRs.
 - [ ] The designated specification committee representative calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job.
 - [ ] The specification project member who created the staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [ ] The EMO updates the specification page with the ballot results.
This list goes on the committed spec index page.
 - [ ] The specification project team should go through the merged spec website page to verify all the links are valid.
 - [ ] The specification project team should approve the compatibility request.
 - [ ] The compatible implementation project/vendor MUST send an email tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [ ] The specification project team should merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
Final release branch PR: https://github.com/eclipse-ee4j/faces-api/pull/1478

**Comment by arjantijms** [comment]
Mail sent

**Comment by bshannon** [comment]
@arjantijms  Looks like the API jar file hasn't been released.

**Comment by arjantijms** [comment]
@bshannon you're right, but it's there now:

https://repo1.maven.org/maven2/jakarta/faces/jakarta.faces-api/2.3.2/

Thx!

**Pull request merged**
