### PR TITLE
Update Jakarta NoSQL 1.0.0-M1 

### PR DESCRIPTION
**Pull request by otaviojava**
# Context

Update Jakarta NoSQL 1.0.0-M1 that enhances documentation.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of wombat-spec-x.y.pdf
- [x] Specification HTML in the form of wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md

### CODE REVIEW

**Comment by otaviojava** [comment]
@ivargrimstad 
Could you help with this?
It looks like an issue at Jakarta Faces specification.

````
6:45:04 AM:   Resolved config
6:45:04 AM:   build:
6:45:04 AM:     command: ./build.sh && cd website && npm run disallow_robots_txt && hugo --buildFuture -b $DEPLOY_PRIME_URL
6:45:04 AM:     commandOrigin: config
6:45:04 AM:     environment:
6:45:04 AM:       - REVIEW_ID
6:45:04 AM:       - NODE_VERSION
6:45:04 AM:       - HUGO_VERSION
6:45:04 AM:     publish: /opt/build/repo/website/public
6:45:04 AM:     publishOrigin: config
6:45:04 AM:   headers:
6:45:04 AM:     - for: /specifications/faces/3.0/jakarta-faces-3.0.html
6:45:04 AM:       values:
6:45:04 AM:         Link: <[https://jakarta.ee/specifications/faces/3.0/jakarta-faces-3.0>;](https://jakarta.ee/specifications/faces/3.0/jakarta-faces-3.0%3E;) rel="canonical"
6:45:04 AM:     - for: /specifications/faces/3.0/jakarta-faces-3.0
6:45:04 AM:       values:
6:45:04 AM:         Link: <[https://jakarta.ee/specifications/faces/3.0/jakarta-faces-3.0>;](https://jakarta.ee/specifications/faces/3.0/jakarta-faces-3.0%3E;) rel="canonical"
6:45:05 AM: Failed during stage "building site": Build script returned non-zero exit code: 2
6:45:05 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
6:45:05 AM: Failing build: Failed to build site
```

**Comment by ivargrimstad** [comment]
> @ivargrimstad Could you help with this? It looks like an issue at Jakarta Faces specification.
> 
> ```
> 6:45:04 AM:   Resolved config
> 6:45:04 AM:   build:
> 6:45:04 AM:     command: ./build.sh && cd website && npm run disallow_robots_txt && hugo --buildFuture -b $DEPLOY_PRIME_URL
> 6:45:04 AM:     commandOrigin: config
> 6:45:04 AM:     environment:
> 6:45:04 AM:       - REVIEW_ID
> 6:45:04 AM:       - NODE_VERSION
> 6:45:04 AM:       - HUGO_VERSION
> 6:45:04 AM:     publish: /opt/build/repo/website/public
> 6:45:04 AM:     publishOrigin: config
> 6:45:04 AM:   headers:
> 6:45:04 AM:     - for: /specifications/faces/3.0/jakarta-faces-3.0.html
> 6:45:04 AM:       values:
> 6:45:04 AM:         Link: <[https://jakarta.ee/specifications/faces/3.0/jakarta-faces-3.0>;](https://jakarta.ee/specifications/faces/3.0/jakarta-faces-3.0%3E;) rel="canonical"
> 6:45:04 AM:     - for: /specifications/faces/3.0/jakarta-faces-3.0
> 6:45:04 AM:       values:
> 6:45:04 AM:         Link: <[https://jakarta.ee/specifications/faces/3.0/jakarta-faces-3.0>;](https://jakarta.ee/specifications/faces/3.0/jakarta-faces-3.0%3E;) rel="canonical"
> 6:45:05 AM: Failed during stage "building site": Build script returned non-zero exit code: 2
> 6:45:05 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
> 6:45:05 AM: Failing build: Failed to build site
> ```
> ```

My guess is that it is just a hickup of Netlify.

**Review by ivargrimstad — CHANGES_REQUESTED** [review]
This PR should only update the nosql/1.0 directory.
Please remove the updates to data/1.0 (javadoc)

**Comment by otaviojava** [comment]
> This PR should only update the nosql/1.0 directory. Please remove the updates to data/1.0 (javadoc)

ouch, my bad. Fixing it.

**Comment by otaviojava** [comment]
@ivargrimstad done.

**Review by ivargrimstad — APPROVED** [review]

**Pull request merged**
