### PR TITLE
Jakarta Mail 2.1 spec

### PR DESCRIPTION
**Pull request by lukasj**
## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
- [x] Specification HTML in the form of jakarta-wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [ ] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
- [x] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [x] Updated release record
   - [x] Generated IP Log
   - [x] Email to PMC
   - [x] Start release review by emailing EMO 
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/mail/jakarta.mail-api/2.1.0/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-mail-tck-2.1.0.zip
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/mail/issues/593
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by lukasj** [comment]
this is now ready for the review

**Comment by Pandrex247** [comment]
Should the compatibility certification request not link to a specific version of Angus Mail? It currently gives no details about which version is being used and links to the master branch.

**Comment by lukasj** [comment]
link should be updated

**Comment by Pandrex247** [comment]
1. Spec PR
  - [x] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [x] Directory of form {spec}/x.y
  - [x] PDF of form jakarta-{spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [x] HTML of form jakarta-{spec}-spec-x.y.html ("-spec" preferred but not required)
  - [x] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [x] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [x] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [x] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta.{spec}-api/x.y.z/
  - [x] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [x] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] (Optional) Second PR for just apidocs

2. _index.md
  - [x] Link to project release plan of the form https://projects.eclipse.org/projects/ee4j.{spec}/releases/x.y/plan
  - [x] Link to spec pdf
  - [x] Link to spec html
  - [x] Link to apidocs
  - [x] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip (The folder path is required, the file name pattern is preferred.)
  - [x] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [x] Name of and link to at least one Compatible Implementation

3. javadocs
  - [x] Footer contains Eclipse copyright and link to license
  - [x] ESFL license is included, usually as doc-files/speclicense.html
  - [x] no META-INF directory in PR
  - [x] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [x] Correct spec title
  - [x] Version number of the form x.y, not x.y.z
  - [x] Correct Eclipse copyright line
  - [x] No DRAFT or SNAPSHOT
  - [x] Correct Logo

5. Spec HTML
  - [x] Same as PDF

6. TCK zip file
  - [x] README file (optional for this release)
  - [x] EFTL license file, preferably named LICENSE.md
  - [x] User's Guide (or equivalent documentation)
  - [x] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [x] Software requirements listed
  - [x] Installation and configuration described
  - [x] How to run tests
  - [x] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [x] Request issue has `certification` label.

9. TCK results summary
  - [x] Page is hosted by Compatible Implementation project
  - [x] Includes all information from certification request
  - [x] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

10. If a Release Review is required, the specification project team contacts the EMO to initiate the review by sending an email to emo@eclipse.org.
    (A Release Review is not required if the current release is a Service Release based on a previously successful Major or Minor
    release as indicated by a release record on the project's Releases page, e.g., the [Jakarta Servlet releases page](https://projects.eclipse.org/projects/ee4j.servlet/reviews).)
    - [x] An issue will be created by the EMO to track the release review.
    - [x] The specification project team requests approval for the release from the PMC by sending an email to ee4j-pmc@eclipse.org.
    - [x] The specification project team then delivers an IP Log to the IP Team for their review as described in https://www.eclipse.org/projects/handbook/#pmi-commands-iplog.

11. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Comment by Pandrex247** [comment]
The [compatibility certification request issue](https://github.com/eclipse-ee4j/mail/issues/593) falls afoul of the same comment as above - it's pointing to the master branch and not specifying that it's Angus Mail 1.0.

The SHA of the TCK uploaded to staging also doesn't seem to match that given on said issue.
```
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-mail-tck-2.1.0-tckinfo.txt
SHA256SUM: 6f02a92e0a5ef60260e65f95938cc566da2f93a3d269c3b321da0d787a3448a5

https://github.com/eclipse-ee4j/mail/issues/593
SHA-256: 56033d9ae33d5ffd9c70e29fb93bea1082fe14e2c04bcefdbc9b0335b76c1fd1
```

**Comment by lukasj** [comment]
should be fixed

**Comment by Pandrex247** [comment]
- [ ] Adds the approved label to the PRs, and sends out the Ballot Summary per this [template](https://github.com/jakartaee/specification-committee/blob/master/spec_finalization_checklist.md#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](https://github.com/jakartaee/specification-committee/blob/master/jakarta.ee-spec@eclipse.org)
- [ ] Calculates the staged EFTL TCK signature and promotes it to the committee download area using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
- [ ] Merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
- [ ] Updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
- [ ] Notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](https://github.com/jakartaee/specification-committee/blob/master/emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
- [ ] Creates an issue in the specification project that includes the following checklist for the specification project team:

**Review by Pandrex247 — APPROVED** [review]

**Comment by Pandrex247** [comment]
> Merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.

This is currently marked as `2021-04-15` - is this correct? It seems quite a while ago now and more in line with when then the _Plan_ was done. Should it not be something closer to `2021-11-03`?

**Comment by ivargrimstad** [comment]
> > Merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
> 
> This is currently marked as `2021-04-15` - is this correct? It seems quite a while ago now and more in line with when then the _Plan_ was done. Should it not be something closer to `2021-11-03`?

It doesn't really matter as long as the date is before today. It is the publish date for the file to show on the web, so the date around plan review is actually correct since that is when the page was first displayed.

**Pull request merged**
