### PR TITLE
XML Web Services 3.0.1 (SR)

### PR DESCRIPTION
**Pull request by lukasj**
## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
  N/A
- [ ] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
  N/A
- [ ] Specification HTML in the form of jakarta-wombat-spec-x.y.html
  N/A
- [ ] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
  N/A
- [ ] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
  N/A
- [ ] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [ ] Updated release record
   - [ ] Generated IP Log
   - [ ] Email to PMC
   - [ ] Start release review by emailing EMO 
  N/A
- [x] For a [Service Release Review](https://jakarta.ee/committees/specification/operations/#creating_a_final_service_release_specification)
   - [x] Updated release record
   https://projects.eclipse.org/projects/ee4j.jaxws/releases/3.0.1-jakarta-xml-web-services
   - [x] Add Change Log
   - [ ] Start release review by emailing Specification Committee
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/xml/ws/jakarta.xml.ws-api/3.0.1/
- [ ] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
  N/A
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/jax-ws-api/issues/163
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by kwsutter** [comment]
A more condensed PR template checklist is being worked via PR #345.  Just an FYI...  Also, I just assigned @edbratt and @m0mus as mentors for this Service Release issue.

**Review by m0mus — APPROVED** [review]
LGTM

**Comment by lukasj** [comment]
the process states:
> After the Specification PRs are reviewed and approved by independent specification committee members, the PRs can be merged. The Specification Project team can then release the staged artifacts to Maven Central.

which implies that the binary cannot be published before this gets merged. Would be great to know, if there is anything I can do to speed things up. Thanks.

**Comment by kwsutter** [comment]
Thanks, @m0mus and @lukasj!

**Pull request merged**
