### PR TITLE
Concurrency 3.1 plan

### PR DESCRIPTION
**Pull request by njr-11**
Plan Review PR Template
When creating a specification project plan review, create PRs with the content defined as follows.

Include the following in the PR:

- [x]  A directory in the form wombat/x.y where x.y is the release major.minor version.
- [x] An index page wombat/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
- [x] Spec. Page Title should be on the form "Jakarta Wombat X.Y (under development)"
- [x] Includes a plan for the release. Usually, a couple of statements is enough. Otherwise, a link to a document describing the release.
- [x] Includes a detailed description of any backward incompatibility (Mark with N/A and check if none)
- [x] Declares optional features if there are any (Mark with N/A and check if none)
- [x] Includes minimum Java SE version
- [x] Describe any updates or required changes including splitting out the TCK (Mark with N/A and check if not planned)
- [x] Link to updated release record

### CODE REVIEW

**Comment by edbratt** [comment]
I hope it's okay, I replaced the initial commit description with the Plan Review template (we can check off many more tasks that way).

**Comment by edbratt** [comment]
1. Spec PR for Plan / Proposal
  - [x] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [x] Directory of form {spec}/x.y
  - [x] (Optional) PDF of form jakarta-{spec}-spec-x.y.pdf ("-spec" preferred but not required) -- NA
  - [x] (Optional) HTML of form jakarta-{spec}-spec-x.y.html ("-spec" preferred but not required) -- NA
  - [x] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [x] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [x] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)

2. _index.md
  - [x] Link to project PMI plan of the form https://projects.eclipse.org/projects/ee4j.{spec}/releases/x.y/plan
  - [x] Scope statement changes -- This might be any of
    * Revised specification document, possibly with markup indicating changes
    * Short description of proposed changes
    * List of issues 
        * If many issues are involved consider using an epic (issue of issues) and only provide high-level summary. 
    * If the version update includes material that is outside the original scope, (i.e. if a feature were to be refactored to another specification or if some major additional functionality is proposed), this should be highlighted.
  - [x] High-level Plan -- If intended to align with a more broad release (i.e. Jakarta EE major release) reference that plan (or plan body). Indicate the milestones intended for *this* specification update (any planned checkpoints: feature complete, code complete, TCK complete, target ballot date). 
  - [ ] How to communicate with the Specification committer team (team list, issue tracker, etc.)
  - [ ] Any additional requirements or details that would be necessary to complete this specification (dependencies, resource requirements, etc.)

3. Proposed Spec PDF (Optional) -- Not included with initial Plan
  - [ ] Correct spec title, clearly marked preliminary -- NA
  - [ ] Correct Eclipse copyright line -- NA
  - [ ] Must indicate DRAFT or SNAPSHOT -- NA
  - [ ] Correct Logo -- NA

4. Proposed Spec HTML (Optional) -- Not included
  - [ ] Same as PDF -- NA

5. TCK
  - [x] Brief outline describing how TCK will be developed.
  - [ ] Name or list of target implementation partners

6. EMO Requirements 
    TBD
    - [ ] An issue will be created by the EMO to track the release review.

**Comment by edbratt** [comment]
I apologize for the delay reviewing this PR.

I would recommend the following, to facilitate approval:

The list of features/changes, would be improved by including issues IDs. I don't feel qualified to make these changes but it appears this might be a good starting point:

- Integration with Java 21 Virtual Threads, [Support Loom Virtual Threads](https://github.com/jakartaee/concurrency/issues/268), [Interoperability with Structured Concurrency](https://github.com/jakartaee/concurrency/issues/272)
- Java Flow/ReactiveStreams and context propagation, [Support Java 9 Flow and ReactiveStream](https://github.com/jakartaee/concurrency/issues/257)
- Replace more features from EJB, such as Schedule and Lock annotations, [De-empasise EJB, JNDI, Resource-refs, etc. ...](https://github.com/jakartaee/concurrency/issues/252)
- Become more CDI-centric, [Concurrency Dependency Issues](https://github.com/jakartaee/concurrency/issues/234)
- Specification bug fixes and clarifications, [Context Service chapter not updated in Specification](https://github.com/jakartaee/concurrency/issues/233)
- TCK fixes and enhancements, [TCK Improvements for 3.1](https://github.com/jakartaee/concurrency/issues/269)
 
According to the mentor checklist, the page is improved by including, how to contact the team. You might consider adding:

Community input is encouraged. Your comments to the issues (or on any Concurrency Issue in our [issue tracker](https://github.com/jakartaee/specifications/issues)) or you may join the Concurrency Developer mailing by clicking the subscribe button on [this page](https://accounts.eclipse.org/mailing-list/cu-dev).

The mentor checklist asks when Milestone releases will be available -- I presume this means something like a candidate build that other projects or community members could use to assess/work with the proposed changes. Do you have any estimates for that yet?

Once we have agreed if we will make these changes, we can start.

**Review by edbratt — CHANGES_REQUESTED** [review]
Please see comments in 'conversation'

**Comment by edbratt** [comment]
This is an informative comment -- 
The mentor should remind the specification committer team of the various process requirements and also the support that is available from the various committees. This can be done via e-mail or a face-to-face meeting as appropriate.
  - [ ] Pointers to various written resources (such as [Specification Process Guide](https://jakarta.ee/committees/specification/guide/), [TCK Process Guide](https://jakarta.ee/committees/specification/tckprocess/), Eclipse Developement Process, etc.)
  - [ ] Remind the team that the EFSP requires at least one checkpoint update every twelve months. 
  - [ ] Progress Reviews may be required as requested by the Specification committee. 
  - [ ] Remind the team they are obligated to inform the Specification Committee if their work requires evolution to the plan (major features in or out) and/or any significant changes to checkpoint targets.
  - [ ] Remind team of the IP review process for all new, and changes to existing, third party requirements
  - [ ] Remind the team of the community building resources available from the various committees. Some examples
    * Community outreach and involvement through Marketing committee venues and [jakarta.ee](https://jakarta.ee)
        * [What's New, News](https://jakarta.ee/news/)
        * [Community Announcements](https://jakarta.ee/news/?news-type=community_news)
        * [Community Events](https://jakarta.ee/community/events/)
    * Resource allocation assistance (e.g. additional CI/CD resources anticipated, etc.) from Steering committee
    * General process help from the Specification Committee, etc.)
    * General technical guidance, advice, feedback, review from the Platform Committer team, etc. 
 
Lastly, you are welcome to join any of the weekly Platform Committer team meetings, Tuesday's at 8 AM Pacific. See the [Jakarta EE Working Group Calendar](https://calendar.google.com/calendar/embed?src=eclipse-foundation.org_e9ki8t2gc75sh07qdh95c8ofvc%40group.calendar.google.com) for specific details.

**Comment by njr-11** [comment]
> The list of features/changes, would be improved by including issues IDs.

Good idea. I added links.

> According to the mentor checklist, the page is improved by including, how to contact the team.

I added this as well.

> The mentor checklist asks when Milestone releases will be available -- I presume this means something like a candidate build that other projects or community members could use to assess/work with the proposed changes. Do you have any estimates for that yet?

I'm not the spec lead, just one of the committers helping with getting the plan created, and no, I can't estimate that on behalf of all the other spec participants.

**Comment by edbratt** [comment]
Thanks! Looks good to go. I will start the ballot.

**Review by edbratt — APPROVED** [review]
Requested updates have been added. Will start ballot

**Pull request merged**
