### PR TITLE
Jakarta XML Binding 3.0

### PR DESCRIPTION
**Pull request by lukasj**
## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of wombat-spec-x.y.pdf
- [x] Specification HTML in the form of wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [ ] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
- [x] For a Release Review, a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/xml/bind/jakarta.xml.bind-api/3.0.0/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-xml-binding-tck-3.0.0.zip
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/jaxb-api/issues/168
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

### CODE REVIEW

**Comment by starksm64** [comment]
# Spec Review Checklist

1. Spec PR
  - [x] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta-{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] (Optional) Second PR for just apidocs

2. _index.md
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request
 
10. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Comment by lukasj** [comment]
Un-checked checkbox means that it is not done. As soon as spec relevant steps will be completed, The check-boxes will be checked.

**Comment by lukasj** [comment]
final version of the spec has been added, let me know if there are any issues there. Thx!

**Comment by starksm64** [comment]
Spec final version looks good.

**Comment by lukasj** [comment]
CCR is there

**Comment by starksm64** [comment]
I have checked the sha256 sum on two downloads of the https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-xml-binding-tck-3.0.0.zip staged TCK and neither matches the 8fc7e5c861e0afb83d675987361f84f3b1fc7019c7db53ef8e478007d38a3bb4 value given in the CCR. I see:

Scotts-iMacPro:jaxb starksm$ shasum -a256 ../jakarta-xml-binding-tck-3.0.0.zip 
494024ced40f3111131288a2d22ed9728c1c7202995d1c8bfc2e004c1ec33e81  ../jakarta-xml-binding-tck-3.0.0.zip

**Comment by lukasj** [comment]
@starksm64 Are you going to check the content of the zip before or after the checksum matches?

**Comment by starksm64** [comment]
@lukasj after

**Comment by starksm64** [comment]
Note I added EMO/PMC tasks that can be done in parallel.

**Comment by lukasj** [comment]
> Note I added EMO/PMC tasks that can be done in parallel.

already done, see appropriate places for reference

**Comment by starksm64** [comment]
I see the PMC email. The emo release tracking issue is:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=565959

That issue indicates the IP log is approved.

**Comment by lukasj** [comment]
checksum is fixed

**Review by starksm64 — APPROVED** [review]
I have verified the updated TCK, CCR and summary results. This is now ready for ballot.

**Comment by starksm64** [comment]
the ballot thread:
https://www.eclipse.org/mhonarc/lists/jakarta.ee-spec/msg01054.html

**Comment by starksm64** [comment]
The ballot has completed and passed, and the EMO has been notified. Waiting on EMO tracking issue.

Representative | Representative for: | Vote
-- | -- | --
Kenji Kazumura | Fujitsu | +1
Dan Bandera, Kevin Sutter | IBM | +1
Ed Bratt, Dmitry Kornilov | Oracle | +1
Andrew Pielage, Matt Gill | Payara | +1
Scott Stark, Mark Little | Red Hat | +1
David Blevins, Jean-Louis Monteiro, Cesar Hernandez | Tomitribe | +1
Ivar Grimstad | EE4J PMC | +1
Marcelo Ancelmo, Martijn Verburg | Participant Members |  
Werner Keil | Committer Members |  
Scott (Congquan) Wang | Enterprise Members | +1
  | Total | 8

**Comment by starksm64** [comment]
EMO review scheduled for Nov 4.

**Comment by starksm64** [comment]
* On ballot completion, the specification committee mentor:
 - [ ] adds this final checklist to the main PR.
 - [ ] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [ ] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
 - [ ] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [ ] creates an issue in the specification project that includes the following checklist for the specification project team:
 \<include url of Issue here>

**Pull request merged**
