### PR TITLE
setup initial directory structure for jakarta ee 9 specs

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

To help kick off the necessary creation of PRs for the Specs and Apidocs, this PR attempts to create the directory structure for all of the Specs that are expected to be part of Jakarta EE 9.  Please review for accuracy for the expected major release bump for each of the Jakarta EE component technologies.  And, there are a few new components (ie. activation, jaxb, etc) that we need to ensure the proper directory name (short name) was used.  Thanks!

(BTW, I used the .keep convention to allow the creation of "empty" placeholder directories in git.  This seemed to be a fairly common convention.)

All of this is in support of the first item in the PR checklist:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.

### CODE REVIEW

**Comment by bshannon** [comment]
You could probably create boilerplate _index.md pages in the new *.0 directories by copying the _index.md files from the existing directories and changing just a few things.  For example, mail/1.6/_index.md has
```
---
title: "Jakarta Mail 1.6"
date: 2019-09-10
summary: "First release for Jakarta EE 8"
---

Jakarta Mail defines a platform-independent and protocol-independent framework to build mail and messaging applications.
...
```

Create mail/2.0/_index.md as:
```
---
title: "Jakarta Mail 2.0"
date: 2019-12-16
summary: "Release for Jakarta EE 9"
---

Jakarta Mail defines a platform-independent and protocol-independent framework to build mail and messaging applications.

```
And delete the rest of the content after the "scope" statement.
@dblevins can then add the content he's proposing, and the project teams can further update the _index.md pages as appropriate for their *.0 release.

**Comment by kwsutter** [comment]
> You could probably create boilerplate _index.md pages in the new *.0 directories by copying the _index.md files from the existing directories and changing just a few things. For example, mail/1.6/_index.md has

Yeah, I thought about doing that.  At first, I was just going to copy over the existing _index.md and let the component team figure the proper updates.  But, then that may have been confusing.  And, I really didn't want to do all of the updating for all of the components.  Why take that fun away from everyone?  So, I decided to just go with the .keep files for now just to initiate the directory structure.  Thanks for reviewing!

**Comment by kwsutter** [comment]
> Now we just need @dblevins to fill in some of the proposed content so we can see what these directories would look like for specs that are just starting development of a new version. (The deploy preview isn't useful without this additional content.)

:-) Yeah, I noticed that too (deploy preview).  TBH, I don't know exactly what else @dblevins was planning for the proposed content.  I guess we'll have to wait for his review to see what else he had in mind.

**Comment by kwsutter** [comment]
> > You could probably create boilerplate _index.md pages in the new *.0 directories by copying the _index.md files from the existing directories and changing just a few things. For example, mail/1.6/_index.md has
> 
> Yeah, I thought about doing that. At first, I was just going to copy over the existing _index.md and let the component team figure the proper updates. But, then that may have been confusing. And, I really didn't want to do all of the updating for all of the components. Why take that fun away from everyone? So, I decided to just go with the .keep files for now just to initiate the directory structure. Thanks for reviewing!

I experimented a bit more with this and if we only provide the top-level metadata and the scope statement (like @bshannon suggested) and delete everything else, then this would provide a nice structure that is viewable via the deploy action...  And, this type of update would be relatively easy to do.  Any plus 1's?

**Comment by kwsutter** [comment]
Woohoo!  The deploy now works.  It helps if you remember to push the _index.md files...  doh!  This is a nice feature.  Check it out!  https://deploy-preview-130--jakartaee-specifications.netlify.com/  Click on the Specifications box and then traverse to one of the four modified specs -- activation, annotations, authentication, or authorization.

**Comment by bshannon** [comment]
Looks good Kevin, can you do it for all the spec directories?

Also, it should be "activation", not "activations".

**Comment by kwsutter** [comment]
> Looks good Kevin, can you do it for all the spec directories?

Thanks, Bill.  I'll continue the exercise.  Shouldn't take too long...
> 
> Also, it should be "activation", not "activations".

That was weird.  I couldn't find where I had mistyped "activations".  It looks like Hugo autogenerated the title and left off the "Jakarta" and made "Activation" plural...  I'll include a top-level _index.md for Activation to avoid that situation.  The "summary:" for each of these new components may need some adjusting...

**Comment by bshannon** [comment]
We're probably going to want to list specifications in reverse version number order,
so people see the newest specification first, right?  Is this going to require a change
to Hugo?

**Comment by kwsutter** [comment]
Yeah, this is a Hugo question....

**Comment by edbratt** [comment]
I think there ought to be something that clearly indicates Jakarta EE 8 is current and released and everything under Jakarta EE 9 is under development (and it not yes released). As it is now, there's little distinction except when you get to the leaf page where there is no data. Soon enough, there will be data, but it won't be finished for several months. Until then, I;d think we would want to make it clear to anyone browsing the tree, that EE 9 is under construction, while Jakarta EE 8 is the current release.

**Comment by kwsutter** [comment]
> I think there ought to be something that clearly indicates Jakarta EE 8 is current and released and everything under Jakarta EE 9 is under development (and it not yes released). 

Good idea, @edbratt.  So, something like "Jakarta EE 9 Platform (under development)"?  And, do this for every entry for the Jakarta EE 9 components.

**Comment by smillidge** [comment]
IMHO ready to merge. Once its out there we can add more changes and I can update the Jakarta EE 9 blurb with a link off to the release plan and add some of the verbiage from the plan as an intro.

**Comment by kwsutter** [comment]
Going ahead with the merge.

**Pull request merged**
