### PR TITLE
Jakarta CDI 4.1 final release

### PR DESCRIPTION
**Pull request by starksm64**
## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
- [x] Specification HTML in the form of jakarta-wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [ ] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable. N/A
- [x] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [x] Updated release record
   - [x] Generated IP Log
   - [x] Email to PMC
   - [x] Start release review by emailing EMO 
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/enterprise/jakarta.enterprise.cdi-api/4.1.0/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://download.eclipse.org/ee4j/cdi/4.1/
- [x] The URL of the compatibility certification request issue:
      [Weld 6.0.0.Beta1](https://github.com/jakartaee/cdi/issues/789)
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by starksm64** [comment]
This should be ready

**Comment by Emily-Jiang** [comment]
@starksm64 I added a comment on the CCR as it needs to be executed by both Java 17 and Java 21. Once it is ready, I can start the ballot.

**Comment by starksm64** [comment]
@Emily-Jiang The SE 21 runs have been added

**Comment by Emily-Jiang** [comment]
@starksm64 I reviewed the PR and found the following issues, which need to be resolved:
1. The spec doc status still shows `Draft`. Therefore, the license was wrong as well. You need to restage the release.
2. On the [CDI 4.1 page](https://deploy-preview-704--jakartaee-specifications.netlify.app/specifications/cdi/4.1/), 
a. you need to update the Minimum Java SE Version to Java SE 11 as currently it shows Java SE 17 or higher.
b. At the moment, only cdi main jar was listed. Do we also need to list the lang model and cdi.el jar as well. If not, where would be listed.
c. Do we need to say CDI 4.1 beans.xml instead of saying CDI 4.0 beans.xml.
> Schemas
> 
>     [XML Schema for the CDI 4.0 beans.xml deployment](https://jakarta.ee/xml/ns/jakartaee/beans_4_0.xsd)
>     No changes currently planed for the schema

d. Under `Compatible Implementations`, please remove `tbd`.

**Comment by starksm64** [comment]
Done

**Comment by Emily-Jiang** [comment]
> @starksm64 I reviewed the PR and found the following issues, which need to be resolved: See [here](https://deploy-preview-704--jakartaee-specifications.netlify.app/specifications/cdi/4.1/jakarta-cdi-spec-4.1.html)
> 
>     1. The spec doc status still shows `Draft`. Therefore, the license was wrong as well. You need to restage the release.
> 
>     2. On the [CDI 4.1 page](https://deploy-preview-704--jakartaee-specifications.netlify.app/specifications/cdi/4.1/),
>        a. you need to update the Minimum Java SE Version to Java SE 11 as currently it shows Java SE 17 or higher.
>        b. At the moment, only cdi main jar was listed. Do we also need to list the lang model and cdi.el jar as well. If not, where would be listed.
>        c. Do we need to say CDI 4.1 beans.xml instead of saying CDI 4.0 beans.xml.
> 
> 
> > Schemas
> > ```
> > [XML Schema for the CDI 4.0 beans.xml deployment](https://jakarta.ee/xml/ns/jakartaee/beans_4_0.xsd)
> > No changes currently planed for the schema
> > ```
> 
> d. Under `Compatible Implementations`, please remove `tbd`.

@starksm64 there are more changes to be done apart from removing `tbd`. Please see my comments above.

**Comment by starksm64** [comment]
@Emily-Jiang There should be nothing left to do on this

**Comment by Emily-Jiang** [comment]
* On ballot completion, the specification committee mentor:
 - [ ] adds this final checklist to the main PR.
 - [ ] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [ ] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
 - [ ] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [ ] creates an issue in the specification project that includes the following checklist for the specification project team:

**Pull request merged**
