### PR TITLE
Jakarta RESTful Web Services: API docs

### PR DESCRIPTION
**Pull request by spericas**
Signed-off-by: Santiago Pericas-Geertsen <santiago.pericasgeertsen@oracle.com>

## Specification PR template
Include the following:
- [ ] A directory in the form wombat/x.y containing the following.
- [ ] Specification PDF in the form of wombat_x.y.pdf
- [ ] Specification HTML in the form of wombat_x.y.html
- [X] Specification JavaDoc in the apidocs directory.
- [ ] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [ ] For a Progress Review, that sufficient progress has been made on
      a Compatible Implementation and TCK, to ensure that the spec is
      implementable and testable.
- [ ] For a Release Review, a summary that a Compatible Implementation
      is complete, passes the TCK, and that the TCK includes sufficient
      coverage of the specification. The TCK users guide MUST include
      the instructions to run the compatible implementations used to
      validate the release.  Instructions MAY be by reference.
- [ ] The URL of the OSSRH staging repository for the api, javadoc:
      <add URL here>

### CODE REVIEW

**Comment by spericas** [comment]
> Not a serious issue, but META-INF/MANIFEST.MF isn't needed here.
> 
> I see a reference to the license on the index page but it's missing from the footer of every page.

 Javadocs updated.

**Comment by spericas** [comment]
> I noted that the Javadocs seem to have "@SInCE 2.0" and I was expecting these to be "@SInCE JAX-RS 2.0" or similar based on https://www.eclipse.org/lists/ee4j-pmc/msg02056.html

 Frankly, we have made most of the API changes before some of those discussions started (or settled). Moreover, we went through the process of eliminating all the "JAX-RS" instances in our docs, so adding those seemed odd at the time; however, if the consensus is to use old acronyms with `@since`, we can make the change.

> but perhaps as the JAX-RS element was not removed for this release (I assume, based on e.g. [this file](https://github.com/eclipse-ee4j/jaxrs-api/blame/EE4J_8/jaxrs-api/src/main/java/javax/ws/rs/ApplicationPath.java))

 Can you elaborate this? I'm not sure which part of that file you're referring to.

**Comment by bshannon** [comment]
Fixing the @since entries is not critical for this release.

**Comment by dblevins** [comment]
Not sure if this is a showstopper, but there are some "Java EE" references we might want to convert:

```
restful-web-services/2.1/apidocs/javax/ws/rs/client/ClientBuilder.html:620: When running in a Java EE container, implementations are required to use the container-managed
restful-web-services/2.1/apidocs/javax/ws/rs/client/ClientBuilder.html:648: When running in a Java EE container, implementations are required to use the container-managed

```

**Comment by spericas** [comment]
> Not sure if this is a showstopper, but there are some "Java EE" references we might want to convert:
> 
> ```
> restful-web-services/2.1/apidocs/javax/ws/rs/client/ClientBuilder.html:620: When running in a Java EE container, implementations are required to use the container-managed
> restful-web-services/2.1/apidocs/javax/ws/rs/client/ClientBuilder.html:648: When running in a Java EE container, implementations are required to use the container-managed
> ```

 I've changed it to Jakarta EE.

**Comment by dblevins** [comment]
This spec is due for review and promotion to vote August 16th.  Can you review this checklist and ensure all requirements are met:
https://github.com/jakartaee/specification-committee/blob/master/spec_review_checklist.md

**Comment by spericas** [comment]
> This spec is due for review and promotion to vote August 16th. Can you review this checklist and ensure all requirements are met:
> https://github.com/jakartaee/specification-committee/blob/master/spec_review_checklist.md

We are working on it and making progress. We should be done in time.

**Comment by kwsutter** [comment]
# Spec Review Checklist

1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://oss.sonatype.org/conte/repositories/staging/jakarta/{spec}/jakarta-{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] Second PR for just apidocs

2. _index.md
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

**Comment by spericas** [comment]
@kwsutter It was brought to my attention that the directory name used in this PR is inconsistent with that in #7. I will submit another PR shortly to fix this inconsistency.

**Comment by spericas** [comment]
@kwsutter @bshannon https://github.com/jakartaee/specifications/pull/99

**Pull request merged**
