### PR TITLE
Jakarta JSON Processing  2.1 spec

### PR DESCRIPTION
**Pull request by lukasj**
## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [ ] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
      N/A
- [ ] Specification HTML in the form of jakarta-wombat-spec-x.y.html
      N/A
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [ ] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
- [x] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [x] Updated release record
   - [x] Generated IP Log
   - [x] Email to PMC
   - [x] Start release review by emailing EMO 
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/json/jakarta.json-api/2.1.0/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/promoted/eftl/jakarta-jsonp-tck-2.1.0.zip
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/jsonp/issues/364
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by ivargrimstad** [comment]
It would be nice if we had some text on the _index page explaining that there are no PDF/HTML versions of the spec and pointing the reader to the JavaDoc for details.

**Comment by starksm64** [comment]
# Spec Review Checklist

1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form jakarta-{spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form jakarta-{spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta.{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] (Optional) Second PR for just apidocs

2. _index.md
  - [ ] Link to project release plan of the form https://projects.eclipse.org/projects/ee4j.{spec}/releases/x.y/plan
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip (The folder path is required, the file name pattern is preferred.)
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

10. If a Release Review is required, the specification project team contacts the EMO to initiate the review by sending an email to emo@eclipse.org.
    (A Release Review is not required if the current release is a Service Release based on a previously successful Major or Minor
    release as indicated by a release record on the project's Releases page, e.g., the [Jakarta Servlet releases page](https://projects.eclipse.org/projects/ee4j.servlet/reviews).)
    - [ ] An issue will be created by the EMO to track the release review.
    - [ ] The specification project team requests approval for the release from the PMC by sending an email to ee4j-pmc@eclipse.org.
    - [ ] The specification project team then delivers an IP Log to the IP Team for their review as described in https://www.eclipse.org/projects/handbook/#pmi-commands-iplog.

11. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Comment by lukasj** [comment]
@ivargrimstad you mean something similar to what's in the last commit? Or can you suggest something better? I do not mean the exact text but where to put it, UI-like things, etc...

**Comment by ivargrimstad** [comment]
> @ivargrimstad do you mean something similar to what's in the last commit? Or can you suggest something better? I do not necessarily mean the exact text but where to put it, UI-like things, etc...

Yes, something like this was what I had in mind.

**Comment by starksm64** [comment]
@lukasj any target date on getting this ready for ballot?

**Comment by lukasj** [comment]
we hope to have tck ready before x-mas or during 1st half of Jan at the latest

**Comment by starksm64** [comment]
@Emily-Jiang, @ivargrimstad this looks ready for ballot to me

**Comment by lukasj** [comment]
I’d need to respin the api jar as there was an issue found. Let me know if I can still do that. Thx!

**Comment by starksm64** [comment]
Sure, just drop the current one and update it. This has not started a vote yet.

**Comment by lukasj** [comment]
Ok, I’ll let you know once it’s done

**Comment by lukasj** [comment]
updated/refreshed/done => ready

**Comment by Emily-Jiang** [comment]
> Sure, just drop the current one and update it. This has not started a vote yet.

I have now started the ballot @starksm64 @lukasj

**Comment by Emily-Jiang** [comment]
The ballot has passed. Please proceed to the next step.

**Comment by Emily-Jiang** [comment]
- On ballot completion, the specification committee mentor:

- [ ] adds this final checklist to the main PR.

- [ ] adds the approved label to the PRs, and sends out the Ballot Summary per this [template](https://github.com/jakartaee/specifications/pull/438#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](https://github.com/jakartaee/specifications/pull/jakarta.ee-spec@eclipse.org)

- [ ] calculates the staged EFTL TCK signature and promotes it to the committee download area

- [ ] using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).

- [ ] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.

- [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.

- [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](https://github.com/jakartaee/specifications/pull/emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.

- [ ] creates an issue in the specification project that includes the following checklist for the specification project team: https://github.com/eclipse-ee4j/batch-api/issues/200

**Comment by Emily-Jiang** [comment]
@starksm64 can you continue the mentor tasks listed above https://github.com/jakartaee/specifications/pull/432#issuecomment-1077874292. I don't have committer status so I could not add the `approved` label.

**Comment by starksm64** [comment]
The official TCK was promoted to https://download.eclipse.org/jakartaee/jsonp/2.1/ and has a SHA256 of:
└> cat /tmp/jakarta-jsonp-tck-2.1.0.zip.sha256 
6ee953382ff965627fe20dd7e3bfce6c968ed829d611cf4990988ab54bfe8b54

**Comment by starksm64** [comment]
All tasks on this issue have been completed.

**Pull request merged**
