### PR TITLE
Jakarta JSON Binding 2.1 Plan Review

### PR DESCRIPTION
**Pull request by Verdent**
Signed-off-by: David Kral <david.k.kral@oracle.com>

## Plan Review PR template
When creating a specification project plan review, create PRs with the content defined as follows.

Include the following in the PR:

- [x] A directory in the form wombat/x.y where x.y is the release major.minor version.
- [x] An index page wombat/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
- [x] Title should be on the form "Jakarta Wombat X.Y (under development)"
- [x] Includes a plan for the release. Usually, a couple of statements is enough. Otherwise, a link to a document describing the release.
- [x] N/A - Includes a detailed description of any backward incompatibility (Mark with N/A and check if none)
- [x] N/A - Declares optional features if there are any (Mark with N/A and check if none)
- [x] Includes minimum Java SE version
- [x] N/A - Describe any updates or required changes including splitting out the TCK (Mark with N/A and check if not planned)
- [x] Link to updated release record
https://projects.eclipse.org/projects/ee4j.jsonb/releases/2.1.0

### CODE REVIEW

**Review by ivargrimstad — APPROVED** [review]

**Comment by kwsutter** [comment]
Before I can vote on this Plan, I would like to understand why this is a major version update.  The release record indicates that there are breaking API changes.  But, I don't see those documented.  I see the long list of Issues that need to be addressed, but I really don't want to examine every issue and come to my own conclusions.

I would like to see a short description of the proposed breaking changes before casting my ballot.  Thanks!

**Comment by Verdent** [comment]
There is going to be a significant number of changes. It’s too many for a minor release. We don’t have a final design of APIs yet. We cannot say for now if there are going to be backwards incompatible changes or only additions to existing APIs (which can be partially treated as incompatibility).

**Comment by kwsutter** [comment]
But, from a semantic versioning perspective, we should only be increasing the major version if there is an incompatible update to the API.  A minor version can still contain a "significant number of changes", as long as you don't break the semantic expectations of the API.  If you can't identify any breaking changes at this point, I think you should consider a 2.x update and then change this later if the need arises.

**Comment by Verdent** [comment]
Alright, I think your point does make sense. I have changed the version to the 2.1 as proposed.

**Review by kwsutter — APPROVED** [review]
Looks great, @Verdent!  Thank you!

**Pull request merged**
