### PR TITLE
Release Jakarta Data Beta version

### PR DESCRIPTION
**Pull request by otaviojava**
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of wombat-spec-x.y.pdf
- [x] Specification HTML in the form of wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md

### CODE REVIEW

**Comment by otaviojava** [comment]
@ivargrimstad @Emily-Jiang

**Comment by ivargrimstad** [comment]
It is on the agenda for Today's specification committee to figure out how to handle this PR. Some of the things we will look into are;
- Jakarta Data does not have a public plan yet, so there may be a need for a plan review
- If it is considered a progress review, there are some information/items missing for that to pass. For example a milestone version of the TCK and a compatible implementation passing this version of the TCK

I will provide more feedback after the call.

**Comment by ivargrimstad** [comment]
We discussed this in the spec cmte last week and concluded that a progress review is the most appropriate. 
What you need to do is:

- Update _index.md in the the PR with a plan according to the new template, specifically the three sections
```
### New features, enhancements or additions
<!-- List here -->
* 

### Removals, deprecations or backwards incompatible changes
<!-- List here -->
* 

### Minimum Java SE Version
<!-- Specify the minimum required Java SE version for this specification -->
**<!--VERSION NUMBER-->**
```
- The "Removals" section can just state "N/A" since it is the first release
- Look at other specifications for examples, e.g. [Jakarta MVC 2.1](https://jakarta.ee/specifications/mvc/2.1/)

- Create a release record for 1.0 on the project [PMI pages](https://projects.eclipse.org/projects/ee4j.data/governance) with the plan and link to it from the _index.md page
- I don't think you need release records for the milestones (beta-releases), but you can create them if you want the history to be complete on the PMI releases page. You don't need to link to those release records here though.

**Comment by otaviojava** [comment]
Thank you @ivargrimstad so, I'll close this PR.

**Comment by ivargrimstad** [comment]
> Thank you @ivargrimstad so, I'll close this PR.

That's not exactly what I meant. If you don't want to do a progress review at this point, you should still do a plan review.

**Comment by keilw** [comment]
Thanks @ivargrimstad Maybe a plan review could also be appropriate for Jakarta NoSQL and the planned changes in https://github.com/eclipse-ee4j/nosql/pull/154

>I don't think you need release records for the milestones (beta-releases), but you can create them if you want the history to >be complete...

With around 400 API elements changed or dropped, I would use that history in this case, while other milestone/beta-releases could be less extensive.

**Comment by otaviojava** [comment]
@ivargrimstad 
We'll close this one and open a milestone after try-out more with the community.
When we get more confidence, we'll put the PR again.

For now, let's try it faster.

**Comment by ivargrimstad** [comment]
That would be appropriate for a progress review. You still need a plan. Right now, the project is operating under the radar of the Specification Committee. According to the JESP, a plan is required.

**Comment by keilw** [comment]
Release plan I guess, kind of like https://projects.eclipse.org/projects/technology.uomo/releases/0.8.0/plan or https://projects.eclipse.org/projects/ee4j.jakartaconfig/releases/0.1/plan

**Comment by otaviojava** [comment]
@ivargrimstad do you have some models for use on plans?
We usually work on Twitter or on the e-mail list.

**Comment by ivargrimstad** [comment]
Yes, see my comment from yesterday. Look at examples by other specs. E.g. MVC

**Comment by otaviojava** [comment]
Thanks, copy. It looks like a changelog file.

https://keepachangelog.com/en/1.0.0/

**Pull request closed without merging**
