### PR TITLE
Jakarta JSON Processing 2.0.1 (SR)

### PR DESCRIPTION
**Pull request by lukasj**
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>

## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
       N/A
- [x] Specification HTML in the form of jakarta-wombat-spec-x.y.html
       N/A
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
       N/A
- [x] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
       N/A
- [ ] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [x] Updated release record
   - [x] Generated IP Log
   - [ ] Email to PMC
   - [x] Start release review by emailing EMO 
       N/A
- [x] For a [Service Release Review](https://jakarta.ee/committees/specification/operations/#creating_a_final_service_release_specification)
   - [x] Updated release record
    https://projects.eclipse.org/projects/ee4j.jsonp/releases/2.0.1
   - [x] Add Change Log
   - [x] Start release review by emailing Specification Committee
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/json/jakarta.json-api/2.0.1/
- [x] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
       https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jsonp-tck-2.0.1.zip
- [x] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/jsonp/issues/281
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by kwsutter** [comment]
FYI, there is a shorter PR template checklist being worked via PR #345.  You can continue to use the one already here and mark the extra things as "n/a".  Just wanted you to be aware of the other work in this area.  Thanks!

**Comment by lukasj** [comment]
the process states:
> After the Specification PRs are reviewed and approved by independent specification committee members, the PRs can be merged. The Specification Project team can then release the staged artifacts to Maven Central.

which implies that the binary cannot be published before this gets merged. Would be great to know, if there is anything I can do to speed things up. Thanks.

**Comment by keilw** [comment]
@lukasj I am going through anyting that's not "N/A" and there is almost nothing, but the changelog says:
"fixed broken cross references in the Javadoc" could you point me to which file(s) were fixed?
Other than that only 3 boxes under Point 6 are missing, then this can be done.

**Comment by lukasj** [comment]
@keilw see #318 and https://github.com/eclipse-ee4j/jsonp/pull/272 linked from there

Note this is *service release* (see the [link](https://jakarta.ee/committees/specification/operations/#creating_a_final_service_release_specification) for details), therefore rules/requirements for regular release from point 6 do not apply here

**Review by keilw — APPROVED** [review]
Looks good to me

**Pull request merged**
