### PR TITLE
Jakarta Activation 2.1 Plan Review

### PR DESCRIPTION
**Pull request by lukasj**
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>

## Plan Review PR template
When creating a specification project plan review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version.
- [x] An index page wombat/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
- [x] Title should be on the form "Jakarta Wombat X.Y (under development)"
- [x] Includes a plan for the release. Usually, a couple of statements is enough. Otherwise, a link to a document describing the release.
- [x] N/A - Includes a detailed description of any backward incompatibility (Mark with **N/A** and check if none)
- [x] N/A - Declares optional features if there are any (Mark with **N/A** and check if none)
- [x] Includes minimum Java SE version
- [x] N/A - Describe any updates or required changes including splitting out the TCK (Mark with **N/A** and check if not planned)
- [x] Link to updated release record
       https://projects.eclipse.org/projects/ee4j.jaf/releases/2.1

### CODE REVIEW

**Review by jeanouii — COMMENTED** [review]
Would have been great to have the release record reflect what's in the plan. Here is an example of what some other specifications do.

https://projects.eclipse.org/projects/ee4j.es/releases/3.0

Other than that it's ok with me.
@lukasj do you want a bit more time to improve it or can I create the ballot?

**Review by jeanouii — APPROVED** [review]
https://www.eclipse.org/mhonarc/lists/jakarta.ee-spec/msg01747.html

**Comment by lukasj** [comment]
@jeanouii api/impl split is the only thing planned for the 2.1 release (and there is a PR for that already on the review). Can you suggest how can this be made more explicit? Or do you have anything else you want to see in the 2.1? Thx!

**Comment by lukasj** [comment]
Is there anything I need to do here to move this forward?

**Pull request merged**
