### PR TITLE
Jakarta Security 1.0

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

## Specification PR template
When creating a specification project release review, create two PRs with the content divided as follows.

Include the following in PR#1:
- [X] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [X] Specification PDF in the form of wombat_x.y.pdf
- [X] Specification HTML in the form of wombat_x.y.html
- [X] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] For a Release Review, a summary that a Compatible Implementation
      is complete, passes the TCK, and that the TCK includes sufficient
      coverage of the specification. The TCK users guide MUST include
      the instructions to run the compatible implementations used to
      validate the release.  Instructions MAY be by reference.
- [X] The URL of the OSSRH staging repository for the api, javadoc:
https://oss.sonatype.org/content/repositories/staging/jakarta/security/enterprise/jakarta.security.enterprise-api/1.0.2/
- [X] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-security-tck-1.0.0.zip
- [X] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/security-api/issues/143

### CODE REVIEW

**Comment by dblevins** [comment]
Spec "status" should be "Final" or "Final Release"

**Comment by edbratt** [comment]
Please update the TCK link to promoted version w/EFSL http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-security-tck-1.0.0.zip
SHA-256: 
`
309111f000afb682f631a99d86a52bc8a8ab6f27dbed496387d5752e1a6647b4
`

**Comment by arjantijms** [comment]
> Please update the TCK link to promoted version w/EFSL

Thanks, will do!

**Comment by arjantijms** [comment]
Ran TCK again with promoted version. Script needed a little adjustment for the new name being used (security vs securityapi) and the "-" added, otherwise it passed again. TMP link to results: https://jenkins.eclipse.org/es/job/2_security-run-tck-against-staged-build/lastSuccessfulBuild/artifact/security-tck/bin/summary.txt/*view*/ (will update link to stable one tomorrow)

**Comment by keilw** [comment]
Why is the version number 1.0 compared to Java EE 8/JSR 375, is the spec unchanged?

**Comment by arjantijms** [comment]
Stable link to results, to be included with the certification request for the implementation using this API: https://eclipse-ee4j.github.io/soteria/certifications/jakarta-security/1.0/TCK-Results

**Comment by NottyCode** [comment]
# Spec Review Checklist

1. Spec PR
  - [x] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [x] Directory of form {spec}/x.y
  - [x] PDF of form {spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [x] HTML of form {spec}-spec-x.y.html ("-spec" preferred but not required)
  - [x] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [x] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [x] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://oss.sonatype.org/conte/repositories/staging/jakarta/{spec}/jakarta-{spec}-api/x.y.z/
  - [x] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [x] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [x] Second PR for just apidocs

2. _index.md
  - [x] Link to spec pdf
  - [x] Link to spec html
  - [x] Link to apidocs
  - [x] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip
  - [x] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [x] Name of and link to at least one Compatible Implementation

3. javadocs
  - [x] Footer contains Eclipse copyright and link to license
  - [x] ESFL license is included, usually as doc-files/speclicense.html
  - [x] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [x] Correct spec title
  - [x] Version number of the form x.y, not x.y.z
  - [x] Correct Eclipse copyright line
  - [x] No DRAFT or SNAPSHOT
  - [x] Correct Logo

5. Spec HTML
  - [x] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [x] EFTL license file, preferably named LICENSE.md
  - [x] User's Guide (or equivalent documentation)
  - [x] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [x] Software requirements listed
  - [x] Installation and configuration described
  - [x] How to run tests
  - [x] Where to file challenges

8. Compatibility certification request
  - [x] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [x] Request issue has `certification` label.

9. TCK results summary
  - [x] Page is hosted by Compatible Implementation project
  - [x] Includes all information from certification request
  - [x] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

**Comment by NottyCode** [comment]
When I download the TCK I get the following SHA: `de4114b9532333bd2c24d7bcb54f3f47cb4dcead6d0b3de05baea237acac948e` but the compatibility request is using a version with a sha hash of `309111f000afb682f631a99d86a52bc8a8ab6f27dbed496387d5752e1a6647b4`

**Comment by NottyCode** [comment]
@arjantijms the updated link in commit 057d1a4 is to a page with a 404. The PR comment links to the old location which does give me a payload, but it has the sha hash `de4114b9532333bd2c24d7bcb54f3f47cb4dcead6d0b3de05baea237acac948e` If the commit was intended to address the sha hash mismatch I don't think it does.

**Comment by arjantijms** [comment]
@NottyCode 
> the updated link in commit 057d1a4 is to a page with a 404.

Yes, but wasn't that the idea? Almost no TCKs are actually there at the moment, but they are supposed to appear there at some point, right? The TCK link for Messaging that was said to be correct gives a 404 as well. It's a little confusing indeed.

**Comment by arjantijms** [comment]
I checked the hash that was used for the run, and it's `de4114b9532333bd2c24d7bcb54f3f47cb4dcead6d0b3de05baea237acac948e`, which is the same as you reported.

I assume that there's a copy/paste error in the hash for the report, but I'll re-run the TCK to be sure.

**Comment by arjantijms** [comment]
@NottyCode I re-ran the Security TCK, just to be 100% sure. The SHA256s of the prime artefacts used are printed at the bottom of the summary:

```
[javatest.batch] Number of Tests Passed      = 85
[javatest.batch] Number of Tests Failed      = 0
[javatest.batch] Number of Tests with Errors = 0
[javatest.batch] ********************************************************************************
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/autoapplysession/Client.java#testAutoApplySession
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/basic/Client.java#testBasicHAMHasCorrectQualifier
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/basic/Client.java#testBasicHAMValidateRequest
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/basic/Client.java#testBasicHAMValidateRequest_wrongPassword
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/customform/base/Client.java#testCustomFormHAMHasCorrectQualifier
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/customform/base/Client.java#testCustomFormHAMValidateRequest
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/customform/base/Client.java#testCustomFormLoginToContinueErrorPage
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/customform/base/Client.java#testLoginToContinueuseRedirectToLogin
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/customform/expression/Client.java#testLoginToContinueuseForwardToLoginExpression
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/form/Client.java#testFormHAMHasCorrectQualifier
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/form/Client.java#testFormHAMValidateRequest
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/form/Client.java#testLoginToContinueerrorPage
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/form/Client.java#testLoginToContinueLoginPage
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/rememberme/test1/Client.java#testRememberMecookieHttpOnly
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/rememberme/test1/Client.java#testRememberMecookieMaxAgeSeconds
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/rememberme/test1/Client.java#testRememberMeCookieNameandisRememberMeExpression
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/rememberme/test2/Client.java#testRememberMecookieHttpOnlyFalse
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/rememberme/test2/Client.java#testRememberMecookieSecureOnly
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/rememberme/test3/Client.java#testRememberMecookieHttpOnlyExpression
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/rememberme/test3/Client.java#testRememberMecookieMaxAgeSecondsExpression
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/rememberme/test3/Client.java#testRememberMecookieSecureOnlyExpression
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/rememberme/test3/Client.java#testRememberMeisRememberMe
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/sam/obtainbean/Client.java#testSAMObtainBean
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/workflow/cleansubject/Client.java#testHAMCleanSubject
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/workflow/secureresponse/Client.java#testHAMSecureResponse
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/workflow/validaterequest/Client.java#testCallValidateRequestBeforeService
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/workflow/validaterequestduringauthen/Client.java#testCallValidateRequestDuringAuthenticate
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/ham/workflow/validaterequestwithfilter/Client.java#testCallValidateRequestBeforeFilter
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/basic/Client.java#testIdentityStoreInstall
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/customhandler/Client.java#testIdentityStore_customHandler
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/basic/Client.java#testAnnotationDBIDStore_Basic
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/hashalgorithm/Client.java#testAnnotationDBIDStore_HashAlgorithmDefault
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/hashalgorithmparam/Client.java#testAnnotationDBIDStore_HashAlgorithmParam
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/invalidcallerquery/Client.java#testAnnotationDBIDStore_Invalidcallerquery
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/invaliddatasource/Client.java#testAnnotationDBIDStore_Invaliddatasource
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/invalidgroupsquery/Client.java#testAnnotationDBIDStore_Invalidgroupsquery
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/invalidhashalgorithmparam/Client.java#testAnnotationDBIDStore_InvalidHashAlgorithmParam
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/invalidpriorityuseforexpr/Client.java#testAnnotationDBIDStore_invalidpriorityuseforexpr
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/multi/Client.java#testAnnotationDBIDStore_multi_withLdap
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/notvalidated/Client.java#testAnnotationDBIDStore_notValidated
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/priorityuseforexpr/Client.java#testAnnotationDBIDStore_priorityuseforexpr
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/priorityuseforexprbean/Client.java#testAnnotationDBIDStore_priorityuseforexprbean
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/useforgroup/Client.java#testAnnotationDBIDStore_useforgroup
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/database/useforvalidation/Client.java#testAnnotationDBIDStore_useforvalidation
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/idstorepermission/Client.java#testIdentityStore_customHandlerWithoutIDStorePermission
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/basic/Client.java#testAnnotationLdapIDStore_Basic
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/binddn/Client.java#testAnnotationLdapIDStore_Binddn
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/groupmemberof/Client.java#testAnnotationLdapIDStore_groupMemberOf
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/groupmemberofnotexist/Client.java#testAnnotationLdapIDStore_groupMemberOfNotExist
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/invalidbinddn/Client.java#testAnnotationLdapIDStore_invalidBinddn
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/invalidbinddnpassword/Client.java#testAnnotationLdapIDStore_invalidBinddnPassword
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/invalidcallerbasedn/Client.java#testAnnotationLdapIDStore_invalidCallerBasedn
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/invalidcallernameattr/Client.java#testAnnotationLdapIDStore_invalidCallerNameAttribute
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/invalidcallersearchbase/Client.java#testAnnotationLdapIDStore_invalidCallerSearchBase
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/invalidcallersearchfilter/Client.java#testAnnotationLdapIDStore_invalidCallerSearchFilter
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/invalidgroupmemberattr/Client.java#testAnnotationLdapIDStore_invalidGroupMemberAttribute
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/invalidgroupnameattr/Client.java#testAnnotationLdapIDStore_invalidGroupNameAttribute
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/invalidgroupsearchbase/Client.java#testAnnotationLdapIDStore_invalidGroupSearchBase
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/invalidgroupsearchfilter/Client.java#testAnnotationLdapIDStore_invalidGroupSearchFilter
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/invalidsearchscopeexpr/Client.java#testAnnotationLdapIDStore_invalidsearchScopeExpression
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/invalidurl/Client.java#testAnnotationLdapIDStore_invalidURL
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/notvalidated/Client.java#testAnnotationLdapIDStore_NotValidated
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/priorityuseforexpr/Client.java#testIdentityStore_ldap_priorityuseforexpr
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/searchscopebothonelevel/Client.java#testAnnotationLdapIDStore_searchScopeBothOneLevel
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/searchscopebothsubtree/Client.java#testAnnotationLdapIDStore_searchScopeBothSubTree
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/searchscopecalleronelevelgroupsubtree/Client.java#testAnnotationLdapIDStore_searchScopeCallerOneLevelGroupSubTree
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/searchscopecallersubtreegrouponelevel/Client.java#testAnnotationLdapIDStore_searchScopeCallerSubTreeGroupOneLevel
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/searchscopeexpr/Client.java#testAnnotationLdapIDStore_searchScopeExpression
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/useforgroup/Client.java#testIdentityStore_ldap_useforgroup
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/ldap/useforvalidation/Client.java#testIdentityStore_ldap_useforvalidation
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/multi/Client.java#testIdentityStoreValidate_multiIDStore
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/multi/Client.java#testIdentityStoreValidate_multiIDStore_INVALID
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/multi/Client.java#testIdentityStoreValidate_multiIDStore_INVALIDWithNOTVALIDATED
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/multi/Client.java#testIdentityStoreValidate_multiIDStore_NOTVALIDATED
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/multiauthz/Client.java#testIdentityStore_getGroups_multiGroupStore_highPriority_valid
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/multiauthz/Client.java#testIdentityStore_getGroups_multiGroupStore_lowerPriority_valid
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/useforgroup/Client.java#testIdentityStore_validationType_useforgroup
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/idstore/useforvalidation/Client.java#testIdentityStore_validationType_useforvalidation
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/securitycontext/authenticate/Client.java#testSecurityContextAuthenticate
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/securitycontext/authenticate/Client.java#testSecurityContextAuthenticate_wrongCredential
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/securitycontext/callerdata/Client.java#testSecurityContextHasAccessToWebResource
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/securitycontext/callerdata/Client.java#testSecurityContextIsCallerInRole
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/securitycontext/ejb/Client.java#testSecurityContextAvailableInEJB
[javatest.batch] PASSED........com/sun/ts/tests/securityapi/securitycontext/getprincipalsbytype/Client.java#testSecurityContextGetPrincipalsByType
[javatest.batch] PASSED........com/sun/ts/tests/signaturetest/securityapi/SecurityAPISigTest.java#signatureTest_from_standalone
[javatest.batch] 
SHA256_GF=SHA256(/home/jenkins/workspace/2_security-run-tck-against-staged-build/download/glassfish.zip)= 26f3fa6463d24c5ed3956e4cab24a97e834ca37d7a23d341aadaa78d9e0093ce
SHA256_API=SHA256(/home/jenkins/workspace/2_security-run-tck-against-staged-build/download/jakarta.security.enterprise-api.jar)= 82e6545f0d61b5329327677d563dabab16bbcc62e41c18e0cb836f1235a9d5ed
SHA256_TCK=SHA256(/home/jenkins/workspace/2_security-run-tck-against-staged-build/download/securitytck.zip)= de4114b9532333bd2c24d7bcb54f3f47cb4dcead6d0b3de05baea237acac948e
```

It seems we're good here, as the TCK SHA256 still matches.

**Comment by NottyCode** [comment]
The latest run data all matches so it looks good to me. I've marked the last 2 items on the checklist.

**Comment by arjantijms** [comment]
@NottyCode Thanks Alasdair! :)

**Comment by NottyCode** [comment]
@arjantijms This is optional for the first release, but the javadoc jar generated by the project isn't consistent with the javadoc PR. The copyright footer doesn't match the PR.

**Comment by arjantijms** [comment]
@NottyCode 
>This is optional for the first release, but the javadoc jar generated by the project isn't consistent with the javadoc PR. The copyright footer doesn't match the PR.

You're right, this was actually an interesting problem. The default scripts that most projects use, do the following:

```sh
echo '-[ Deploy artifacts to staging repository ]-------------------------------------'
mvn ${MVN_EXTRA} -U -C -s /home/jenkins/.m2/settings.xml \
    -DskipTests -Ddoclint=none -Poss-release -Pstaging \
    clean package source:jar javadoc:jar gpg:sign install:install ${MVN_DEPLOY_ARGS}
```

The java docs in the project however are configured by the id `attach-api-javadocs`. Thus runs if you just do a `mvn install`, but not if you use `javadoc:jar`.

The solution it to add the id explicitly:

```sh
echo '-[ Deploy artifacts to staging repository ]-------------------------------------'
mvn ${MVN_EXTRA} -U -C -s /home/jenkins/.m2/settings.xml \
    -DskipTests -Ddoclint=none -Poss-release -Pstaging \
    clean package source:jar javadoc:jar@attach-api-javadocs gpg:sign install:install ${MVN_DEPLOY_ARGS}
```
@attach-api-javadocs

**Comment by arjantijms** [comment]
@bshannon I updated Jakarta Security with the new Jakarta Authorization 1.5 maven coordinates, and re-run the TCK: https://jenkins.eclipse.org/es/job/2_security-run-tck-against-staged-build/lastSuccessfulBuild/artifact/security-tck/bin/summary.txt/*view*/

I think this one should now be good to go.

@NottyCode 

The last item in "SHA-256 fingerprint matches staged TCK zip file on cert request" isn't checked off yet, but that one is now correct.

**Comment by dblevins** [comment]
* On ballot completion
 - [x] The designated specification committee representative adds this final checklist to the main PR.
 - [x] The specification committee representative merges the specification PRs.
 - [ ] The designated specification committee representative calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job.
 - [ ] The specification project member who created the staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] The EMO updates the specification page with the ballot results.
This list goes on the committed spec index page.
 - [ ] The specification project team should go through the merged spec website page to verify all the links are valid.
 - [ ] The specification project team should approve the compatibility request.
 - [ ] The compatible implementation project/vendor MUST send an email tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [ ] The specification project team should merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
@dblevins thanks for merging! I'll now go forward releasing the API jars

**Comment by arjantijms** [comment]
Security jars released and available on Maven Central:

https://repo1.maven.org/maven2/jakarta/security/enterprise/jakarta.security.enterprise-api/1.0.2/

**Comment by bshannon** [comment]
@arjantijms Please confirm the other checklist items above.

**Comment by arjantijms** [comment]
@bshannon mail sent, and PR done:

https://github.com/eclipse-ee4j/security-api/pull/144

Due to the employment transition I lost the rights to merge it. Have asked @m0mus and @waynebeaton about it.

**Comment by bshannon** [comment]
I approved the PR, but you need to pass the ECA check.

**Comment by arjantijms** [comment]
@bshannon 

The ECA check doesn't fail due to the bot having done the commits:

> Anonymous (eclipse-es-bot@****.org) is not covered by the necessary legal agreements in order to proceed.

I think that all project leads always just override this, but we may want to sort this by either excluding the bots or giving them the right legal right?

**Comment by bshannon** [comment]
Sigh.  Have they still not fixed that?

Ok, but what about the Travis CI failures?

**Comment by arjantijms** [comment]
The travis failures are because travis suddenly started to not support (Oracle) JDK 8 anymore.

Tons of other projects of me got the same error.

**Comment by bshannon** [comment]
> The travis failures are because travis suddenly started to not support (Oracle) JDK 8 anymore.

Are you going to switch it to OpenJDK?  Or are you going to disable Travis?

**Comment by arjantijms** [comment]
> Are you going to switch it to OpenJDK? Or are you going to disable Travis?

Switching to OpenJDK. 

The other solution is listing the Linux distribution using the `dist:` attribute and then enter a distro that does have OracleJDK,  but that seems to tie the file a bit too much to specific names being used by Travis.

**Pull request merged**
