### PR TITLE
activation TCK 2.1.1

### PR DESCRIPTION
**Pull request by lukasj**
promote jakarta activation 2.1.1 tck addressing [linked tck challenge](https://github.com/jakartaee/jaf-api/issues/98), please.

Staged TCK binary: https://www.eclipse.org/downloads/download.php?file=/ee4j/jaf/jakartaee10/staged/eftl/jakarta-activation-tck-2.1.1.zip

### CODE REVIEW

**Comment by ivargrimstad** [comment]
TCK promoted

**Comment by lukasj** [comment]
@ivargrimstad @Emily-Jiang can this https://download.eclipse.org/ee4j/jaf/jakartaee10/staged/eftl/jakarta-activation-tck-2.1.1.zip be promoted to fix broken link to the binary on the spec page once @brideck verifies it one more time (...rather twice than never...;-) ), please?

**Comment by brideck** [comment]
The new zip file looks good on our end. Please promote it.

**Comment by ivargrimstad** [comment]
Done: https://download.eclipse.org/jakartaee/activation/2.1/

**Pull request merged**
