### PR TITLE
El 5.0.0 release

### PR DESCRIPTION
**Pull request by markt-asf**
## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [X] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [X] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
- [X] Specification HTML in the form of jakarta-wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [X] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [X] Updated release record
   - [X] Generated IP Log
   - [x] Email to PMC
   - [x] Start release review by emailing EMO 
- [X] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/el/jakarta.el-api/5.0.0/
- [X] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-expression-language-tck-5.0.0.zip
- [X] The URL of the compatibility certification request issue:
      https://github.com/jakartaee/expression-language/issues/185
- [X] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by Pandrex247** [comment]
1. Spec PR
  - [x] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [x] Directory of form {spec}/x.y
  - [x] PDF of form jakarta-{spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [x] HTML of form jakarta-{spec}-spec-x.y.html ("-spec" preferred but not required)
  - [x] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [x] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [x] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [x] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta.{spec}-api/x.y.z/
  - [x] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue} - **Missing**
  - [x] (Optional) Second PR for just apidocs - N/A

2. _index.md
  - [ ] Link to project release plan of the form https://projects.eclipse.org/projects/ee4j.{spec}/releases/x.y/plan - **Missing extra link to the plan, please add it as an item under the release record link**
  - [x] Link to spec pdf
  - [x] Link to spec html
  - [x] Link to apidocs
  - [x] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip (The folder path is required, the file name pattern is preferred.)
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar - **Not pointing to search.maven**
  - [ ] Name of and link to at least one Compatible Implementation - **Not sure TBD is valid!**
  - [x] Review summary statement to ensure it has been updated to reflect the work accomplished and does not contain proposal statements as might be found in Plan Review statement.

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license - **Needs updating? Lists 2020**
  - [x] ESFL license is included, usually as doc-files/speclicense.html
  - [x] no META-INF directory in PR
  - [x] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [x] Correct spec title
  - [x] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line - **Does this need updating for 2022? It lists 2021**
  - [x] No DRAFT or SNAPSHOT
  - [x] Correct Logo

5. Spec HTML
  - [x] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release) - **Seems to be the README for EL 4?**
  - [x] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation) - **Also seems to be for EL 4**
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG) - **Knock-on of no listed CI, how to test against GlassFish 6.1 included but that's not the CI for EL 5**

7. TCK User's Guide (or equivalent documentation)
  - [x] Software requirements listed
  - [x] Installation and configuration described
  - [x] How to run tests
  - [x] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

10. If a Release Review is required, the specification project team contacts the EMO to initiate the review by sending an email to emo@eclipse.org.
    (A Release Review is not required if the current release is a Service Release based on a previously successful Major or Minor
    release as indicated by a release record on the project's Releases page, e.g., the [Jakarta Servlet releases page](https://projects.eclipse.org/projects/ee4j.servlet/reviews).)
    - [ ] An issue will be created by the EMO to track the release review.
    - [ ] The specification project team requests approval for the release from the PMC by sending an email to ee4j-pmc@eclipse.org.
    - [ ] The specification project team then delivers an IP Log to the IP Team for their review as described in https://www.eclipse.org/projects/handbook/#pmi-commands-iplog.

11. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Comment by markt-asf** [comment]
Note: The correct copyright year for the specification and Javadoc is 2021 as work for 5.0.0 was completed in 2021 and there have been no changes since then. (So far, anyway).

**Comment by markt-asf** [comment]
I've submitted a PR to the TCK project to update the EL TCK version from 4.0 to 5.0

I believe that the only remaining outstanding issue is for Glassfish to pass the TCK and the associated paperwork.

**Comment by Pandrex247** [comment]
Just for clarity since I don't think edits to comments send notifications: I updated my checklist comment, but there are still some things outstanding:
* Compatibility certification link missing
* Should the Compatible Implementation just be GlassFish 7 (final)? Should be an RC I believe? Could it not potentially point to Expressly rather than GlassFish? The compatible implementation for EL 4.0 _says_ GlassFish but the CCR actually lists EL-RI
* TCK Results missing

**Comment by Pandrex247** [comment]
I also can't see if you've kicked off a release review with the EMO - see the initial PR template checklist

**Comment by markt-asf** [comment]
Sorry, I missed the additional version issues. I've created https://github.com/eclipse-ee4j/jakartaee-tck/pull/921 to address those.

I was expecting the CCR to come from Glassfish.

My understanding is that I need to wait for the CCR before I can initiate the release review.

**Comment by Pandrex247** [comment]
Last I checked GlassFish still fails 9 TCK tests using Expressly (EL-RI) - Arjan looks to be making a move on them shortly.
If the implementation used by Tomcat or another vendor currently passes though we could use that instead for ratification :)

**Comment by arjantijms** [comment]
@Pandrex247 

Indeed, I just started to look at the 9 failures. The TCK is quite easy to run with Tomcat as well, as it really only wants a jar and a setting for a variable mapper, which is `"org.apache.el.lang.VariableMapperImpl"`. The Tomcat jar for Expression Language is:

```xml
<dependency>
    <groupId>org.apache.tomcat</groupId>
    <artifactId>tomcat-jasper-el</artifactId>
    <version>10.1.0-M14</version> 
</dependency> 
```

**Comment by arjantijms** [comment]
> I'm fairly sure I just copied and pasted the code for those tests and just tweaked the expression to be evaluated. I'm happy to review proposed alternative approaches to these tests if that is what is required.

There's only a small change needed really (adding the `jakarta.el.BeanELResolver.BeanELResolver` to the test ELContext) though some of the test code could do with a little bit of additional refactoring.

The copy/pasted code is in a way the issue, as the original TCK writers never considered the method invocation case, which I think is weird, but it is what it is.

**Comment by arjantijms** [comment]
Everything is fixed now; TCK has been updated and made available in the updated version, and GF (via Expressly) now passes the full TCK.

The CCR: https://github.com/jakartaee/expression-language/issues/185

**Comment by markt-asf** [comment]
Just a rebase

**Comment by markt-asf** [comment]
@Pandrex247 I think we are at the point where I can email the PMC and the EMO. Once you confirm that, I'll get those emails sent.

**Comment by Pandrex247** [comment]
Nice!
Had another look, and I spotted that the `_index.md` file is missing a link to Expressly - it currently just says _Expressly 5.0.0-M2_ without a link to it.

Aside from that yeah the only other thing outstanding that I can see is the email to the PMC and the release review with the EMO.

**Comment by markt-asf** [comment]
Emails sent.

**Comment by arjantijms** [comment]
Release review tracking issue: https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/273

**Review by Pandrex247 — APPROVED** [review]

**Comment by Pandrex247** [comment]
On ballot completion, the specification committee mentor:

- [x] Adds this final checklist to the main PR.
- [x] Adds the approved label to the PRs, and sends out the Ballot Summary per this [template](https://github.com/jakartaee/specification-committee/blob/master/spec_finalization_checklist.md#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](https://github.com/jakartaee/specification-committee/blob/master/jakarta.ee-spec@eclipse.org)
- [ ] Calculates the staged EFTL TCK signature and promotes it to the committee download area using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
- [ ] Merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
- [ ] Updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
- [ ] Notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](https://github.com/jakartaee/specification-committee/blob/master/emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
- [ ] Creates an issue in the specification project that includes the following checklist for the specification project team: <include url of Issue here>

**Pull request merged**
