### PR TITLE
Jakarta XML Web Services 4.0 Plan Review

### PR DESCRIPTION
**Pull request by lukasj**
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>

## Plan Review PR template
When creating a specification project plan review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version.
- [x] An index page wombat/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
- [x] Title should be on the form "Jakarta Wombat X.Y (under development)"
- [x] Includes a plan for the release. Usually, a couple of statements is enough. Otherwise, a link to a document describing the release.
- [x] N/A - Includes a detailed description of any backward incompatibility (Mark with **N/A** and check if none)
- [x] N/A - Declares optional features if there are any (Mark with **N/A** and check if none)
- [x] Includes minimum Java SE version
- [x] N/A - Describe any updates or required changes including splitting out the TCK (Mark with **N/A** and check if not planned)
- [x] Link to updated release record
      https://projects.eclipse.org/projects/ee4j.jaxws/releases/4.0-jakarta-xml-web-services

### CODE REVIEW

**Comment by andymc12** [comment]
Would it be possible to put more details into the plan review?  For example, I see this bullet item:
> - provide features requested by the community

What community-requested features are planned for JAX-WS 4.0?

> - adopt changes from other specification included in Jakarta EE 10

Which changes from which specs?

> - consider folding Jakarta Web Services Metadata and Jakarta SOAP w/Attachments into this (master) Specification

+1 to this, but I'd remove the word "consider" and state that it is a goal of the release to fold in these specs.

> - (major release due to changes in Jakarta XML Binding)

Can you provide more details here on what JAXB changes are causing the major version increase?  Maybe just provide a link to the JAXB 4.0 release plan?  

Thanks!

**Comment by andymc12** [comment]
@lukasj thanks for the info!

**Review by kwsutter — APPROVED** [review]
Looks like Jun (Primeton) has already started the ballot.  But, since he doesn't have a github id yet, I am reviewing and approving the PR ready for ballot.

**Comment by lukasj** [comment]
Is there anything I need to do here to move this forward?

**Pull request merged**
