### PR TITLE
Update for Jakarta Batch 2.1.1 Service Release

### PR DESCRIPTION
**Pull request by scottkurz**
## Specification Service Release PR template
When creating a service release, create PRs with the content defined as follows.

Include the following in the PR:
- [X] The URL of the Eclipse Project release record:
https://projects.eclipse.org/projects/ee4j.batch/releases/2.1.1
- [X] The URL of the OSSRH staging repository for the api, javadoc:
N/A
- [X] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
https://download.eclipse.org/jakartabatch/tck/eftl/jakarta.batch.official.tck-2.1.1.zip
- [X] The URL of the compatibility certification request (CCR) issue:
  Reusing earlier CCR: https://github.com/eclipse-ee4j/batch-api/issues/197 - we will include a comment noting this impl has been validated against the new v2.1.1 TCK
- [X] Specification JavaDoc in the `wombat/x.y/apidocs` directory.
- N/A
- [X] Changelog file at this location describing service release updates, `wombat/x.y/changelog`.
- [X] Update `wombat/x.y/_index.md` accordingly.
- [X] Start service release review by emailing [Specification Committee](https://accounts.eclipse.org/mailing-list/jakarta.ee-spec) and referencing this PR.
https://www.eclipse.org/lists/jakarta.ee-spec/msg02626.html

Note: Specifications themselves do not have service releases.  Only the associated API (limited to JavaDoc updates), JavaDoc, and TCK artifacts can have service releases.  Thus, the Specification version does not use the third digit -- only the `x.y` version is used in the Specification directory structure.
 
@scottmarlow can you please take a look before I email the Specification Committee?  Let me ping @starksm64 too to take a look.  Thank you.

Thank you !

## UPDATE after reading more

In my reading of it, the service release process doesn't really clarify the case where you are only updating a TCK but not the API/Javadoc or spec... so I'm interested to hear what all you think is required here.  E.g. we don't need to produce a Maven release of the API at v2.1.1 just to match this service release do we?  Thanks.

### CODE REVIEW

**Comment by scottmarlow** [comment]
> The URL of the compatibility https://github.com/eclipse-ee4j/batch-api/issues/197 request (CCR) issue:
Do I need to do a new CCR? I'm claiming that the certification against the v2.1.0 TCK should still be valid.

While it is not required, it would be valuable to indicate which compatible implementations are still passing with the TCK update (for compatible implementations that happen to have access to the the updated TCK).  I believe that typically, only the compatible implementation that was used for ballot, is tested against the updated TCK but it would be good to open this up to others in the community as well (the how to do can be a future discussion point).

I agree with not providing a new CCR since existing compatible Batch implementations just need to `self validate` that they pass with either https://download.eclipse.org/jakartabatch/tck/eftl/jakarta.batch.official.tck-2.1.0.zip or newer.

**Comment by scottkurz** [comment]
> > The URL of the compatibility [eclipse-ee4j/batch-api#197](https://github.com/eclipse-ee4j/batch-api/issues/197) request (CCR) issue:
> > Do I need to do a new CCR? I'm claiming that the certification against the v2.1.0 TCK should still be valid.
> 
> While it is not required, it would be valuable to indicate which compatible implementations are still passing with the TCK update (for compatible implementations that happen to have access to the the updated TCK). I believe that typically, only the compatible implementation that was used for ballot, is tested against the updated TCK but it would be good to open this up to others in the community as well (the how to do can be a future discussion point).
> 
> I agree with not providing a new CCR since existing compatible Batch implementations just need to `self validate` that they pass with either https://download.eclipse.org/jakartabatch/tck/eftl/jakarta.batch.official.tck-2.1.0.zip or newer.

OK maybe I'll add a note to the existing CCR mentioning the run against 2.1.1 TCK.  Thanks.

**Comment by scottkurz** [comment]
Haven't gotten any further response yet to the PR or my email so I'll plan on trying to add this to the Tuesday platform agenda if I don't hear more by then.

**Comment by scottkurz** [comment]
> There is no reason to produce a new api jar just because the tck has had a micro release. So I would not say there are changes in a 2.1.1 release. Those changes could just be internal release notes in the TCK dist.

So @starksm64 you're basically saying that I was wrong to read into the [TCK Process](https://jakarta.ee/committees/specification/tckprocess/) the need to do a new Eclipse service release record.   

Instead I should just literally follow the instructions at the end, in:  **Process for releasing a point revision of a TCK**

> The process for releasing a point revision of a TCK entails filing an issue in the [jakartaee/specifications repository with the following details](https://github.com/jakartaee/specifications):
> 
>     Link to the TCK release to be published.
>     Updated TCK links in the specification’s _index.md file.
>     A high-level description of what tests were excluded from the TCK and why.

OK, that makes more sense to me.  Thanks.

**Comment by starksm64** [comment]
I don't see where a service release record is called out in the tck process. Can you highlight the text that calls for this?

That end part is the only thing that makes sense to me.

**Comment by scottkurz** [comment]
> I don't see where a service release record is called out in the tck process. Can you highlight the text that calls for this?
> 
> That end part is the only thing that makes sense to me.

Now that you've made the comment your interpretation makes sense to me, and no, I don't see specific text that calls for a service release record.   

To explain my confusion, (and I'm not trying to argue in favor of this interpretation), I was just looking at the term "service release" in the TCK process and saying "let me search around to make sure I gather up all the rules regarding service releases" 
and noting the description in:   https://jakarta.ee/committees/specification/operations/ for doing the "spec + API" service release.

I should've stopped with the TCK process doc.

**Comment by Emily-Jiang** [comment]
@scottkurz , you don't need to create this PR at all. EF allows us to freely perform service release and you can publish the service release to maven central. Basically @starksm64 is correct. You can do the tck or apis separately as you wish when it comes to service release.

**Comment by scottmarlow** [comment]
Only EPL licensed TCK zips can currently be pushed to public Maven repositories.  The EPL licenses TCK zips can be used for development but cannot be used for compatibility certification requests.  

In order for the EFTL licensed TCK to be copied to https://download.eclipse.org/jakartaee/batch/2.1, someone with permissions to copy files to that location, needs to know to copy the 2.1.1 TCK to there.  A [spec issue](https://github.com/jakartaee/specifications/issues) can be created requesting that to happen (typically by someone on the Jakarta EE Specification committee).  A [recent example is here.](https://github.com/jakartaee/specifications/issues/321).  An example [pull request to update the specification page content to reference the new TCK is here](https://github.com/jakartaee/specifications/pull/323).

**Comment by scottkurz** [comment]
Thank you Emily, Scott S., Scott M...will close this issue.

**Pull request closed without merging**
