### PR TITLE
Pages 3.1.0 release

### PR DESCRIPTION
**Pull request by markt-asf**
## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [X] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [X] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
- [X] Specification HTML in the form of jakarta-wombat-spec-x.y.html
- [X] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [x] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [x] Updated release record
   - [x] Generated IP Log
   - [x] Email to PMC
   - [x] Start release review by emailing EMO 
- [X] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/servlet/jsp/jakarta.servlet.jsp-api/3.1.0/
- [X] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-pages-tck-3.1.0.zip
- [X] The URL of the compatibility certification request issue:
      https://github.com/eclipse-ee4j/jsp-api/issues/227
- [X] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by keilw** [comment]
@markt-asf The last commits contained a "Partial update in preparation for release review", do you expect to be done in time for Jakarta EE 10? 
Also the API repo (still in EE4J) contains only 3 issues tagged "Jakarta EE 10" https://github.com/eclipse-ee4j/jsp-api/issues?q=label%3A%22Jakarta+EE+10%22+is%3Aclosed all of them closed by "glassfishrobot", while 2 or 3 others were closed late 2021 but they are missing the "Jakarta EE 10" or "3.1" label or similar, so it's a bit hard to link them to the 3.1.0 release.

**Comment by markt-asf** [comment]
I've been done for months. The delay has been with the TCK project. The staged binary looks to be available now so I'll get that added. The certification request should be all that is missing then.

You are misreading the issue data. Those issues were opened by glassfishrobot (they have been through multiple migrations) but were closed by me.

I'll go through the closed issues and add the Jakarta EE 10 tag to any issue that resulted in a spec doc change or an API change. My intention is not to tag issues that could be considered lower-level house-keeping (for example fixing copyright dates).

**Comment by markt-asf** [comment]
For the record there were two other issues closed late last year. I've added the label to one. The other was resolved as "won't fix" so I opted not to add a label.

**Comment by markt-asf** [comment]
The only reason this was draft was the lack of TCK download location in `_index.md`. I've added an educated guess for that.

**Comment by keilw** [comment]
@markt-asf So otherwise it is ready?

**Comment by markt-asf** [comment]
As far as I am aware, it just needs the CCR which I am currently assuming will come from Glassfish at some point. Other than that, I believe Jakarta Pages 3.1.0 is good to go.

**Comment by markt-asf** [comment]
Glassfish submitting a certification request.

**Comment by keilw** [comment]
@markt-asf I believe based on the discussion in the Spec Committee calls, that Glassfish could only submit that after it passes the TCK and not the other way round. What keeps Glassfish from passing the TCK? 
I saw REST also had some troubles and withdraw its review.

**Comment by markt-asf** [comment]
@keilw That would be a question for the Glassfish project. I'm not aware of any issues with either the Pages 3.1.0 release or the associated TCK that would prevent Glassfish from passing the TCK.

**Comment by arjantijms** [comment]
@keilw 
>  Who at Glassfish is responsible for passing the TCK or file the certification request?

It would be great if you could help. Run the TCK against GlassFish 7 m3, and if there's anything failing try to fix it. Maybe you can start here: https://github.com/eclipse-ee4j/wasp/issues/43

**Comment by keilw** [comment]
# Spec Review Checklist

1. Spec PR
  - [x] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [x] Directory of form {spec}/x.y
  - [x] PDF of form jakarta-{spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [x] HTML of form jakarta-{spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [x] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta.{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] (Optional) Second PR for just apidocs

2. _index.md
  - [ ] Link to project release plan of the form https://projects.eclipse.org/projects/ee4j.{spec}/releases/x.y/plan
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip (The folder path is required, the file name pattern is preferred.)
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation
  - [ ] Review summary statement to ensure it has been updated to reflect the work accomplished and does not contain proposal statements as might be found in Plan Review statement.

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [x] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [x] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

10. If a Release Review is required, the specification project team contacts the EMO to initiate the review by sending an email to emo@eclipse.org.
    (A Release Review is not required if the current release is a Service Release based on a previously successful Major or Minor
    release as indicated by a release record on the project's Releases page, e.g., the [Jakarta Servlet releases page](https://projects.eclipse.org/projects/ee4j.servlet/reviews).)
    - [ ] An issue will be created by the EMO to track the release review.
    - [ ] The specification project team requests approval for the release from the PMC by sending an email to ee4j-pmc@eclipse.org.
    - [ ] The specification project team then delivers an IP Log to the IP Team for their review as described in https://www.eclipse.org/projects/handbook/#pmi-commands-iplog.

11. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Comment by keilw** [comment]
9 tests for Pages are currently failing, see https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Jakarta-EE-10.0-TCK-results

Given the removal of support for NPAPI by browsers, we probably need to look at deprecating and removing <jsp:plugin> and associated structures. I could get the work done for that fairly quickly (in the next 24-28 hours) but is it practical to get that done for Jakarta EE 10?

Given the specs will still support <jsp:plugin> where use of applet is valid, this change seems like the simplest way forward for the TCK.

**Comment by arjantijms** [comment]
> 9 tests for Pages are currently failing, see https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Jakarta-EE-10.0-TCK-results

Where do you see 9 tests failing? GlassFish 7 (M4) should fully pass the pages TCK.

**Comment by keilw** [comment]
@markt-asf there are still a few items open aside from the TCK test results:

- [Jakarta Server Pages 3.0 TCK](https://download.eclipse.org/jakartaee/pages/3.1/jakarta-pages-tck-3.1.0.zip) says 3.0 but links to 3.1.0
- The project Release Plan link also still points to https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee10/JakartaEE9ReleasePlan is that intended, or shouldn't the last part be JakartaEE10ReleasePlan?
- There's no pointer to at least one Compatible Implementation (probably due to the TCK failures)

**Comment by scottmarlow** [comment]
> > 9 tests for Pages are currently failing, see https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Jakarta-EE-10.0-TCK-results
> 
> Where do you see 9 tests failing? GlassFish 7 (M4) should fully pass the pages TCK.

https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Jakarta-EE-10.0-TCK-results is mentioned above, which links to https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/1746/nodes/147/steps/1145/log/?start=0 

^ ran against https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.0-SNAPSHOT-nightly.zip on Sunday April 17, 2022.

From looking in the linked content, the first failure shows a warning about a HTTP 500 and also a `jakarta.servlet.ServletException: java.lang.ClassCastException: class org.glassfish.wasp.runtime.ELContextWrapper cannot be cast to class org.glassfish.wasp.runtime.ELContextImpl`.

**Comment by arjantijms** [comment]
@scottmarlow maybe someone who's more up to date with those exact scripts and the TCK CI can explain those.

When I run the TCK everything passes. See: https://ci.eclipse.org/jsp/job/2_jsp-run-tck-against-staged-build/lastSuccessfulBuild/artifact/pages-tck/bin/summary.txt/*view*/

I also tried to run it locally, and run some of the code manually.

**Comment by arjantijms** [comment]
CCR: https://github.com/eclipse-ee4j/jsp-api/issues/227

**Comment by scottmarlow** [comment]
> @scottmarlow maybe someone who's more up to date with those exact scripts and the TCK CI can explain those.
> 
> When I run the TCK everything passes. See: https://ci.eclipse.org/jsp/job/2_jsp-run-tck-against-staged-build/lastSuccessfulBuild/artifact/pages-tck/bin/summary.txt/*view*/
> 
> I also tried to run it locally, and run some of the code manually.

Correction:  You are right, there are no Pages Standalone TCK failures with GlassFish.  

The Pages tests are only failing in the Platform TCK run, not the Standalone Pages TCK run with GlassFish (those standalone Pages tests are all passing on https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1750/testReport/).

**Comment by arjantijms** [comment]
Thanks for the update Scott. So then it's still a mystery why they are failing there, perhaps an older build? But that's a worry for a little later then.

**Comment by arjantijms** [comment]
Currently waiting for a new staging of the Jakarta Pages 3.1 TCK: https://github.com/eclipse-ee4j/jakartaee-tck/issues/941

**Comment by scottmarlow** [comment]
> Currently waiting for a new staging of the Jakarta Pages 3.1 TCK: [eclipse-ee4j/jakartaee-tck#941](https://github.com/eclipse-ee4j/jakartaee-tck/issues/941)

New Pages TCK is staged.

**Comment by arjantijms** [comment]
@scottmarlow new build of GlassFish and WaSP was used to run the newly staged Pages TCK and it passed.

CCR has been updated.

**Comment by arjantijms** [comment]
Release review link: https://projects.eclipse.org/projects/ee4j.jsp/reviews/3.1.0-release-review

**Comment by arjantijms** [comment]
CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24081

**Comment by arjantijms** [comment]
Mail to EMO send

Mail to PMC send: https://eclipse.org/lists/ee4j-pmc/msg03337.html

@markt-asf can you check the items off for those in the list above? Release record is up to date as well.

**Comment by arjantijms** [comment]
@ivargrimstad and @keilw I think we can go to ballot now?

**Comment by arjantijms** [comment]
Project Review Issue: https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/281

**Comment by arjantijms** [comment]
@keilw @ivargrimstad just a PING ;)

Can Pages go to ballot now?

**Comment by ivargrimstad** [comment]
@keilw Please finish the review and start the ballot if everything looks good. I will do it tomorrow if not done by then

**Comment by keilw** [comment]
@ivargrimstad, @arjantijms The  link to the Compatible implementation still says "Glassfish version TBD", can it stay like that for the ballot?

**Comment by arjantijms** [comment]
@ivargrimstad @keilw @markt-asf 

Can you adjust it to

[Eclipse WaSP 3.1.0-M3](https://github.com/eclipse-ee4j/wasp)
Vehicle: [Eclipse Glassfish 7.0.0-28-04-2022](https://github.com/eclipse-ee4j/glassfish/releases/download/7.0.0-28-04-2022/glassfish.zip)

See https://github.com/eclipse-ee4j/jsp-api/issues/227

Thanks!

**Comment by arjantijms** [comment]
@ivargrimstad can I start the ballot too? It's probably in the rules somewhere, but as today is the deadline and things are getting a bit tight, I'll write the email to start the ballot just to be sure. If it's not valid, then too bad, but then I've at least tried.

**Comment by ivargrimstad** [comment]
> @ivargrimstad can I start the ballot too? It's probably in the rules somewhere, but as today is the deadline and things are getting a bit tight, I'll write the email to start the ballot just to be sure. If it's not valid, then too bad, but then I've at least tried.

Werner or I will start it Monday morning.

**Comment by starksm64** [comment]
Just get everything ready in the PRs and the spec committee mentors will
start the ballots.

**Comment by keilw** [comment]
# On ballot completion, the specification committee mentor:
 - [x] adds this final checklist to the main PR.
 - [x] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [ ] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
 - [ ] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [ ] creates an issue in the specification project that includes the following checklist for the specification project team:

**Pull request merged**
