### PR TITLE
Servlet 6.0.0 release

### PR DESCRIPTION
**Pull request by markt-asf**
## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [X] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [X] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
- [X] Specification HTML in the form of jakarta-wombat-spec-x.y.html
- [X] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [X] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [X] Updated release record
   - [X] Generated IP Log
   - [ ] Email to PMC
   - [ ] Start release review by emailing EMO 
- [X] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/servlet/jakarta.servlet-api/6.0.0/
- [X] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-servlet-tck-6.0.0.zip
- [X] The URL of the compatibility certification request issue:
      https://github.com/jakartaee/servlet/issues/464
- [X] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

### CODE REVIEW

**Comment by edbratt** [comment]
Could someone please have a look at why the deploy preview for this PR has failed?

**Comment by markt-asf** [comment]
I was expecting the CCR to come from Glassfish.

**Comment by marceloancelmo** [comment]
will check glassfish in this case @markt-asf

**Comment by markt-asf** [comment]
@dblevins see https://www.eclipse.org/lists/servlet-dev/msg00454.html
The view of the Servlet project was not to change the TCK so as things stand Tomcat cannot pass it (and the Tomcat team is fine with that).

**Comment by arjantijms** [comment]
> will check glassfish in this case @markt-asf

GlassFish passes the Servlet 6 TCK indeed. I can do a CCR for sure. I first thought Tomcat wanted to honour of passing first, as most of the work was done there, and GF just used it. But it's perfectly fine for us to the CCR.

**Comment by ivargrimstad** [comment]
# Mentor's Spec Review Checklist

1. Spec PR
  - [ ] PR uses [template](https://github.com/jakartaee/specifications/blob/master/pull_request_template.md)
  - [ ] Directory of form {spec}/x.y
  - [ ] PDF of form jakarta-{spec}-spec-x.y.pdf ("-spec" preferred but not required)
  - [ ] HTML of form jakarta-{spec}-spec-x.y.html ("-spec" preferred but not required)
  - [ ] Index page {spec}/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
  - [ ] Index page {spec}/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_index_template.md)
  - [ ] No other files (e.g., no jakarta_ee_logo_schooner_color_stacked_default.png)
  - [ ] Staging repository link of the form https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/{spec}/jakarta.{spec}-api/x.y.z/
  - [ ] EFTL TCK link of the form http://download.eclipse.org/.../+.zip
  - [ ] Compatibility certification link of the form https://github.com/eclipse-ee4j/{project}/#{issue}
  - [ ] (Optional) Second PR for just apidocs

2. _index.md
  - [ ] Link to project release plan of the form https://projects.eclipse.org/projects/ee4j.{spec}/releases/x.y/plan
  - [ ] Link to spec pdf
  - [ ] Link to spec html
  - [ ] Link to apidocs
  - [ ] Link to final TCK download zip file of the form https://download.eclipse.org/jakartaee/{spec}/x.y/*{spec}-tck-x.y.z.zip (The folder path is required, the file name pattern is preferred.)
  - [ ] Link to API jar file of the form https://search.maven.org/artifact/jakarta.{spec}/jakarta.{spec}-api/x.y.z/jar
  - [ ] Name of and link to at least one Compatible Implementation
  - [ ] Review summary statement to ensure it has been updated to reflect the work accomplished and does not contain proposal statements as might be found in Plan Review statement.

3. javadocs
  - [ ] Footer contains Eclipse copyright and link to license
  - [ ] ESFL license is included, usually as doc-files/speclicense.html
  - [ ] no META-INF directory in PR
  - [ ] javadocs-jar artifact matches apidocs (optional for this release)

4. Spec PDF
  - [ ] Correct spec title
  - [ ] Version number of the form x.y, not x.y.z
  - [ ] Correct Eclipse copyright line
  - [ ] No DRAFT or SNAPSHOT
  - [ ] Correct Logo

5. Spec HTML
  - [ ] Same as PDF

6. TCK zip file
  - [ ] README file (optional for this release)
  - [ ] EFTL license file, preferably named LICENSE.md
  - [ ] User's Guide (or equivalent documentation)
  - [ ] How to test the Compatible Implementation(s) listed in _index.md above with the TCK (may be in UG)

7. TCK User's Guide (or equivalent documentation)
  - [ ] Software requirements listed
  - [ ] Installation and configuration described
  - [ ] How to run tests
  - [ ] Where to file challenges

8. Compatibility certification request
  - [ ] Request follows [template](https://github.com/jakartaee/specification-committee/blob/master/compatibility-certification-request.md)
  - [ ] SHA-256 fingerprint matches staged TCK zip file
  - [ ] Request issue has `certification` label.

9. TCK results summary
  - [ ] Page is hosted by Compatible Implementation project
  - [ ] Includes all information from certification request
  - [ ] Summary includes number of tests passed, failed, errors
  - [ ] SHA-256 fingerprint matches staged TCK zip file on cert request

10. If a Release Review is required, the specification project team contacts the EMO to initiate the review by sending an email to emo@eclipse.org.
    (A Release Review is not required if the current release is a Service Release based on a previously successful Major or Minor
    release as indicated by a release record on the project's Releases page, e.g., the [Jakarta Servlet releases page](https://projects.eclipse.org/projects/ee4j.servlet/reviews).)
    - [ ] An issue will be created by the EMO to track the release review.
    - [ ] The specification project team requests approval for the release from the PMC by sending an email to ee4j-pmc@eclipse.org.
    - [ ] The specification project team then delivers an IP Log to the IP Team for their review as described in https://www.eclipse.org/projects/handbook/#pmi-commands-iplog.

11. Update Jakarta EE API jar
  - [ ] Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Comment by arjantijms** [comment]
The CCR: https://github.com/jakartaee/servlet/issues/464

**Comment by markt-asf** [comment]
Just a rebase

**Comment by markt-asf** [comment]
@ivargrimstad I think we are at the point where I can email the PMC and the EMO. Once you confirm that, I'll get those emails sent.

**Comment by marceloancelmo** [comment]
Looking pretty good @markt-asf.

Let me take a look in everything and cross-check against the checklist

**Comment by gregw** [comment]
just a note to let you all that Jetty is some months off passing the Servlet 6.0 TCK.  We are taking the opportunity of the cleanup in 6.0 to do the same in jetty itself, so we are in the middle of a major refactor of jetty.... hence me not responding to this issue for some weeks!

See you on the other side!

**Comment by ivargrimstad** [comment]
@marceloancelmo The ballot must be run before merging! Please do a revert, then finalize the checklist and start the ballot.

**Comment by marceloancelmo** [comment]
Sorry @ivargrimstad , my bad as I merged by accident while doing the checklist. Reverted, checklist finalized and sending the email for the ballot now

**Comment by ivargrimstad** [comment]
No worries 
When the ballot completes, you just have to revert the revert-merge again and we're fine :)

**Comment by arjantijms** [comment]
>  I think we are at the point where I can email the PMC and the EMO. Once you confirm that, I'll get those emails sent.

I think we can send the emails now. If I'm not mistaken the emails can be send at any time, and not necessarily have to be send when everything is fully perfect here.

**Comment by marceloancelmo** [comment]
Good point @arjantijms , we can send the emails to PMC and EMO.

@markt-asf may I please ask you to send the emails?

**Comment by markt-asf** [comment]
Done.

**Comment by scottmarlow** [comment]
@markt-asf please confirm that you do not want one more Servlet TCK to be built with https://github.com/eclipse-ee4j/jakartaee-tck/pull/934?  

The discussion is on https://github.com/eclipse-ee4j/jakartaee-tck/issues/949

**Comment by scottmarlow** [comment]
> My preference is to merge the PR and rebuild the TCK if @arjantijms is happy to run the TCK again.

So we impact the EE 10 schedule if we delay for this change though, so I think we should continue the ballot.

**Comment by arjantijms** [comment]
Rerunning the TCK is not much of an issue for me, but as it would delay the ballot and we're extremely close to the last deadline, let's leave this test for next time then.

**Comment by marceloancelmo** [comment]
Agree on leaving TCK rerun for next time. 

I will update the ballot with the details about the update on the TCK results. Thank you @arjantijms

**Pull request merged**
